### ISSUE TITLE
The output of label.png is the black. 

### ISSUE THREAD

**Issue by 315386775** [wkentaro/labelme#10]
After the operation of Convert to Dataset. The output of label.png is all the black. The depth of the image is 16.  But the image size is the 60kb. Did anyone have this problem?

**Comment by wkentaro** [comment]
It is an expected behavior, you can see `label_viz.png` to see if labeling is good,
The example use of label.png is below:
```
In [1]: import PIL.Image

In [2]: img = PIL.Image.open('label.png')

In [3]: import numpy as np

In [4]: img = np.array(img)

In [5]: img
Out[5]: 
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [6]: np.unique(img)
Out[6]: array([0, 1, 2, 3], dtype=int32)

In [7]: import yaml

In [8]: yaml.load(open('info.yaml'))
Out[8]: 
{'label_names': ['background',
  'highland_6539_self_stick_notes',
  'kong_air_dog_squeakair_tennis_ball',
  'mead_index_cards']}

```

**Comment by 315386775** [comment]
@wkentaro Thx. Now i konw It is an expected behavior. but i want to use the 'label.png' as the FCN's image label. I check the voc2007 segemention object have many color. How to convert the label.png to the image label that i can be use in my research.

**Comment by wkentaro** [comment]
You can use `skimage.color.label2rgb(label)`, but it is just a visualization and it is not useful for fcn training.
VOC label also has int values in actual:

```
In [1]: import numpy as np

In [2]: import PIL.Image

In [3]: label = np.array(PIL.Image.open('VOC2012/SegmentationClass/2007_000032.png'), dtype=np.int32)

In [4]: np.unique(label)
Out[4]: array([  0,   1,  15, 255], dtype=int32)  # 0-21: class labels, and 255 means unlabeld
```
