### ISSUE TITLE
Unable to run after installation

### ISSUE THREAD

**Issue by lightbearer88** [wkentaro/labelme#1006]
Hi,

First off, I performed the following commands when installing (Windows 10, using Anaconda):
```
conda create --name=labelme python=3
source activate labelme
conda install labelme -c conda-forge
```
After that, I used the following command in Jupyter Notebooks:

`!labelme`

And I got the following error:
```
Traceback (most recent call last):
  File "C:\Pythons\envs\labelme\Scripts\labelme-script.py", line 6, in <module>
    from labelme.__main__ import main
  File "C:\Pythons\envs\labelme\lib\site-packages\labelme\__init__.py", line 17, in <module>
    QT4 = QT_VERSION[0] == "4"
TypeError: 'NoneType' object is not subscriptable
```
Did I do something wrong or is there a bug?

**Comment by llokng922** [comment]
This is probably because pyqt is not installed probably.

**Comment by ksooklall** [comment]
I had the same issue then ran `conda install -c anaconda pyqt`, but now I have this issue

```
Traceback (most recent call last):
  File "/home/kenan/anaconda3/envs/labelme/lib/python3.10/site-packages/labelme/widgets/canvas.py", line 618, in paintEvent
    p.translate(self.offsetToCenter())
  File "/home/kenan/anaconda3/envs/labelme/lib/python3.10/site-packages/labelme/widgets/canvas.py", line 659, in offsetToCenter
    return QtCore.QPoint(x, y)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'
Aborted (core dumped)
```

**Comment by parksangback** [comment]
i resolved this problem!!

**Comment by mkpvasu** [comment]
After solving the above error, I am running to an additional error

Traceback (most recent call last):
  File "C:\Users\munikumar\anaconda3\envs\labelme\lib\site-packages\labelme\widgets\canvas.py", line 245, in mouseMoveEvent
    if QtCore.Qt.RightButton & ev.buttons():
TypeError: unsupported operand type(s) for &: 'MouseButton' and 'MouseButtons'

Does anyone know how to rectify this?

**Comment by aurelien-m** [comment]
Any news on this? How could it work before with `return QtCore.QPoint(x, y)`?

**Comment by oikonochristina** [comment]
i am having the same issue with @mkpvasu , how could we solve this typeError?

**Comment by LancerXE** [comment]
It might because pyqt5 is not installed, try this:
`pip install pyqt5`
and then run labelme: `labelme`

**Comment by danilosjc** [comment]
Hey, I fixed the problem. I just did the following:
First I did the changes like @parksangback said above

cd /home/<input_your_ubuntu_name>/anaconda3/envs/labelme/lib/python3.10/site-packages/labelme/widgets/
sudo gedit canvas.py
In the scripts ,key input (Ctrl+f :return QtCore.QPoint(x, y)).
Then you can see the code which is making the error.
Let's change the code about like under line!!
from
return QtCore.QPoint(x, y)
to
return QtCore.QPoint(int(x),int(y))

But I continued getting error (but a different one). 
So I installed pyqt5 and natshore with pip

and edited the files app.py and label_list_widget.py

 I replaced my app.py by https://github.com/wkentaro/labelme/blob/main/labelme/app.py and edited line 1373 like this instruction: 

For details: In file app.py under root dir of label me, line 1373 about, should force change type to int:

def setScroll(self, orientation, value):
    self.scrollBars[orientation].setValue(int(value))
    self.scroll_values[orientation][self.filename] = value

and also edited the file label_list_widget.py as follow

In file label_list_widget.py under widgets, in the method sizeHint, a force type change to in should be added: about line 62

def sizeHint(self, option, index):
    thefuckyourshitup_constant = 4
    return QtCore.QSize(
        int(self.doc.idealWidth()),
        int(self.doc.size().height() - thefuckyourshitup_constant),
    )

Source: https://pythontechworld.com/issue/wkentaro/labelme/1159

Good luck!
