### ISSUE TITLE
When changing the label value with label edit, the program crashes.

### ISSUE THREAD

**Issue by sangwoo89** [wkentaro/labelme#1021]
app.py (1171 row)
item = self.uniqLabelList.findItemsByLabel(label)[0]
there is out of range error.

add code.. good working.

 def _get_rgb_by_label(self, label):
        if self._config["shape_color"] == "auto":
 if not self.uniqLabelList.findItemsByLabel(label):
                item = QtWidgets.QListWidgetItem()
                item.setData(Qt.UserRole, label)
                self.uniqLabelList.addItem(item)

item = self.uniqLabelList.findItemsByLabel(label)[0]

**Comment by wkentaro** [comment]
Will be fixed by v5.0.2

```
pip install --no-cache-dir labelme==5.0.2
```
