### ISSUE TITLE
Not working in Ubuntu 22.04

### ISSUE THREAD

**Issue by ffreitas-dev** [wkentaro/labelme#1040]
As soon as I just installed it from the gnome store, it opens and closes immediately. Any chance to export the project to flatpak?

**Comment by fiastros** [comment]
I'm having the same issue on ubuntu 22.04. The Gui opens and then closes when i click on anything

**Comment by wkentaro** [comment]
Moving to https://github.com/wkentaro/labelme/issues/1006
