### ISSUE TITLE
Error saving label data with Python2 + macOS Sierra

### ISSUE THREAD

**Issue by codecolony** [wkentaro/labelme#11]
While saving the json, I get the following error. Any idea to resolve this issue?

a bytes-like object is required, not 'str'

**Comment by codecolony** [comment]
Actually, I think this is because of python 3 that I'm using because installing on MAC Sierra with python 2 failed. 

I get error "Please install pyrcc4 command." even after installing pyqt5. Any ideas how to resolve this?

**Comment by wkentaro** [comment]
Please follow the installation guide: https://github.com/wkentaro/labelme#installation

**Comment by codecolony** [comment]
Hi @wkentaro ,

I followed the same guide but got many errors.

For example, on Mac Sierra, I installed pyqt5 first but the second command fails with following error.

Complete output from command python setup.py egg_info:
    Please install PyQt5.

Why does it ask me to install pyqt5 again?

Thanks in advance.

**Comment by wkentaro** [comment]
Maybe you need to run `brew uninstall pyqt5; brew install pyqt5 --with-python`.
I have just updated README, so please refer it for detail.

**Comment by Dean-TianZhang** [comment]
Hi @wkentaro ,

I also have followed the installation instruction of Labelme in the updated Readme file, but I get the same problem as @codecolony that 'a bytes-like object is required, not 'str'. What should I do next?

Meanwhile, I also have difficulties in load image to the workspace in GUI, and I can only load image through the command like 'labelme  _static/apc2016_obj3.jpg'.

Could you give me some instructions about these two aspects?

Thanks!

**Comment by wkentaro** [comment]
Above instruction is for Python2 on macOS Sierra. Is that so in your environment?

**Comment by Dean-TianZhang** [comment]
Thanks for soon reply. Mine is macOS Sierra with python3(pyqt5 installed)

**Comment by wkentaro** [comment]
Please try below:

```bash
pip uninstall labelme
pip3 uninstall labelme
rm -f /usr/local/bin/labelme
rm -f `which labelme`

brew uninstall pyqt5
brew install pyqt5
pip3 install git+https://github.com/wkentaro/labelme.git@pyqt5
labelme IMG_FILE.jpg
```

**Comment by Dean-TianZhang** [comment]
It still has the same problem I told before. But the Linux version Label runs normally. I think it may be caused by the qt version.

**Comment by wkentaro** [comment]
Hmm, it works on my env. Sorry, I'm not sure about the other possible solutions for this.

**Comment by wkentaro** [comment]
It seems that current solution for you is use of docker:

https://github.com/wkentaro/labelme#installation
