### ISSUE TITLE
labelme2voc.py  error!!!!

### ISSUE THREAD

**Issue by bbidong** [wkentaro/labelme#111]
When i run labelme2voc.py , i meet the follow error:
AttributeError: 'module' object has no attribute 'shapes_to_label' ,
what should i do??

**Comment by wkentaro** [comment]
Maybe you need to install the latest labelme by 
```
pip install git+https://github.com/wkentaro/labelme.git

# or 
git clone https://github.com/wkentaro/labelme.git
cd labelme
pip install .
# or pip install -e .
```
