### ISSUE TITLE
Convert to dataset error

### ISSUE THREAD

**Issue by zouwt189** [wkentaro/labelme#114]
When I convert the json to set of image and label, and run as labelme_json_to_dataset examples/single_image/apc2016_obj3.json -o examples/single_image/apc2016_obj3_json
get the result:
Traceback (most recent call last):
  File "/Users/zouwentong/anaconda3/bin/labelme_json_to_dataset", line 11, in <module>
    sys.exit(main())
  File "/Users/zouwentong/anaconda3/lib/python3.6/site-packages/labelme/cli/json_to_dataset.py", line 34, in main
    os.mkdir(out_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'examples/single_image/apc2016_obj3_json'

I don't know why, hope you can help me!

**Comment by wkentaro** [comment]
Are you sure that you have examples/single_image/apc2016_obj3.json?

**Comment by zouwt189** [comment]
The file is there for sure.

**Comment by zouwt189** [comment]
Thank you very much, I've already solved the problem. The directory is wrong.
