### ISSUE TITLE
Disabling double_click in the config file doesn't work.

### ISSUE THREAD

**Issue by Bosezz** [wkentaro/labelme#1147]
https://github.com/wkentaro/labelme/blob/e8e821000f89aea3d8e2d9c2e3b3c3ea032e880f/labelme/widgets/canvas.py#L42

It should be "None" to work. It doesn't work the way it is now since it always crashes with "ValueError" if I put double_click: None in my config file because it seems to read the entries from the config files as Strings. It worked when I changed None to "None" in Line 42.

**Comment by wkentaro** [comment]
You need to specify `null` as it is JSON.
