### ISSUE TITLE
Error: "module 'labelme.utiles'has no attribute'shapes_to_label'"

### ISSUE THREAD

**Issue by piaopiaow** [wkentaro/labelme#115]
Hello , I use the labelme installed under Windows, but I can't use it directly to open a folder and label all the images. There is no "File List" option on the right. And can not be converted to VOC format data set. Error: "module 'labelme.utiles'has no attribute'shapes_to_label'". I have installed the latest labelme. Why is there such a problem?

**Comment by wkentaro** [comment]
It is because you use the old version of labelme which is released to pypi: v2.8.0.
File List and shapes_to_label is only supported with latest labelme, but unsupported with the released labelme, v2.8.0.
If you would like to use the latest labelme, you should do

```
git clone https://github.com/wkentaro/labelme.git
cd labelme
pip install .

# or 

pip install git+https://github.com/wkentaro/labelme.git
```

**Comment by wkentaro** [comment]
This issue is close to https://github.com/wkentaro/labelme/issues/111.

**Comment by wkentaro** [comment]
I added instruction here: https://github.com/wkentaro/labelme#anaconda
