### ISSUE TITLE
Update README instructions for the right Python version

### ISSUE THREAD

**Issue by dr-smgad** [wkentaro/labelme#1176]
### Provide environment information

The installation instructions in the README file are not accurate as the conda env creation step mentions **python=3** while this won't work (at least on Windows OS as I tried, it gives error can't find labelme command, also I tried to add to Path but in vain), when changing this to **python=3.8** everything worked fine.

### What OS are you using?

Windows

### Describe the Bug

Anaconda command prompt can't find command "labelme" after activating the labelme conda environment.

**Comment by wkentaro** [comment]
I can run with Python 3.9 and 3.10 on Conda on macOS. So could you check again with the latest labelme?
