### ISSUE TITLE
labelme

### ISSUE THREAD

**Issue by she-666** [wkentaro/labelme#1206]
### Provide environment information

(labelme) C:\Users\s\Desktop\example>python labelme2voc.py images target --labels labels.txt
Creating dataset: target
class_names: ('_background_', 'SAT', 'VAT', 'Muscle', 'Bone', 'Gas', 'Intestine')
Saved class_names: target\class_names.txt
Generating dataset from: images\A004.json
Traceback (most recent call last):
  File "labelme2voc.py", line 106, in <module>
    main()
  File "labelme2voc.py", line 95, in main
    viz = imgviz.label2rgb(
TypeError: label2rgb() got an unexpected keyword argument 'img'

### What OS are you using?

python3.6 labelme3.16

### Describe the Bug

My file is labelme2voc.py. I can't find img in label2rgb(). And all  my try are wrong.

**Comment by wkentaro** [comment]
Maybe you're not using the latest `labelme2voc.py`?

**Comment by wkentaro** [comment]
This is the latest
<img width="487" alt="image" src="https://user-images.githubusercontent.com/4310419/198878402-d009545f-f953-4107-945e-da4df2320e68.png">

**Comment by kanikshas4** [comment]
I got the same issue. 

Creating dataset: /Users/kanikshasharma/Downloads/labelme-master/examples/semantic_segmentation/Train_new6
class_names: ('_background_', 'Rust')
Saved class_names: /Users/kanikshasharma/Downloads/labelme-master/examples/semantic_segmentation/Train_new6/class_names.txt
Generating dataset from: /Users/kanikshasharma/Downloads/labelme-master/examples/semantic_segmentation/Train/20.json
This JSON file (/Users/kanikshasharma/Downloads/labelme-master/examples/semantic_segmentation/Train/20.json) may be incompatible with current labelme. version in file: 4.5.12, current version: 5.1.0
Traceback (most recent call last):
  File "/Users/kanikshasharma/Downloads/labelme-master/examples/semantic_segmentation/labelme2voc.py", line 105, in <module>
    main()
  File "/Users/kanikshasharma/Downloads/labelme-master/examples/semantic_segmentation/labelme2voc.py", line 94, in main
    viz = imgviz.label2rgb(
TypeError: label2rgb() got an unexpected keyword argument 'img'

**Comment by wkentaro** [comment]
Solution: use the latest examples folder.

**Comment by abbasmari** [comment]
Update this file labelme2voc.py by using following method 

`imgviz.label2rgb(label, image=None, alpha=0.5, label_names=None, font_size=30, thresh_suppress=0, colormap=None, loc='rb', font_path=None)`

https://imgviz.readthedocs.io/en/latest/reference/functions/generated/imgviz.label2rgb.html

**Comment by 2018-Summer** [comment]
是imgviz版本太高了，降成imgviz-1.2.0，就可以了

**Comment by sajadalipour** [comment]
change like this:
 if not args.noviz:
            clsv = imgviz.label2rgb(
                cls,
                imgviz.rgb2gray(img),
                label_names=class_names,
                font_size=15,
                loc="rb",
            )
            imgviz.io.imsave(out_clsv_file, clsv)

        # instance label
        labelme.utils.lblsave(out_insp_file, ins)
        np.save(out_ins_file, ins)
        if not args.noviz:
            instance_ids = np.unique(ins)
            instance_names = [str(i) for i in range(max(instance_ids) + 1)]
            insv = imgviz.label2rgb(
                ins,
                imgviz.rgb2gray(img),
                label_names=instance_names,
                font_size=15,
                loc="rb",
            )
