### ISSUE TITLE
Rectangle annotation

### ISSUE THREAD

**Issue by abawchen** [wkentaro/labelme#123]
Thanks for the great tool!

Is it possible or any plan to support rectangle annotation? It would be more efficiency since sometimes we don't need polygon.

I can contribute if it makes sense.

**Comment by abawchen** [comment]
Yeah, I know `labelImg` can do it, but what I ask is that users can choose polygon or rectangle annotation by their own.

Btw, `labelImg` can't review the annotation/labeling result after finishing (i.e. close the app and re-open it)

**Comment by wkentaro** [comment]
> Yeah, I know labelImg can do it, but what I ask is that users can choose polygon or rectangle annotation by their own.

Currently, users can't choose rectangle annotation.
So, what do you ask?

**Comment by abawchen** [comment]
Sorry for the confusion, update my comment:
> but what the feature I want is that users can choose polygon or rectangle annotation by their own.

**Comment by wkentaro** [comment]
Yeah, I think adding this feature is reasonable, since someone may need both polygon and bounding box (though it seems rare).
I think the implementation of save format can be done with `is_bbox` flag for each **shape**.

**Comment by serycjon** [comment]
I wanted to combine labelme and polyrnn++ since it has been released. Made a new issue for that feature - https://github.com/wkentaro/labelme/issues/125
