### ISSUE TITLE
[Windows 10] labelme gui not opening

### ISSUE THREAD

**Issue by innat** [wkentaro/labelme#1233]
### Provide environment information

python : 3.10.9

```
conda create --name=labelme python=3
conda activate labelme
pip install labelme
```

### What OS are you using?

Windows 10

### Describe the Bug

Please see in the taskbar, the white app icon is the the labelme. It just apears like this and no log message in the terminal and no gui.

![image](https://user-images.githubusercontent.com/17668390/216828853-33d20a6a-af90-4e59-83e1-600c3990cbc1.png)

**Comment by innat** [comment]
cc. @wkentaro

**Comment by bxxk2021** [comment]
try this：labelme --reset-config         
that's solve my problem
