### ISSUE TITLE
Suggestion: use qtpy for abstracting the qt implementation

### ISSUE THREAD

**Issue by jbvo** [wkentaro/labelme#127]
From the Spyder project there is the qtpy abstraction layer that lets you write code as if PyQt5 is imported, but run with Qt4 under the hood. This can simplify some parts of the code, taking away some if statements.  Additionally the ambiguous import warnings that Spyder gives when opening the project (*"QListWidget exists in both PyQt4 and PyQt5"*) would be gone also.

**Comment by wkentaro** [comment]
How can it handle `.qrc` file?
https://github.com/wkentaro/labelme/blob/master/labelme/resources.qrc

**Comment by wkentaro** [comment]
https://github.com/wkentaro/labelme/commit/54863e2a914896e60cbdad0e8726260c18f987e2 made the `.qrc` file no longer necessary.

**Comment by wkentaro** [comment]
Do you have some idea what library is better for this?
There is a comparison matrix at mottosso/Qt.py:
https://github.com/mottosso/Qt.py#projects-similar-to-qtpy

**Comment by wkentaro** [comment]
@jbvo Thank you for the suggestion! This is supported via #130 .
