### ISSUE TITLE
labelme gui doesn't show on windows11

### ISSUE THREAD

**Issue by whansk50** [wkentaro/labelme#1278]
### Provide environment information

python 3.7.16 on Anaconda with following Anaconda install manual of this repository

```
Package           Version
----------------- -----------
certifi           2022.12.7
colorama          0.4.6
cycler            0.11.0
fonttools         4.38.0
imgviz            1.7.2
kiwisolver        1.4.4
labelme           5.2.0.post4
matplotlib        3.5.3
natsort           8.3.1
numpy             1.21.6
packaging         23.1
Pillow            9.5.0
pip               22.3.1
pyparsing         3.0.9
PyQt5             5.15.9
PyQt5-Qt5         5.15.2
PyQt5-sip         12.12.1
python-dateutil   2.8.2
PyYAML            6.0
QtPy              2.3.1
setuptools        65.6.3
six               1.16.0
termcolor         2.3.0
typing_extensions 4.5.0
wheel             0.38.4
wincertstore      0.2
```

### What OS are you using?

windows 11

### Describe the Bug

same as #1233 
It appears only on taskbar, but window doesn't pop-up

![image](https://github.com/wkentaro/labelme/assets/60608880/544dd32f-2ea4-48b3-af86-e5294e1ed38b)

**Comment by guptar11** [comment]
I am currently having the same issue on Windows. I downloaded the .exe and I'm not able to see anything besides see LabelMe in the taskbar.

**Comment by karthikziffer** [comment]
I am having the same issue.

**Comment by whansk50** [comment]
@karthikziffer Thanks, it works well
