### ISSUE TITLE
module 'labelme.utils' has no attribute 'label_colormap'

### ISSUE THREAD

**Issue by pravinrav** [wkentaro/labelme#1292]
### Provide environment information

I am trying to convert my .json files containing my labels (semantic segmentation, polygonal bounding box information) to VOC segmentation format for visualizing the segmentation masks over the input pixels of my image. I then get the error:

module 'labelme.utils' has no attribute 'label_colormap'

I am following the example here for VOC segmentation format dataset creation: 
https://github.com/wkentaro/labelme/tree/main/examples/semantic_segmentation

(base) pravin@AdminisatorsMBP SEGMENTATION % 

./labelme2voc.py Images_To_Segment Images_To_Segment_voc5 --labels labels.txt

Creating dataset: Images_To_Segment_voc5
class_names: ('_background_', 'vein')
Saved class_names: Images_To_Segment_voc5/class_names.txt
Traceback (most recent call last):
  File "/Users/pravin/Documents/SEGMENTATION/./labelme2voc.py", line 95, in <module>
    main()
  File "/Users/pravin/Documents/SEGMENTATION/./labelme2voc.py", line 56, in main
    colormap = labelme.utils.label_colormap(255)
AttributeError: module 'labelme.utils' has no attribute 'label_colormap'
(base) pravin@AdminisatorsMBP SEGMENTATION % pwd
/Users/pravin/Documents/SEGMENTATION

Please help. 

I tried:

cd labelme
pip install -e .

But this did not fix the issue. 

### What OS are you using?

Mac OS Ventura 13.2.1

### Describe the Bug

I am trying to convert my .json files containing my labels (semantic segmentation, polygonal bounding box information) to VOC segmentation format for visualizing the segmentation masks over the input pixels of my image. I then get the error:

module 'labelme.utils' has no attribute 'label_colormap'

I am following the example here for VOC segmentation format dataset creation: 
https://github.com/wkentaro/labelme/tree/main/examples/semantic_segmentation

(base) pravin@AdminisatorsMBP SEGMENTATION % 

./labelme2voc.py Images_To_Segment Images_To_Segment_voc5 --labels labels.txt

Creating dataset: Images_To_Segment_voc5
class_names: ('_background_', 'vein')
Saved class_names: Images_To_Segment_voc5/class_names.txt
Traceback (most recent call last):
  File "/Users/pravin/Documents/SEGMENTATION/./labelme2voc.py", line 95, in <module>
    main()
  File "/Users/pravin/Documents/SEGMENTATION/./labelme2voc.py", line 56, in main
    colormap = labelme.utils.label_colormap(255)
AttributeError: module 'labelme.utils' has no attribute 'label_colormap'
(base) pravin@AdminisatorsMBP SEGMENTATION % pwd
/Users/pravin/Documents/SEGMENTATION

Please help. 

I tried:

cd labelme
pip install -e .

But this did not fix the issue.

**Comment by pravinrav** [comment]
@wkentaro Please help. I tried 

cd labelme
pip install -e .

from your earlier reply regarding a labelme.utils not defined issue.

**Comment by wkentaro** [comment]
Probably you need to check the following to see if your installation is correct.

```
python3 -m labelme
python3
> import labelme
> print(labelme)

python3 ./labelme2voc.py
```

**Comment by pravinrav** [comment]
```
Last login: Wed Jun 14 03:03:08 on ttys006
(base) pravin@AdminisatorsMBP ~ % python3 -m labelme
[INFO   ] __init__:get_config:70 - Loading config file from: /Users/pravin/.labelmerc
(base) pravin@AdminisatorsMBP ~ % 
(base) pravin@AdminisatorsMBP ~ % python3
Python 3.10.9 (main, Mar  1 2023, 12:20:14) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import labelme
>>> print(labelme)
<module 'labelme' from '/Users/pravin/labelme/labelme/__init__.py'>
>>> 
KeyboardInterrupt
>>> 
>>> 
KeyboardInterrupt
>>> exit()

```

`(base) pravin@AdminisatorsMBP Documents % cd SEGMENTATION
(base) pravin@AdminisatorsMBP SEGMENTATION % ls
Images_To_Segment			Images_To_Segment_voc_new
Images_To_Segment_Converted_To_Png	labelme2voc.py
Images_To_Segment_voc2			labels.txt
Images_To_Segment_voc5
(base) pravin@AdminisatorsMBP SEGMENTATION % python3 ./labelme2voc.py
usage: labelme2voc.py [-h] --labels LABELS input_dir output_dir
labelme2voc.py: error: the following arguments are required: input_dir, output_dir, --labels
(base) pravin@AdminisatorsMBP SEGMENTATION % python3 ./labelme2voc.py Images_To_Segment Images_To_Segment_voc3_new --labels labels.txt

Creating dataset: Images_To_Segment_voc3_new
class_names: ('_background_', 'vein')
Saved class_names: Images_To_Segment_voc3_new/class_names.txt
Traceback (most recent call last):
  File "/Users/pravin/Documents/SEGMENTATION/./labelme2voc.py", line 95, in <module>
    main()
  File "/Users/pravin/Documents/SEGMENTATION/./labelme2voc.py", line 56, in main
    colormap = labelme.utils.label_colormap(255)
AttributeError: module 'labelme.utils' has no attribute 'label_colormap'
(base) pravin@AdminisatorsMBP SEGMENTATION % 
`

**Comment by wkentaro** [comment]
I found there is no `labelme.utils.label_colormap` in the first place.
<img width="488" alt="image" src="https://github.com/wkentaro/labelme/assets/4310419/bcb954e5-3fcb-4e5f-a9e0-ab10dc3b0695">

Probably you're using old labelm2voc.py.
