### ISSUE TITLE
How to convert 16 color depth label.png to 8-bit color?

### ISSUE THREAD

**Issue by Xiaowo857** [wkentaro/labelme#13]
I would like to know how to change the output label.png of 16-bit color to 8-bit color. I am confused about this. Is there anything like gray=True or something like this?

Anyone helps.... Thanks a lot.

**Comment by wkentaro** [comment]
I'm not sure why you want to do this, but if you'd like to convert `label.png` to mask image, run below:

```python
import numpy as np
import matplotlib.pyplot as plt
import PIL.Image

label_file = 'label.png'
lbl = np.asarray(PIL.Image.open(label_file))
print(np.unique(lbl))
assert lbl.dtype == np.int32

for label_value in np.unique(lbl):
    mask = lbl == label_value
    plt.imshow(mask, gray=True)
    plt.show()
```

See https://github.com/wkentaro/labelme/blob/master/scripts/labelme_json_to_dataset#L33 for the way how `label.png` is created.

**Comment by Xiaowo857** [comment]
Thank you so much. I just need to make a dataset of mask images.
