### ISSUE TITLE
PNG label files in semantic segmentation is black

### ISSUE THREAD

**Issue by RomRoc** [wkentaro/labelme#132]
Hello, I tried to xecute your useful example to convert to VOC-like Dataset using labelme2voc.py
I always get completely black png files in SegmentationClass directory. I checked your samples 2011_000003.png ... files, they are black too (i tested with opencv).
I know they should be almost black, as you commented, but I get it completely black.
Indeed it works perfectly output files in SegmentationClassVisualization.
Do you confirm you get proper png label files?
Thanks

**Comment by wkentaro** [comment]
See here: https://github.com/wkentaro/labelme/tree/master/examples/tutorial#how-to-load-label-png-file

**Comment by wkentaro** [comment]
I have just updated the FAQ: https://github.com/wkentaro/labelme#faq

**Comment by RomRoc** [comment]
Amazing! It works. Thanks a lot.

**Comment by RomRoc** [comment]
You can view png in opencv adding this code to your tutorial sample:

```
img_to_cv = lbl.astype(np.uint8)
cv2.imshow('img_to_cv',img_to_cv)
cv2.waitKey(0)
cv2.destroyAllWindows()
```
To magnify the segmentation elements in png, we can multiply numpy array in visualization:
`lbl = np.asarray(img_pil) * 25`
