### ISSUE TITLE
Add vertex into an existing polygon

### ISSUE THREAD

**Issue by russkel** [wkentaro/labelme#141]
Is there a way to insert a vertex into existing polygons? Sometimes when annotating large objects I create a rough overall and then improve detail in certain areas. I can't seem to be able to do this with labelme?

**Comment by wkentaro** [comment]
Currently, it is not possible. But I think adding this would be great and not so difficult.

**Comment by wkentaro** [comment]
Closed via https://github.com/wkentaro/labelme/pull/172
