### ISSUE TITLE
command line argument could not work

### ISSUE THREAD

**Issue by xikuibin** [wkentaro/labelme#149]
`def get_config(config_from_args=None, config_file=None):`  in labelme/labelme/config/__init__.py do something in wrong order.

The command line arguments is used first
```
    if config_from_args is not None:
        update_dict(config, config_from_args,
                    validate_item=validate_config_item)
```
then covered by the values from '.labelmerc
```
    if os.path.exists(config_file):
        with open(config_file) as f:
            user_config = yaml.load(f) or {}
        update_dict(config, user_config, validate_item=validate_config_item)
```
So all command lines argument do not work.

It updating config by arguments before return, the command line arguments will work.

After reading the code. I think the flow will confuse the user.
If there is a config file '.labelmerc' in the user home, all command arguments will be overided.  It user want to some new argument, the only we is delete the '.labelmerc' manually or edit the '.labelmerc' directly.

Is this the design?

**Comment by wkentaro** [comment]
@xikuibin Thanks for reporting this. Yes, I think you're right, and it is a kind of bug.
I fix this by https://github.com/wkentaro/labelme/pull/150, so could you try that?
