### ISSUE TITLE
Cant remove Group Id after its entered

### ISSUE THREAD

**Issue by ashwinkrypton** [wkentaro/labelme#1500]
### Provide environment information

Python 3.9.15 labelme 5.5.0 

### What OS are you using?

Windows 10

### Describe the Bug

Can't remove Group Id after it has been entered.

For segmentation, I want to remove Group Id to the polygon which has been entered by mistake at the right box which is available, but it won't be reflected in the Polygon Labels list.

This works perfectly fine if I use Labelme 5.4.0.post1

https://github.com/user-attachments/assets/8d306070-38ca-48fa-91b2-39c896cb9e1b

### Expected Behavior

Polygon with no Group Id after editing.

### To Reproduce

Open a jpg image and give Group ID for the polygon and try removing the Group ID.

**Comment by wkentaro** [comment]
Thanks for the report. It's fixed via https://github.com/wkentaro/labelme/pull/1498.

**Comment by ashwinkrypton** [comment]
Thanks for the reply. This issue was fixed in labelme 5.6.0a0 pre release version. Could you please upload a stable release shortly.
