### ISSUE TITLE
Is it possible to support video segmentation annotation?

### ISSUE THREAD

**Issue by yl1991** [wkentaro/labelme#163]
Hi wkentaro,

I was wondering if you will support video segmentation annotations, like in the DAVIS challenge. Basically I think given a sequence of frames,  you can allow the annotators to copy the annotation from the previous frame and to fine-tune a bit in the current frame. 

Best regards,
Yiming

**Comment by wkentaro** [comment]
That would be a great feature! And I would be happy to support it.
Currently, I don't have the plan (or time) to implement it by myself, but pull requests are welcome!

**Comment by wkentaro** [comment]
This would be achieved by https://github.com/wkentaro/labelme/pull/169.
