### ISSUE TITLE
Problems on Windows

### ISSUE THREAD

**Issue by syan1992** [wkentaro/labelme#17]
I use it on Windows. There isn't a file after I click save. I can't find the 'json' file.

**Comment by wkentaro** [comment]
Sorry, I don't have environment to reproduce.

**Comment by syan1992** [comment]
In line 793, I think it might be as follows, without '[0]' in the end: 
filename = dlg.getSaveFileName(
            self, 'Choose File', default_labelfile_name,
            'Label files (*%s)' % LabelFile.suffix)

**Comment by wkentaro** [comment]
@syan1992 Thanks for the report. I released [v2.5.2](https://github.com/wkentaro/labelme/releases/tag/v2.5.2)
