### ISSUE TITLE
Key-point annotation

### ISSUE THREAD

**Issue by Anitkrun** [wkentaro/labelme#176]
I suppose key-point annotation is not a current feature? I need to annotate the skeletal points for a human body. I would really appreciate if anyone can point me in the right direction. Perhaps I can write something for that?

Would this be a feature to be added in future?

**Comment by wkentaro** [comment]
> I suppose key-point annotation is not a current feature? 

Although it seems unoptimized annotation, I think you can do it by annotating each keypoint like `person-1-reye`, `person-1-rhand`, `person-2-reye`...

**Comment by wkentaro** [comment]
https://github.com/wkentaro/labelme/pull/188 adds this feature.
![](https://user-images.githubusercontent.com/4310419/42725240-7c721a24-87bb-11e8-9f02-6e6a2e4ccd5d.jpg)
