### ISSUE TITLE
After I run labelme2voc.py，there is no label pic(png format) in data_dataset_voc/SegmentationClass directory

### ISSUE THREAD

**Issue by hhue** [wkentaro/labelme#178]
hi,the question is following:
After I run labelme2voc.py，there is no label pic(png format) in data_dataset_voc/SegmentationClass directory,there are some other file(npy format),but I hope the label png image in this dir

thanks you!

**Comment by RomRoc** [comment]
In the lastest commit #173 they changed output from png to npy, to consider -1 value (ignore), before it was png file as output, for my opinion png was better to use for training models in machine learning.

**Comment by wkentaro** [comment]
https://github.com/wkentaro/labelme/pull/182 will make the script to output the PNG file also.
In PNG file, the -1 value (ignore label) will be converted to 255 as in the VOC dataset.
