### ISSUE TITLE
Capability to draw lines

### ISSUE THREAD

**Issue by PREM1980** [wkentaro/labelme#180]
Is there a feature to draw lines using this tool?
Im planning to add that feature. Will it be ok if I submit a PR requests for that feature.

**Comment by PREM1980** [comment]
Ok, I will submit a PR with the updates to draw a line.

The toolbar to 'draw polygon' will be replaced by 'draw shapes'. Will that be ok?

**Comment by wkentaro** [comment]
I think ‘draw line’ tool can be added aside from ‘draw shape’. like ‘draw rectangle’

**Comment by wkentaro** [comment]
https://github.com/wkentaro/labelme/pull/187 adds this feature.
