### ISSUE TITLE
Snap to point sensitivity

### ISSUE THREAD

**Issue by eljirg** [wkentaro/labelme#184]
Hi, I am trying to make annotation of many small patches inside a picture. However it was very frustrating because it kept snapping to the starting/end point if i get to close to it.

Is there anyway that i could reduce the sensitivity of it?

Thanks

**Comment by wkentaro** [comment]
It is defined below:
https://github.com/wkentaro/labelme/blob/427e3350fd7c4e185e4a8b6c48a4d1cd0e057334/labelme/canvas.py#L36

**Comment by wkentaro** [comment]
https://github.com/wkentaro/labelme/pull/186 will add this feature like:

```
labelme --epsilon 5.0 (11.0 default)
```

**Comment by eljirg** [comment]
Thank you very much , you're a life saver!

I tried epsilon = 1 at 500% zoom but it's quite hard to close the polygon then, 2 is the right number for very close stitching.

**Comment by wkentaro** [comment]
👍
