### ISSUE TITLE
FileType Support?

### ISSUE THREAD

**Issue by XiaotianM** [wkentaro/labelme#19]
Hello, I have set up the Labelme. However, it seems to only support the filetype like *.b'bmp'... 
So I don‘t know how to use it. Besides, when I use your example codes, it has gone wrong. Problem presented as follows: "Error saving label data, a bytes-like object is required, not  'str' "

Can you tell me how to solve this problem? Thank you

**Comment by wkentaro** [comment]
Please specify version of labelme and pyqt.

**Comment by XiaotianM** [comment]
Win10 platform, Anaconda, and I install labelme by conda create --name=labelme python=3.5, and others are the same as your guidance

**Comment by wkentaro** [comment]
```
conda list pyqt | grep pyqt
```

**Comment by XiaotianM** [comment]
pyqt 5.6.0 py35_0
I think pyqt is OK, 
the labelme GUI is ok, but I can not load the image.

![labelme](https://user-images.githubusercontent.com/29722350/29807475-c341c2ec-8cc6-11e7-8802-8bf9dace31b8.png)

**Comment by snowballball** [comment]
I can not load my image, too.

**Comment by wkentaro** [comment]
Confirmed. It is caused by the difference of string betwee python2 and 3.
Will be fixed via #20.
