### ISSUE TITLE
How can i change the code to narrow the cursor' circle.

### ISSUE THREAD

**Issue by chenyuyi94** [wkentaro/labelme#192]
Thank you for sharing this tool.when i was labeled the small object,the cursor will catch the first  point. so, how can can change the code to close the points by ourselves.

**Comment by chenyuyi94** [comment]
Thank you  for your reply，Thank you very much 。

**Comment by wkentaro** [comment]
👍

**Comment by chenyuyi94** [comment]
I am sorry to interrupt you again.In practice ,I found that use the key (S) instead of (ctrl+S) will be more effective.But when i change the(save :S)  labelme-master/labelme/config/default_config.yaml  ,it dose not work.(I have uninstalled the labelme and reinstalled  it)

发自我的 iPhone

**Comment by wkentaro** [comment]
Probably you need to change `~/.labelmerc`.
