### ISSUE TITLE
file numbering - Filter filenames from file list

### ISSUE THREAD

**Issue by tabasano** [wkentaro/labelme#193]
hi.
I think file numbering and jumping by it are useful and dispensable when coping with too many images.
so I added it. how about it?

**Comment by wkentaro** [comment]
You mean search by filename from file list?
I think that would be useful.

**Comment by tabasano** [comment]
yes, numbering by file list.
now it doesn't seem to be easy to merge two master, but I have sent a pull request, anyway. 
(and sorry for my typo "dispensable" to *indispensable* ...)

**Comment by wkentaro** [comment]
Is https://github.com/wkentaro/labelme/pull/202 fine for you?

**Comment by tabasano** [comment]
good job.thanks.
but in some cases it may not work when e.g. 
"i can't remember the file... what is that file name... number is about 2000 or 2500 of 10000?"
and when i can't have a right to change complicated names to more human-readable ones by some office rules etc.

**Comment by passion3394** [comment]
how to disable search filename box ?  @wkentaro
