### ISSUE TITLE
module 'labelme.utils' has no attribute 'lblsave'?

### ISSUE THREAD

**Issue by weixia-cs** [wkentaro/labelme#194]
thanks for your nice tools.
i want convert my data to VOC-like Dataset, but something wrong.
 `AttributeError: module 'labelme.utils' has no attribute 'lblsave'` ，can your help me？

**Comment by wkentaro** [comment]
```
cd labelme
pip install -e .
```

**Comment by weixia-cs** [comment]
xiexie , thank you
