### ISSUE TITLE
cant see marked area

### ISSUE THREAD

**Issue by wxianfeng** [wkentaro/labelme#199]
when i marked polygon, and save success

when i choose next, then back to previous marked one, cant see marked area

is this right ? 

if not right, how to do review marked file, thx.

**Comment by wkentaro** [comment]
I don't think it is right.
Did you try the example and encounter this problem? https://github.com/wkentaro/labelme/tree/master/examples/semantic_segmentation

**Comment by wkentaro** [comment]
Please provide your environment, version of labelme, and some images to reproduce your issue.

**Comment by wxianfeng** [comment]
@wkentaro 
macOS 10.12.6
labelme 3.2.0

**Comment by wkentaro** [comment]
The example works in my env..

macOS 10.13.6
labelme 3.2.0
PyQt5 (installed by brew)

**Comment by wxianfeng** [comment]
@wkentaro 
emmmm.... save location,  any location is ok? 

can u step by step show me the tip ?

**Comment by wxianfeng** [comment]
@wkentaro 

i found problem and fixed, i save json not in image folder, save to another path.
