### ISSUE TITLE
can't open the labelme.exe

### ISSUE THREAD

**Issue by jesen8** [wkentaro/labelme#204]
### this is the dir below

![default](https://user-images.githubusercontent.com/33971685/43123426-b6740b36-8f56-11e8-838c-736cf6e9651b.png)

### and the dir of labelme.exe

![default](https://user-images.githubusercontent.com/33971685/43123442-c07d9106-8f56-11e8-9c33-ac4431e8c9e1.png)

### but when i run this exe ,the error happend...

![default](https://user-images.githubusercontent.com/33971685/43123484-eab2e1d8-8f56-11e8-984c-90178a3df510.png)

**Comment by jesen8** [comment]
yes，i can run labelme in anaconda ,but i want to tun it by exe....ok,thanks!

**Comment by wkentaro** [comment]
I reopen this because maybe someone will find the way to fix.

**Comment by amin-git** [comment]
I'm download  last release (v3.3.6) and run 

> python setup.py install

now run successfully on anaconda terminal but after compile with pyinstaller and execute lableme.exe get this error :

![image](https://user-images.githubusercontent.com/19725851/44903487-ef975b00-ad21-11e8-82bb-3fa03b18dab9.png)

platform : windows 10 64bit
python : Python 3.6.4 and pyqt 5.6.0

tnx

**Comment by carsonzhu** [comment]
@Amin-Tgz You can try below solution, it worked fine for me:
- Copy platform directory to directory of your executable. You'll find the platform directory at a location like c:\Users\<username>\envs\<environmentname>\Library\plugins\platforms

**Comment by Amin-Tgz** [comment]
> 
>     *  location like c:\Users<username>\envs<environmentname>\Library\plugins\platforms


![qt](https://user-images.githubusercontent.com/19725851/45372451-4b0af800-b602-11e8-872d-5756e1372b7c.PNG)


@carsonzhu 
I understood the meaning of the error by your help 👍 
but i cant tackle this problem! :(

**Comment by carsonzhu** [comment]
@Amin-Tgz When I used python 3.6.6 in Windows 10 64bit, I met the same issue as you. Copy platform directory to directory of the executable can solve the problem.
Then I tried python 3.5.6, I found it worked well. You can have a try.
![test1_labelme](https://user-images.githubusercontent.com/13717755/45399718-ba70fe00-b67b-11e8-9e03-5e11a922f0b7.PNG)
![test2_labelme](https://user-images.githubusercontent.com/13717755/45399730-c3fa6600-b67b-11e8-8169-8b78ed3dfdb0.PNG)
Good luck!

**Comment by Amin-Tgz** [comment]
Thanks,
I copied [platform] folder from my [conda env] to [labelme-3.3.6\dist] directory and problem solved!

**Comment by soon-will** [comment]
@jesen8 @Amin-Tgz @carsonzhu Thanks for your effort.
But how do you get the `labelme.exe`?I can only run labelme in anaconda.

**Comment by fei4xu** [comment]
```sh
pip install labelme
```
then in `C:\Users\xxxxxxx\AppData\Roaming\Python\Python37\Scripts` you will find **labelme.exe**

then double click the **labelme.exe** and here we go.
