### ISSUE TITLE
why fail to build the standalone executable on Windows 10

### ISSUE THREAD

**Issue by Dan-Huang-sv** [wkentaro/labelme#205]
Follow: How to build standalone executable
I got a labelme.exe in path:   labelme-3.3.2\dist
but when I run it，i got an error:
![image](https://user-images.githubusercontent.com/38381456/43246410-2c4dd5d8-90e4-11e8-83ee-ab5ab5d9e3f9.png)

In  file: labelme-3.3.2\build\labelme\warnlabelme.txt
I got some messages:

> missing module named 'multiprocessing.forking' - imported by c:\anaconda3\envs\labelme\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py
> missing module named multiprocessing.get_context - imported by multiprocessing, multiprocessing.pool, multiprocessing.managers, multiprocessing.sharedctypes
> missing module named multiprocessing.TimeoutError - imported by multiprocessing, multiprocessing.pool
> missing module named multiprocessing.BufferTooShort - imported by multiprocessing, multiprocessing.connection
> missing module named multiprocessing.AuthenticationError - imported by multiprocessing, multiprocessing.connection
> missing module named multiprocessing.set_start_method - imported by multiprocessing, multiprocessing.spawn
> missing module named multiprocessing.get_start_method - imported by multiprocessing, multiprocessing.spawn
> missing module named multiprocessing.SimpleQueue - imported by multiprocessing, concurrent.futures.process
> missing module named multiprocessing.Manager - imported by multiprocessing, nose.plugins.plugintest
> missing module named multiprocessing.current_process - imported by multiprocessing, nose.plugins.plugintest
> missing module named 'win32com.gen_py' - imported by win32com, c:\anaconda3\envs\labelme\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_win32comgenpy.py
> missing module named pyimod03_importers - imported by PyInstaller.loader.pyimod02_archive, c:\anaconda3\envs\labelme\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py
> missing module named StringIO - imported by numpy.lib.utils, numpy.testing._private.utils, PyInstaller.lib.modulegraph._compat, PyInstaller.lib.modulegraph.zipio, numpy.lib.format, pkg_resources._vendor.six
> missing module named 'pkg_resources.extern.pyparsing' - imported by pkg_resources._vendor.packaging.markers, pkg_resources._vendor.packaging.requirements
> missing module named 'com.sun' - imported by pkg_resources._vendor.appdirs
> missing module named com - imported by pkg_resources._vendor.appdirs

and so on...
Did I made some mistakes?

**Comment by wkentaro** [comment]
Same issue as https://github.com/wkentaro/labelme/issues/204
