### ISSUE TITLE
occasionally closed frames on the right

### ISSUE THREAD

**Issue by oukohou** [wkentaro/labelme#214]
How could I reopen it?
regards.

**Comment by wkentaro** [comment]
Could you explain in more detail? I don't understand the issue.

**Comment by oukohou** [comment]
sure.When I annotate images, I occasionally  closed the frames on the right, which is label list frame, Polygen_labels,and file_list frame, and couldn't find a way to reopen it, an I clear?

**Comment by oukohou** [comment]
ok, thanks.
