### ISSUE TITLE
Wrong color matched

### ISSUE THREAD

**Issue by SadAngelF** [wkentaro/labelme#216]
we use latest labelme in ubuntu16.04, win10 or MACos. We set the color in labelme but get wrong color in label.png. For example, in labelme
![image](https://user-images.githubusercontent.com/30397250/44070700-f8d4c440-9fb7-11e8-8c5d-7bd52c28d44c.png)
However, in the label.png
![image](https://user-images.githubusercontent.com/30397250/44070737-2ba117d4-9fb8-11e8-98c3-bd6ea6a84e8c.png)

**Comment by SadAngelF** [comment]
it becomes green from yellow

**Comment by lzh19961031** [comment]
@SadAngelF Same question.Have you solve the problem?

**Comment by wkentaro** [comment]
Currently, the visualization script creates color based on its own algorithm ignoring the label color set in the labelme.
If you'd like to make the same color, you need to create your own script.

However, in my opinion, changing color on GUI is not so useful, and it is better if the color is automatically changed according to the label name.
So now I'm thinking to remove the feature to change the label color.

**Comment by Iipython** [comment]
@lzh19961031 the author has told us answer.
I
<img width="651" alt="image" src="https://user-images.githubusercontent.com/32443088/44101250-9285a35a-a019-11e8-8268-439c4dc1954d.png">

the color of label can't be controlled,but labels which labeled by the same name in two pictures have the same color.For semantic segmentation,same objects have same color is enough.

**Comment by Iipython** [comment]
@wkentaro  Thank you very much~   
and thank your contribution again
we have method to solve the problem
the user coming up with this question is my teammate,now we have work it out ~

little advice
I think even though controlling the color is not necessary,it's useful for researchers in semantic segmentation.when writing paper, we hope the color is normal(sky is bule,tree is green.....)
just a little advice ~

**Comment by wkentaro** [comment]
> we hope the color is normal(sky is bule,tree is green.....)

You can change the colormap in the visualization functions below:

https://github.com/wkentaro/labelme/blob/a16b5f4914c1eb1987c4cab300711358655cdeac/labelme/utils/draw.py#L65-L66

https://github.com/wkentaro/labelme/blob/a16b5f4914c1eb1987c4cab300711358655cdeac/labelme/utils/draw.py#L34-L35

For example,

```python
# you change the labelme/utils/draw.py to add colormap arg to label2rgb
def label2rgb(lbl, img=None, n_labels=None, alpha=0.5, thresh_suppress=0, colormap=None):
    ...

label_names = ['bg', 'sky', 'tree']
colormap = np.array([(0, 0, 0), (0, 0, 1), (0, 1, 0)]])  # black, blue, green
viz = draw_label(label, label_names=label_names, colormap=colormap)
plt.imshow(viz)
plt.show()
```

**Comment by wkentaro** [comment]
I created an example here: https://github.com/wkentaro/labelme/pull/217#issue-208429102
with the changes needed to apply to draw.py.
