### ISSUE TITLE
BoundingBox support

### ISSUE THREAD

**Issue by jinfagang** [wkentaro/labelme#219]
Does labelme can consider support drag a bounding box feature? using polygons to draw rectangle is not such convenient

**Comment by wkentaro** [comment]
Yes, see the example: https://github.com/wkentaro/labelme/tree/master/examples/bbox_detection#bounding-box-detection-example

**Comment by jinfagang** [comment]
@wkentaro Thanks u wk. But where is the creat reactrangle button goes? I just saw create polygon I am just installed the master branch codes. Is there any except settings to enable this?

**Comment by wkentaro** [comment]
You can change the mode on

1. 'View' menu on the top.
1. Right click on canvas.

![screenshot from 2018-08-15 16-03-04](https://user-images.githubusercontent.com/4310419/44135631-dfc34812-a0a4-11e8-8abb-412bd7c9f842.png)
![screenshot from 2018-08-15 16-03-31](https://user-images.githubusercontent.com/4310419/44135632-dfe5acb8-a0a4-11e8-9527-58fe42d4d22a.png)

**Comment by joshgavinhong** [comment]
Thank you ! Silly me didn't see it...
