### ISSUE TITLE
how does it work?

### ISSUE THREAD

**Issue by SiyuChen1** [wkentaro/labelme#222]
When the `createMode == 'polygon'`,if I click the left button of mouse twice,the current point will be thrown away,and a closed polygon will be formed. I wanted to know how does it works? Which function in the `canvas.py` is in charge of this ?

**Comment by wkentaro** [comment]
You don't need to click twice to add a point to the polygon.

**Comment by wkentaro** [comment]
To save a file, you need to run below function in `app.py`:

https://github.com/wkentaro/labelme/blob/fe1dadbe5db7b698869ed14eb3eb9b332bb68059/labelme/app.py#L783-L828

**Comment by SiyuChen1** [comment]
Thanks~

**Comment by wkentaro** [comment]
:+1:
