### ISSUE TITLE
Tool to re-name labels 

### ISSUE THREAD

**Issue by amolchanov86** [wkentaro/labelme#224]
Hi, it would be great to have a tool for label renaming.
It is useful when one extends the class set and suddenly some of the names do not reflect the new hierarchy properly.

**Comment by wkentaro** [comment]
Yeah. Pull requests are welcome.

**Comment by kaolin** [comment]
What do you envision for this use case? Just rename all the labels in one image to another, or rename all the labels across all images to another, or ... a separate workflow that involves "check label X and choose yes-no if it should be renamed to label Y"? (the former ones could just be a "jq" script).

**Comment by wkentaro** [comment]
> rename all the labels across all images to another

like below.
```python
# labelme_rename_label

parser.add_argument('json_dir')  # like json_files/1.json, 2.json 3.json...
parser.add_argument('--rename', help='"src" "dst"')
args = parser.parse_args()

for json_file in args.json_files:
    ...
```
