### ISSUE TITLE
how to convert a folder including json files to a folder including label pngs

### ISSUE THREAD

**Issue by tengshaofeng** [wkentaro/labelme#225]
hi, @wkentaro ,
you really did a great job. 
when I uselabelme_json_to_dataset, it can convert one json file to one label png.
but not worked for data dir, should I write a python script?

**Comment by wkentaro** [comment]
you may want to know
https://github.com/wkentaro/labelme/blob/master/examples/semantic_segmentation/labelme2voc.py

**Comment by tengshaofeng** [comment]
@wkentaro , thanks ,it is a good idea.
