### ISSUE TITLE
Snap to adjacent polygon edge/vertex

### ISSUE THREAD

**Issue by platypython** [wkentaro/labelme#228]
Where would I go to add some functionality to enable adjacent shapes to share a common edge?

i.e. I draw a rectangle. I draw a second rectangle that shares one common edge. I'd like the vertices to snap on to one another so they're not just _close_ but they exactly share the edge.

Happy to help if one could point me in the right direction.

**Comment by wkentaro** [comment]
Maybe this can be possible with below pipeline:
- Select vertex
- Right click
- Select share start point (Shape class has parent Shape)
- Annotate
- Edit or Move causes change for Shapes with refering parent and child.
