### ISSUE TITLE
how to annotate lanes on the road image?

### ISSUE THREAD

**Issue by passion3394** [wkentaro/labelme#231]
Thanks for your great work:)
But I think the tool can not label the lanes on the road.

I want to use the tool to annotate the lanes on the road. Such as this image:

![0](https://user-images.githubusercontent.com/14256482/46912325-dc281280-cfa4-11e8-873a-3840cd2a539d.jpg)

I want to label the image so that every lane is a single line, and every line contains many points.

I have tried line mode and point mode, but I think the two modes cannot satisfy my requirement.

Hope to get your help, thanks very much.

**Comment by wkentaro** [comment]
Sorry, I'm not sure what you want.
I suppose that we can annotate the lane with the polygonal annotation tool.

**Comment by passion3394** [comment]
<img width="1199" alt="screen shot 2018-10-15 at 1 44 52 pm" src="https://user-images.githubusercontent.com/14256482/46932075-92145f00-d080-11e8-8d09-2162070ae57c.png">
As the above picture shows(I create a lot of points with your tool), there are two set of points on the two lanes, I want each set of points on a lane make a class, but the Polygon Labels tab shows 15(here I want two set of points) and the Label List tab only shows one label(here I want two classes).
Thanks for you reply, if anything is not clear, please tell me.

**Comment by wkentaro** [comment]
Is this not what you want?

```
labelme 46912325-dc281280-cfa4-11e8-873a-3840cd2a539d.jpg --labels lane --validatelabel instance
```

**Comment by passion3394** [comment]
@wkentaro Thanks. your labeling result is very near my requirement ! Is it possible to replace the rectangle with a list of points?

**Comment by passion3394** [comment]
@wkentaro I think I have understand your method, I can use the points to replace the rectangles, and after every point assigned a class, I will gather all the points belong to each line after labeling. Is that right?

**Comment by wkentaro** [comment]
Yeah, that's exactly what I mean.

**Comment by passion3394** [comment]
@wkentaro Yes, the question is resolved, thanks very much. I will close this issue.

**Comment by codeurient** [comment]
> Is this not what you want?
> 
> ```
> labelme 46912325-dc281280-cfa4-11e8-873a-3840cd2a539d.jpg --labels lane --validatelabel instance
> ```
> 
> <img alt="screen shot 2018-10-16 at 11 15 26" width="1680" src="https://user-images.githubusercontent.com/4310419/47009621-df520880-d134-11e8-9349-b7e3e2b11275.png">

I don't have the button `create polygon` (((((
