### ISSUE TITLE
questions about the option and some operations

### ISSUE THREAD

**Issue by passion3394** [wkentaro/labelme#233]
`parser.add_argument(
        '--flags',
        help='comma separated list of flags OR file containing flags',
        default=argparse.SUPPRESS,
    )
    parser.add_argument(
        '--labels',
        help='comma separated list of labels OR file containing labels',
        default=argparse.SUPPRESS,
    )
    parser.add_argument(
        '--validatelabel',
        dest='validate_label',
        choices=['exact', 'instance'],
        help='label validation types',
        default=argparse.SUPPRESS,
    )`

Question 1:
I don't understand the meaning of the  '--flags' and  '--validatelabel' options, is there any doc explaining them?

Question 2:
I use the labelme tool on Mac. But I find it is not very easy to delete points which I have labeled, the situation applys to other shapes(except the rectangle). Is it easy to add the delete function?

**Comment by wkentaro** [comment]
> Question 1:
I don't understand the meaning of the '--flags' and '--validatelabel' options, is there any doc explaining them?

--flags is for image-level annotation shown in 

![image](https://user-images.githubusercontent.com/4310419/47410007-57838400-d75c-11e8-8c0f-1a7b62a4cb21.png)

--validatelabel is to control validation of labels while annotation, in exact, the label must be included in the label list, and in instance, the label matches patterns like 'cat', 'cat-1' and 'cat-2' for example.

> Question 2:
I use the labelme tool on Mac. But I find it is not very easy to delete points which I have labeled, the situation applys to other shapes(except the rectangle). Is it easy to add the delete function?

It is not supported. It is something similar to adding a vertex to a polygon, so you may refer to this: https://github.com/wkentaro/labelme/pull/172.

**Comment by passion3394** [comment]
@wkentaro thanks!
