### ISSUE TITLE
How can i generate a png file without label on it

### ISSUE THREAD

**Issue by NarcissusInMirror** [wkentaro/labelme#235]
i found a code on the Internet and i can generate a png file from the annotated json file, but what confused me is that the generated file has a label on it, which i don't want, how can i wipe it away?
thanks a lot! 
![label_viz](https://user-images.githubusercontent.com/28808216/47604143-f7c0fd80-da27-11e8-8ca0-932d3cac8a1f.png)

**Comment by NarcissusInMirror** [comment]
i didn't install labelme on my Mac, for the job of annotation has been done by my teammates, i simply move the labelme package into anaconda site package directory and import it when using.

**Comment by NarcissusInMirror** [comment]
This is the code i use

```
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('json_file')
    args = parser.parse_args()
 
    json_file = args.json_file
 

    out_dir = "/Users/qiushuhao/Desktop/result"
    data = json.load(open(json_file))
 
    img = utils.image.img_b64_to_arr(data['imageData'])
    lbl, lbl_names = utils.labelme_shapes_to_label(img.shape, data['shapes'])
    lbl_viz = utils.draw_label(lbl, img, lbl_names)
 
    PIL.Image.fromarray(img).save(osp.join(out_dir, 'img.png'))
    PIL.Image.fromarray(lbl).save(osp.join(out_dir, 'label.png'))
    PIL.Image.fromarray(lbl_viz).save(osp.join(out_dir, 'label_viz.png'))
 
    info = dict(label_names=lbl_names)

    with open(osp.join(out_dir, 'info.yaml'), 'w') as f:
        #yaml.safe_dump(info, f, default_flow_style=False)
 
    print('wrote data to %s' % out_dir)
 ```

**Comment by wkentaro** [comment]
Do you wanna to remove `_background_` label?
If so, maybe you're missing what label image is and you need to see it first.

**Comment by wkentaro** [comment]
Ah, ok. I found what you are missing.
Refer to below links
- https://github.com/wkentaro/labelme/tree/master/examples/tutorial#convert-to-dataset
- https://github.com/wkentaro/labelme/tree/master/examples/semantic_segmentation#convert-to-voc-like-dataset

**Comment by NarcissusInMirror** [comment]
all right, i asked for my teammate just now, and found that i do had a wrong concept about label image before, thanks a lot!
