### ISSUE TITLE
Annotations with holes?

### ISSUE THREAD

**Issue by Affonso-Gui** [wkentaro/labelme#245]
Is it possible to make annotations of shapes with holes on it? e.g. donuts

**Comment by wkentaro** [comment]
Please do like following.
![screenshot from 2018-11-07 12-15-00](https://user-images.githubusercontent.com/4310419/48131115-d9100180-e286-11e8-8d05-97076dc198b4.png)

**Comment by Affonso-Gui** [comment]
Thanks!

**Comment by julienguegan** [comment]
Hello, is it the only way ? It is kind of complicated when we want to labellize more complicated and larger shapes (like trees, eyeglasses, clouds ...)

**Comment by wkentaro** [comment]
Another way of doing this is by using "group_id".
The below example contains two polygons that are annotated with group id 0.

<img width="1680" alt="Screen Shot 2020-09-29 at 13 19 50" src="https://user-images.githubusercontent.com/4310419/94557492-8c58b980-0256-11eb-9e0f-32bed49523d0.png">

**Comment by julienguegan** [comment]
To be sure to understand, the idea you propose here is to have 2 polygons one next to other ? 

There is not the possibility to have like a pseudo-label "background" that is not really a class ?

**Comment by wkentaro** [comment]
> To be sure to understand, the idea you propose here is to have 2 polygons one next to other ?

Yeah.

> There is not the possibility to have like a pseudo-label "background" that is not really a class ?

You can create a class like that as in the examples below, but you need to modify labelme2voc.py and labelme2coco.py to make a hole with the background annotation.

https://github.com/wkentaro/labelme/blob/6ca4f83bc3f58a835c1366883045bbc56e62b513/examples/instance_segmentation/labels.txt#L1-L2

**Comment by Affonso-Gui** [comment]
Am sharing my way around this problem just for the record.

Although labelme is an excellent tool to make quick annotations, I thought it was more comfortable to use standard image manipulation software when it is needed to have higher precision labeling of more complex shapes. (Do note that higher precision labeling do not necessarily lead to better learning results).

So what I did was to create an svg annotation file in GIMP, and then use a quick conversion script to generate a labelme compatible json file from that (https://github.com/Affonso-Gui/svglabel). 

In a quick example below, you could just use the color selection tool to select the leaves in like 2 seconds, and then use the conversion script to generate all of the required zero-area connection lines. Do be careful with the number of additional segments you pass to the `-s` option, though, since you could easily end up with a json file with so many points that it would instantly crash when opened with labelme.

![tree_select](https://user-images.githubusercontent.com/20625381/94661688-5bee4980-0342-11eb-899b-2434b4525c09.jpg)
![tree_labelme](https://user-images.githubusercontent.com/20625381/94661709-60b2fd80-0342-11eb-99e4-fa3e9d49ac9e.jpg)

**Comment by julienguegan** [comment]
Sound pretty cool, and I guess it work with other tool as the magic wand. 

Just to be sure, all the red line that link one point on the top to all the others does not matter when you creating your mask then ?

**Comment by Affonso-Gui** [comment]
Correct! If everything is ok with the algorithm (which I was fixing yesterday) all of the connection lines are just going back and forth from the same two points, so they bind no area and therefore do not affect the mask.

You can verify this by re-converting the generated json back into svg and loading it in gimp again: below you can see how all of the paths remain there, but they don't show up once you make a selection and, say, fill it with black.

![select_1](https://user-images.githubusercontent.com/20625381/94791791-1a799f00-0413-11eb-991b-43f53291a71c.jpg)
![select_2](https://user-images.githubusercontent.com/20625381/94791816-1e0d2600-0413-11eb-9ffe-fc98737b39d0.jpg)

That being said, I am probably the only one who has ever used this tool, so if you happen to find some problems please post an issue or create a PR at the repo!
