### ISSUE TITLE
Changing instance color when use json_to_dataset

### ISSUE THREAD

**Issue by yyang294** [wkentaro/labelme#246]
Hi Wkentaro,

Really great work first of all. I am wondering if I could force the color of instance stay the same. For example, I have 2 images (Img1, Img2) and 3 classes (Cls1, Cls2, Cls3) to annotate. In Img1, only Cls2 and Cls 3 appear and in Img2 only Cls1 and Cls3 appear. It seems currently when I use json_to_dataset, the color of each class is not consistent between Img1 and Img2. I am wondering if there is a way to directly import the desired color for each instance? Thank you very much!

**Comment by wkentaro** [comment]
Please refer to https://github.com/wkentaro/labelme/issues/234
