### ISSUE TITLE
imagesize in json

### ISSUE THREAD

**Issue by oostap1** [wkentaro/labelme#249]
Hi
Thanks for great tool for annotation. 

Currently json file does not fully self contain for segmentation mask creation when image is not stored in json itself. And storing image in json makes github complain about big files and requires decompress png each time to just get image size. 

Would be great to have one more parameter in output json: imageSize.
I've submitted Pull Request for that.

**Comment by wkentaro** [comment]
https://github.com/wkentaro/labelme/pull/250 will fix this.
I think that would be better with imageHeight and imageWidth.
