### ISSUE TITLE
Unable to save: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by patrickcgray** [wkentaro/labelme#25]
I can't actually save a file on mac OS running python 3.6.2. Every time I try to save I get:

`AttributeError: 'bytes' object has no attribute 'encode'`

**Comment by jjdblast** [comment]
I also meet this problem, the error message exactly the same with patrick's  

my environment :

Ubuntu 16.04, Anaconda 4, Python 2.7

**Comment by landiaokafeiyan** [comment]
Hi，Thanks for sharing the code，I find a BUG that when I use the tool，if i sliding mouse，the tool will exit。what i have to do if i want to run the code and fix the bug？

**Comment by ibadami** [comment]
@wkentaro @jjdblast  @patrickcgray 
So I found two problems with the encoding bug.
in labelFile.py in `def save(self, filename, shapes, imagePath, imageData,
            lineColor=None, fillColor=None):`
1.`with open(filename, 'wb') as f:`  should be `with open(filename, 'w') as f:` because not all the data we would like to save in json is in binary.
2. ` imageData = b64encode(imageData.encode('utf-8'))` should be  `imageData = b64encode(imageData).decode('ascii')` this will convert the binary image to string.

As a final step one must correct the load function as well.
this will save the json file with ascii image data in base64.

**Comment by wkentaro** [comment]
I tested in below environment, and they all works. Could you please specify the version again?

with labelme==2.6.2

- python2.7 + pyqt5
- python2.7 + pyqt4
- python3.5 + pyqt5
- python3.5 + pyqt4

**Comment by ibadami** [comment]
Could it be that this problem is platform specific? I am also running on mac OS and I faced the same problem.
Did you test it on mac?

**Comment by landiaokafeiyan** [comment]
@Kentaro Wad    i can install labelme  on windows and ubuntu sucessfully. the problem is that when i use labeme to label the image, i will exit the GUI when i slide the mouse pulley.

**Comment by wkentaro** [comment]
@landiaokafeiyan Your problem is different from the topic in this issue, right? If so, could you please open a new issue?

**Comment by landiaokafeiyan** [comment]
@ibadami  i can install labelme on windows and ubuntu sucessfully. i have not test it on Mac

**Comment by landiaokafeiyan** [comment]
@wkentaro  ok sure could you please fix the bug?

**Comment by wkentaro** [comment]
@landiaokafeiyan I think so.

**Comment by landiaokafeiyan** [comment]
@wkentaro many thanks

**Comment by wkentaro** [comment]
@ibadami I also tested on mac also, and it works. (fyi I use conda)

**Comment by ibadami** [comment]
I too used conda.
This is very surprising.

**Comment by ibadami** [comment]
What I do not understand is. When you read the image data using read function in app.py it is read as a binary data. Then how can you encode that binary data in utf-8 during saving. When I googled the error message, I found that this error occurs because the binary data cannot be further encoded.

**Comment by astr93** [comment]
+1, same problem

**Comment by peysabo** [comment]
I used the following and solved the problem:

$  pip3 install SIP
$ pip3 install pyqt5
$ pip install labelme ( it did not worked with pip3)

**Comment by wangchenghan** [comment]
Thanks for sharing this code.
I also meet this problem on windows with python3.6 and pyqt5

**Comment by l02i08u** [comment]
I tested in this way on windows, and it worked.
In labelFile.py
`def save(...):    with open(filename, 'wb') as f:    if six.Py3:    imagedata=b64encode(imageData.decode('utf-8')` should be `with open(filename, 'w') as f:    if six.Py3:    imagedata=str(b64encode(imageData), 'utf-8')`

**Comment by hgs1217** [comment]
@l02i08u 's way works on my windows with Python 3.6. Thanks for his way.

**Comment by y-wan** [comment]
Thanks, @l02i08u 's way works for me as well while saving a file (Python 3.6 on Windows). However, when opening a json file saved in this way, the following code in labelFile.py should also be modified, otherwise similar encoding issues would occur:
`with open(filename, 'rb') as f:` -> `with open(filename, 'r') as f:`
`imageData = b64decode(data['imageData']).decode('utf-8')` -> `imageData = b64decode(bytes(data['imageData'], 'utf-8'))`

**Comment by MischaSchwendy** [comment]
Thank you @l02i08u + @y-wan !  These changes solved the problem for me, too! (also Python 3.6 on Windows)

**Comment by blakeliu** [comment]
@y-wan 
My os is windows 10 ,and anaconda 3 with python 3.5.4
`
def load(self, filename):
        try:
            with open(filename, 'r') as f:
                data = json.load(f)
                imagePath = data['imagePath']

                if six.PY3:
                    imageData = b64decode(bytes(data['imageData'], 'utf-8'))
                elif six.PY2:
                    imageData = b64decode(data['imageData'])
               .............
def save(self, filename, shapes, imagePath, imageData,
            lineColor=None, fillColor=None):    
        try:
            with open(filename, 'w') as f:
                if six.PY3:
                    imageData = str(b64encode(imageData), 'utf-8') #b64encode(imageData.encode('utf-8'))
                elif six.PY2:
                    imageData = b64encode(imageData)
                   .......................

`

When I load json file: 
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\labelme-2.6.4-py3.5.egg\labelme\app.py", line 780, in openFile
  File "C:\Anaconda3\lib\site-packages\labelme-2.6.4-py3.5.egg\labelme\app.py", line 665, in loadFile
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by wkentaro** [comment]
Sorry for late, but I confirmed this issue on Python3.
https://github.com/wkentaro/labelme/pull/61 should fix this.

**Comment by rafaelvalero** [comment]
you may try insted of encode, decode.
