### ISSUE TITLE
read image from "imagePath" of json file not imageData

### ISSUE THREAD

**Issue by lunasdejavu** [wkentaro/labelme#252]
the environment is windows 7 x64 ananconda.
Since I already made a dataset with labelme, I want to do a different pre-processing to the image data.
 I named the image files with the same names, but when I opened them with labelme , it read imageData from json. I tried to remove the imageData from json files and there is an error showed up. I let the "imagePath"  to be the precise location like "D:/1.bmp" but it was still not working. Can someone tell me how to fix this problem? is there any way to modify the source code? I installed labelme by pip.

**Comment by lunasdejavu** [comment]
I fixed it by myself:
```
json_files = glob.glob(r'D:/checkmask/*.json')
for json_file in json_files:
	print(json_file)
	with open(json_file, 'r') as data_file:
			data = json.load(data_file)
	data['imageData']=None
	print(data['imageData'])
	# for element in data:
	# 		print(element)
			# element.pop('imageData', None)
	with open(json_file, 'w') as data_file:
			data = json.dump(data, data_file)
```

**Comment by wkentaro** [comment]
labelme firstly tries to load image from imageData, and if it is null, it loads image from path.

**Comment by lunasdejavu** [comment]
@wkentaro  yes, I found it in the code after all.
Btw May I try to modify this part to add options in the setting to choose load from imageData or imagePath and if there is no "imageData" read the image from imagePath?
I just think it might make the project more reflexible, and it is not that important to waste your time and not hard for a beginner like me who can mess up a project.

**Comment by wkentaro** [comment]
yeah, contributions are welcome.
