### ISSUE TITLE
load labeled jsons from folder different from image folder

### ISSUE THREAD

**Issue by fortuneko** [wkentaro/labelme#253]
Hi all,   
I want to load label jsons from a folder different from the folder contains the images, and also i want to save the jsons to a folder different from the folder contains the images, How can do about this?

**Comment by wkentaro** [comment]
you can change the imagePath entry in the json file.

**Comment by fortuneko** [comment]
thanks @wkentaro 
I have tested but seems not work, i test it in this way
1) I have assembled the images in the folder named "JPEGImages", and the annotation json files in the folder named "jsons", the two folders are in same folder tree level 
2) I modify the json files in the "jsons" folder, changing the imagePath of one json file as  below:
```
"imagePath": "../JPEGImages/topview_bat1_20181029_000000.jpg"
```
3) then i open the labelme and click "OpenDir" select the "jsons" folder, no image or label data loaded

**Comment by wkentaro** [comment]
I tested in `examples/semantic_segmentation` with [test-253 branch](https://github.com/wkentaro/labelme/tree/test-253) and it works.

https://github.com/wkentaro/labelme/blob/7ae2822eaf6cfa1a20e39d7162170daf42d38108/examples/semantic_segmentation/data_annotated/2011_000003.json#L478-L481

Could you share your directory as a public repo?

**Comment by wkentaro** [comment]
You need to select the json file in the GUI or run `labelme data_annotated/2011_000003.json`.
This is because labelme tries to find image files (e.g., jpg, png) and there is no way to find json from image file path in general.
In this case, there are no image files left in `data_annotated/` so no images are loaded.

**Comment by fortuneko** [comment]
placing jsons and images at the same folder seems dose not matter  ,thanks
