### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by JasonHug** [wkentaro/labelme#255]
when i try to save as json file , the programme went wrong because i name label as chinese. enghlish is ok.
![1](https://user-images.githubusercontent.com/28496080/48897980-79207a00-ee86-11e8-9516-d93cea937f29.PNG)

**Comment by JasonHug** [comment]
@wkentaro pls check....

**Comment by wkentaro** [comment]
I tested as below and it worked. I use labelme 3.5.0. Maybe there are some differences among our envs.

https://github.com/wkentaro/labelme/blob/770ef378f3444ee185439ffba46d75b09fac1341/examples/primitives/primitives.json#L2-L13

**Comment by JasonHug** [comment]
is that related to OS...or anaconda's version? i'm win7 and anaconda 2.2.0..

**Comment by JasonHug** [comment]
maybe.. i'am using Python2.7

**Comment by wkentaro** [comment]
I confirmed this and https://github.com/wkentaro/labelme/pull/281 will fix it.
