### ISSUE TITLE
Set default label instead of individually selecting it for every instance

### ISSUE THREAD

**Issue by elmeriz** [wkentaro/labelme#263]
Is there a built-in way to select a default label which is used for every new polygon? I mean that by completing a polygon, it would automatically label it to the default class instead of creating a dialog asking for the label. I am annotating a dataset where only one label is present and there might be hundreds of polygons in an image. It really adds up when I have to always select the label for every new polygon I draw.

**Comment by wkentaro** [comment]
Yeah, I think it would be great we add it. If we have only a single label in the label list (`--labels`), and the `--validatelabel` is set as 'exact'.

**Comment by wkentaro** [comment]
You can do this as described here: https://github.com/wkentaro/labelme/issues/370
