### ISSUE TITLE
the tips to develop labelme

### ISSUE THREAD

**Issue by lunasdejavu** [wkentaro/labelme#275]
Sorry, I am very new to pyQt but I would like to add some functions to labelme.
After I git-clone all the project and add a new function in the file list like open dir or open file then it will open a folder and list the name of folders and show the result of pre-processing from the images inside the folders.
So I am trying to copy everything about open dir and modify the codes inside the action.
but what should I do to test it now?  I don't know the precise instruction to test it like 
`python setup.py`?

**Comment by 111Moderato** [comment]
Maybe you could try:
python setup.py install --record install.txt

**Comment by wkentaro** [comment]
Normally I do:

```
git clone https://github.com/wkentaro/labelme.git
cd labelme

curl -L https://github.com/wkentaro/dotfiles/raw/master/local/bin/install_anaconda3.sh | bash -s .
source .anaconda3/bin/activate
pip install --editable .  # same as python setup.py develop
```

**Comment by lunasdejavu** [comment]
@wkentaro  is there any other way to do it in windows 7 environment?
```
curl -L https://github.com/wkentaro/dotfiles/raw/master/local/bin/install_anaconda3.sh | bash -s .
source .anaconda3/bin/activate
```
then it showed
```
bash: mktemp: command not found
[bash] Unsupported platform: Windows_NT
```
or can I just do `python setup.py develop` after every time I modify the code?

**Comment by wkentaro** [comment]
Oh, mktemp does not work on windows. What can we use on windows to create temporary directory?

> or can I just do python setup.py develop after every time I modify the code?

Well, you don't need to run `python setup.py develop` every time, since that's why we want to use `develop` instead of `install`.

**Comment by lunasdejavu** [comment]
Thanks, Kentaro! That is really helpful! 
I make a list which I am going to do next [here](https://medium.com/@lunasdejavu/customize-labelme-c67cc186f221)
Once I accomplish, I will try to update it here.
