### ISSUE TITLE
Possible to keep all instance the same colour while using different label names?

### ISSUE THREAD

**Issue by yyang294** [wkentaro/labelme#277]
As the title mentioned, I am wondering if it is possible when using labelme2voc. I have been trying to change some code with regard to colormap but with not success. Really appreicate!

**Comment by wkentaro** [comment]
I'm not sure but class label image already satisfy your needs, right?
https://github.com/wkentaro/labelme/tree/master/examples/semantic_segmentation#convert-to-voc-like-dataset
Two persons' label is brown and bottle is purple.

**Comment by yyang294** [comment]
I am running a data annotation company (www.awkvect.com) and this was originally a request by our client. They would like to have all the classes the same color while maintaining different class names (i.e. tree/people/car are of same color). I solved this by doing the following change to the file (\Python36\Lib\site-packages\labelme\utils\draw.py). Hope this could help people with similar question

def label_colormap(N=256):

    def bitget(byteval, idx):
        return ((byteval & (1 << idx)) != 0)

    cmap = np.zeros((N, 3))
    for i in range(0, N):
        id = i
        r, g, b = 0, 0, 0
        for j in range(0, 8):
            r = np.bitwise_or(r, (bitget(id, 0) << 7 - j))
            g = np.bitwise_or(g, (bitget(id, 1) << 7 - j))
            b = np.bitwise_or(b, (bitget(id, 2) << 7 - j))
            id = (id >> 3)
        cmap[i, 0] = r
        cmap[i, 1] = g
        cmap[i, 2] = b
    cmap = cmap.astype(np.float32) / 255
    # Peter's change start
    cmap [1:,:] = [0.5019608, 0, 0]
    # Peter'change End
    return cmap
