### ISSUE TITLE
How to set label color

### ISSUE THREAD

**Issue by InstantWindy** [wkentaro/labelme#288]
Hi, how do I set the color of the label? This label image is in P mode. How can I get the gray scale image?
Thanks!

**Comment by wkentaro** [comment]
Here:
https://github.com/wkentaro/labelme/blob/706dd36733ba9bc3b1bd3bee9f3a0cd1e9d4da63/labelme/utils/_io.py#L17-L18

**Comment by wkentaro** [comment]
You can change from

```python
        colormap = label_colormap(255)
        lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
```

to 

```python
        colormap = np.ones((255, 3), dtype=float)
        colormap[0] = [0, 0, 0]
        lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
```

**Comment by kalyandahal008** [comment]
Hi @wkentaro ,

**Comment by beizhengren** [comment]
@kalyandahal008 Have you solved the problem?

**Comment by PattonYu** [comment]
> You can change from
> 
> ```python
>         colormap = label_colormap(255)
>         lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
> ```
> 
> to
> 
> ```python
>         colormap = np.ones((255, 3), dtype=float)
>         colormap[0] = [0, 0, 0]
>         lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
> ```



> You can change from
> 
> ```python
>         colormap = label_colormap(255)
>         lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
> ```
> 
> to
> 
> ```python
>         colormap = np.ones((255, 3), dtype=float)
>         colormap[0] = [0, 0, 0]
>         lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
> ```
hi,I want to get a red mask lable.png( R:255 in RGB). so I changed my code in _io.py:
'colormap = label_colormap(255)
lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())'
to
'colormap = label_colormap(255)
colormap[0] = [255,0,0]
lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())'
and now, my mask is **r:255,g:0,b:0**, but the background is** r:1 g:0 b:0**
how to make background real black,like r:0 g:0 b:0,and the mask real red(r:255 g:0 b:0)

**Comment by YLONl** [comment]
> You can change from
> 
> ```python
>         colormap = label_colormap(255)
>         lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
> ```
> 
> to
> 
> ```python
>         colormap = np.ones((255, 3), dtype=float)
>         colormap[0] = [0, 0, 0]
>         lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
> ```
done.
Thanks.

**Comment by icoicqico** [comment]
> Hi @wkentaro,
> 
> I have Created 4 labels list in labelme. Each labels are different colors. Above suggestions would not help me because when i output All dataset . Same types of labels has different colors are found in different output Images. Is there any way to do same types of polygon labels has same colors in others images.
> Thanks!

Yes, I have the same problem, may I ask did you solve the problem?

**Comment by ItsMeTheBee** [comment]
You can simply change it to

```
if lbl.min() >= -1 and lbl.max() < 255:
		lbl_pil = PIL.Image.fromarray(lbl.astype(np.uint8), mode="P")
		#colormap = np.ones((255, 3), dtype=float)
		#colormap[0] = [255, 255, 255]
		#lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
		lbl_pil.save(filename) 
```

Now the images will be saved with label (1,1,1) for class 1 and (2,2,2) for class 2 etc.

**Comment by ItsMeTheBee** [comment]
Would be nice to have this as a command line option, if I have some free time I might propose that change
