### ISSUE TITLE
Can the converted file(label.png) be used directly to make tfrecord for Deeplab training?

### ISSUE THREAD

**Issue by DahuoJ** [wkentaro/labelme#289]
@wkentaro Hello! Thank you for providing this effective tool, but I have some confusion.
After converting this label, the label.png shows a color image, but it is still an 8-bit depth map(I don't know what this represents.).

![tim 20190104172139](https://user-images.githubusercontent.com/44385545/50681139-4f41a200-1045-11e9-8faa-2cfd9b00fd12.png)

The second doubt is that the label image looks like color, and when I extract its pixel value it also seems to be not gray value. I followed the voc2012 semantic segmentation dataset format. When I use it directly to make a dataset, the training results will appear in full black. So how do I get a label image with a label gray scale of 0, 1, 2... for training my dataset on Deeplab()?

![e7z4fq 6h 8wz 667s_av 5](https://user-images.githubusercontent.com/44385545/50680915-7350b380-1044-11e9-9e64-fae236fe1d79.png)

Any help will be appreciated!!

**Comment by wkentaro** [comment]
>  it is still an 8-bit depth map(I don't know what this represents.).

For PNG uint8 image, we can set colormap for each pixel value.

> The second doubt is that the label image looks like color

If you do things correctly, the PNG label image can be loaded as label values.
https://github.com/wkentaro/labelme/tree/master/examples/tutorial#how-to-load-label-png-file

**Comment by wkentaro** [comment]
👍

**Comment by DahuoJ** [comment]
hello, @wkentaro . May I ask you another question?
![s3 xx8kh sko h biyc36d](https://user-images.githubusercontent.com/44385545/51095344-1cd73800-17ef-11e9-8a6c-7cfafccbbd5e.png)
label_png is obtained by converting the json file.
label_png1 is obtained by converting the label_png by https://github.com/tensorflow/models/blob/master/research/deeplab/datasets/remove_gt_colormap.py.
It seems that they are all the same label map, but when I use label_png to make tfrecord files directly as a label map, the DeepLab_v3_plus will not work because of the wrong tfrecord files(as PascalVoc2012 dataset). What puzzles me is that when I use label_png1 to make tfrecord files, the network can work.     
Please give me some advice, thanks!!       :D

**Comment by AOTY-szy** [comment]
how the 8-bit label.png is generated? 
For example, cv.imwrite() will save the RGB image as 24-bit.
