### ISSUE TITLE
TOOL can not zoom in

### ISSUE THREAD

**Issue by trillionpowers** [wkentaro/labelme#29]
My environment is python2.7 + pyqt4 + linux (ubuntu 14.04). 
And I open an image in labelme. But it can not zoom in. 
How to zoom in an image?
Thanks for your help.

**Comment by wkentaro** [comment]
Ctrl-F ?

**Comment by trillionpowers** [comment]
It is working.
Thanks

**Comment by wkentaro** [comment]
Your welcome 👍
