### ISSUE TITLE
快捷键问题: Where hotkey is defined?

### ISSUE THREAD

**Issue by lijingrenya** [wkentaro/labelme#295]
你好。
1.可以告诉我有关快捷键的代码是哪个文件吗？
2.保存json文件的路径文件夹，可以提前选择吗？我在保存时每次都会询问....
以上~ 谢谢~

**Comment by wkentaro** [comment]
Sorry, but can you write it in English?

**Comment by lijingrenya** [comment]
> 对不起，你能用英文写吗？

hotkey → .py file → where is it?

**Comment by wkentaro** [comment]
The default hotkey is defined here: https://github.com/wkentaro/labelme/blob/34d7ce694b2181368ce7db46004842dec348f318/labelme/config/default_config.yaml#L44
It is used like this (`shortcuts['save_as']`): https://github.com/wkentaro/labelme/blob/34d7ce694b2181368ce7db46004842dec348f318/labelme/app.py#L232
