### ISSUE TITLE
creating multiple executable versions of labelme

### ISSUE THREAD

**Issue by digracesion** [wkentaro/labelme#296]
i wanted to make 3 versions of labelme: one for bounding box only, another for segmentation only, and another one for both segmentation and bounding box. i've already customized the tool (i created the one for both segmentation and bounding box first, and then copied the folder and edited bits of the code to create the segmentation and bounding box). now i only need to run each version separately. however, when i tried to run bounding box or segmentation build (i.e. i run python main.py in each folder), it's only the build with both segmentation and bounding box that runs.

**Comment by wkentaro** [comment]
So do you want to change the default mode of labelme by command line argument for example?

**Comment by digracesion** [comment]
yeah, something like that. for example, if i call labelme-boundingbox, it will only execute the build for bounding box. while if i call labelme-segmentation, it will only execute the build for segmentation.
