### ISSUE TITLE
Guideline for adding new label shapes and enabling rotation?

### ISSUE THREAD

**Issue by jonbakerfish** [wkentaro/labelme#298]
Thanks for open sourcing this handy tool! 
I want to add some new label shapes (e.g., ellipse, triangle) and enable the user to rotate the labels. Could you shed some light on the overall workflow of the program and which part of the code should be changed?

**Comment by wkentaro** [comment]
This is a logic to add new shape on canvas: https://github.com/wkentaro/labelme/blob/86bec5e0d7f48bff018696e898b18d158adb3d70/labelme/widgets/canvas.py#L178-L192
to finalize shape drawing on canvas: https://github.com/wkentaro/labelme/blob/86bec5e0d7f48bff018696e898b18d158adb3d70/labelme/widgets/canvas.py#L287-L309

Also I think you should search `createMode` in `canvas.py` to see how the program behaves differently for different shapes.
