### ISSUE TITLE
Could you help me a question?

### ISSUE THREAD

**Issue by happygao** [wkentaro/labelme#30]
Hello, I use the labelme software of your write recently. But I only need to label two class, one is road, and the other is background. So I want to modify the code, which to achieve the goal: we only mark the road, the rest of the image is not marked could auto marked a class, it it unnecessary to mark by our hands.Could you help me solve it? 
      Thanks very much.

**Comment by wkentaro** [comment]
You can do it by a script which converts the `label.json` to **dataset** (image.jpg, label.png) by modifying labelme_json_to_dataset:
https://github.com/wkentaro/labelme/blob/master/scripts/labelme_json_to_dataset
