### ISSUE TITLE
Import different coordinate/label files [feature request]

### ISSUE THREAD

**Issue by D-K-E** [wkentaro/labelme#301]
It would be great if we can import some coordinate files that are in well known formats like geojson, altoxml etc, to labelme interface directly. 

I am thinking a functionality like the following. 
After the users load an image/images.
The option to load coordinates becomes available.
We check if the file/file list contains the name of the image along with valid coordinates.
Those that do have a correspondence are associated to images, and their coordinates along with their labels if they exist, become available in the interface. 
If the labels do not exist for the polygons on the scene, user selects the objects on the scene by clicking on the objects while holding the `shift` key, than chooses a label to associate to chosen group. 

This would enable us to use labelme for correction as well, which is quite lacking if you are looking for a tool to correct the output of an automatic segmentation.  
I can see if I can do a PR if you want.

**Comment by D-K-E** [comment]
That might also work, but can we import labelme json files with empty labels ?

**Comment by wkentaro** [comment]
Have you tried?

**Comment by wkentaro** [comment]
Below json file can be loaded by labelme

```
{
  "shapes": [
  ],
  "lineColor": [
    0,
    255,
    0,
    128
  ],
  "fillColor": [
    255,
    0,
    0,
    128
  ],
  "imagePath": "2011_000003.jpg",
  "imageData": null
}
```
