### ISSUE TITLE
object label color not changing for different images where each image has one class

### ISSUE THREAD

**Issue by Kotresh17** [wkentaro/labelme#304]
Hi, thanks for the nice package. I am trying to solve medical image segmentation problem for ultrasound images. where each image has only one class. when I label the other class image color remains same. how to change the fill polygon color in the label. am attaching a labelled image.
![label](https://user-images.githubusercontent.com/24634109/51801632-736c5980-2266-11e9-89a4-bf1782433ae3.png)

**Comment by Kotresh17** [comment]
Original image
![3_1](https://user-images.githubusercontent.com/24634109/51801657-dbbb3b00-2266-11e9-9946-8d1f8aff140b.jpg)

**Comment by wkentaro** [comment]
Have you tried `labelme2voc.py`? It converts a JSON file to a colorized PNG file with different colors for different classes.
https://github.com/wkentaro/labelme/tree/master/examples/semantic_segmentation#convert-to-voc-like-dataset

**Comment by wkentaro** [comment]
I don't understand when you are encountering this problem. Are you using `labelme_json_to_dataset.py`?

**Comment by Kotresh17** [comment]
> Have you tried `labelme2voc.py`? It converts a JSON file to a colorized PNG file with different colors for different classes.
> https://github.com/wkentaro/labelme/tree/master/examples/semantic_segmentation#convert-to-voc-like-dataset

I tried this when i run that code. I got an assertion error
Creating dataset: dataset
Traceback (most recent call last):
  File "labelme2voc.py", line 90, in <module>
    main()
  File "labelme2voc.py", line 42, in main
    assert class_name == '__ignore__'
AssertionError

**Comment by Kotresh17** [comment]
> I don't understand when you are encountering this problem. Are you using `labelme_json_to_dataset.py`?

yeah when I run this I got colorized PNG file like the one as above for all the classes with the same color as above.

**Comment by wkentaro** [comment]
`labelme_json_to_dataset.py` is not the script you want as it says in the warning.
https://github.com/wkentaro/labelme/blob/1e3a5b147100c426a744f00a852ca24089efba98/labelme/cli/json_to_dataset.py#L15-L17

I think you're missing `__ignore__` class on the top.
https://github.com/wkentaro/labelme/blob/1e3a5b147100c426a744f00a852ca24089efba98/examples/semantic_segmentation/labels.txt#L1

**Comment by Kotresh17** [comment]
I just modified it and my labels.txt is like this __ignore___background_BenignMalign-4a    
I have 4 classes benign, malign-4a, malign-4b, malign-4c. I have 40 images of each. each image has only one class as above. when I drew annotation for benign and I got PNG file with polygon color red. and again when I drew annotation for malign-4a I got PNG file with polygon color red. I am getting same color for all the classes. after two classes I run the code labelme2voc.py it's crashed. how to change the fill polygon color manually. Is there any way to do that.

**Comment by wkentaro** [comment]
> when I drew annotation for benign and I got PNG file with polygon color red. and again when I drew annotation for malign-4a I got PNG file with polygon color red.

Do you mean below command outputs the same color for different classes?
If so, I can only say something is wrong..

```
./labelme2voc.py your_labels.txt your_data_annotated your_data_dataset_voc
```

```
# your_labels.txt
__ignore__
_background
benign
malign-4a
malign-4b
malign-4c
```

**Comment by Kotresh17** [comment]
No not that when I run labelme_json_to_dataset it's giving same Color for the different classes. After that when I run labelme2voc.py it suddenly got crashed.

**Comment by wkentaro** [comment]
Ok, so why your labelme2voc.py crashes?

**Comment by Kotresh17** [comment]
> Ok, so why your labelme2voc.py crashes?

when I run the code terminal showing like it suddenly stopped working. now i just recreated the conda environment labelme. now its working fine. yeah I was missing a _ignore_ class. now I successfully created a multiclass segmentation dataset with different classes and different colors. thank you so much for your response.
