### ISSUE TITLE
AttributeError: 'BmpImageFile' object has no attribute '_getexif'

### ISSUE THREAD

**Issue by pantingchn** [wkentaro/labelme#310]
I have created the envs "labelme" and installed all the packages needed, but when I open the image to process, some errors happen. It says: "AttributeError: 'BmpImageFile' object has no attribute '_getexif‘. How to solve this problem???
![default](https://user-images.githubusercontent.com/41134171/52125869-c3815c80-2668-11e9-9e38-3f5e1e11f494.PNG)

**Comment by wkentaro** [comment]
Thanks for the report. This will be fixed by https://github.com/wkentaro/labelme/pull/311.
