### ISSUE TITLE
Error in installation. 

### ISSUE THREAD

**Issue by piperod** [wkentaro/labelme#32]
Hi there, 

Im trying to install labelme in a mac (OS Sierra). Everything goes fine until I type "labelme" to launch the GUI. This errors appears: 

Traceback (most recent call last):
  File "app.py", line 32, in <module>
    from PyQt5.QtGui import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/sip.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /usr/local/lib/python2.7/site-packages/sip.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/sip.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 37, in <module>
    from PyQt4.QtGui import *
ImportError: No module named 'PyQt4'

Any help, very appreciated. Thanks

**Comment by wkentaro** [comment]
So, you fail to import`PyQt5`, right? `python -c 'from PyQt5.QtGUI import *'` fails?

If so, I think you need to reinstall pyqt5 by `brew install pyqt`, and to check your python environment is normal. (maybe you need `brew reinstall python`?)
