### ISSUE TITLE
no sudo privilege in docker env

### ISSUE THREAD

**Issue by cissoidx** [wkentaro/labelme#323]
First, thanks for the great work. 
I have tried to make a docker image from the Dockerfile you provided, everything is good but the developer user does not have su privilege, so I cannot install my own packages in the container. Password is required when asked for su privilege and then it just shows: 

su: Authentication failure

**Comment by wkentaro** [comment]
How to reproduce?

**Comment by cissoidx** [comment]
Thanks for the reply.
1. use the Dockerfile you provided to generate a image
2. run the image with -it
3. try sudo apt install some_package or sudo su

cheers.

**Comment by wkentaro** [comment]
With https://github.com/wkentaro/labelme/pull/328, you can't use `su -` but you can use `sudo <command>`.

**Comment by cissoidx** [comment]
Got it. Thanks.
