### ISSUE TITLE
PyInstall : labelme.exe does not execute anything (proposed fix)

### ISSUE THREAD

**Issue by vincentAgnus** [wkentaro/labelme#326]
Hi,

when building, labelme.exe using pyinstaller and launch hit. the program do not execute anything. Indeed the .spec file specifies that script `main.py` must be executed but this file does not contain code about this.
So adding 
```python
if __name__ == "__main__":    
    main()
```
at the end of `main.py` solve the problem for me.
There is perhaps an entry-point option in .spec pyinstaller file to specify main.py:main as function to start.

**Comment by wkentaro** [comment]
Thanks for the report!

**Comment by wkentaro** [comment]
I released v3.9.1.

**Comment by mingweiY** [comment]
Hi,
i have a problem,the labelme.exe is so big,i used the labelme.spec
