### ISSUE TITLE
deselect all in polygon labels menu

### ISSUE THREAD

**Issue by mynameismaxz** [wkentaro/labelme#330]
How to deselect all of the object that labeled in the "polygon labels" menu on the right.

**Comment by wkentaro** [comment]
Do you mean all at once? I think you can deselect from polygon labels by clicking somewhere else.

**Comment by mynameismaxz** [comment]
Thank you for your answer, but I've been found solution that deselects the polygon all at once. Click on View menu and Hide Polygon. It's just deselecting all of the polygons on the Combo Box menu.

**Comment by easz** [comment]
is there any key board shortcut to do this?
it would be pretty handy.
