### ISSUE TITLE
How to use Qt Designer to add new GUI features? 

### ISSUE THREAD

**Issue by erenRRDA** [wkentaro/labelme#332]
Is it possible to add new GUI features though Qt Designer (need a .ui file) ?
Does labelme all written by source code level without any visual design tool?

**Comment by wkentaro** [comment]
> Does labelme all written by source code level without any visual design tool?

Actually, yes. So I’m not exactly sure how to use it.

**Comment by erenRRDA** [comment]
Oh, I see. That is a great work to do by editing source code only. Hope we can find some way to use Qt Designer.
