### ISSUE TITLE
Question about returning to the mouse mode

### ISSUE THREAD

**Issue by shuangshuangguo** [wkentaro/labelme#333]
Hi, thank you for the wonderful job.
I want to use this tool to label table lines, but after I click 'Create Line' botton, I can not return to the moude mode. Is it normal? Please help me. Thank you.

**Comment by shuangshuangguo** [comment]
And I found that a line can not be deleted.

**Comment by wkentaro** [comment]
> I can not return to the moude mode

What is mouse mode?

> And I found that a line can not be deleted.

You need delete line annotations from the 'Polygon Labels' list in the right side. Doesn't this work?
