### ISSUE TITLE
Same labels Names has different colors in  whole Data-set.

### ISSUE THREAD

**Issue by kalyandahal008** [wkentaro/labelme#337]
Hi @wkentaro,

I have Created 4 labels list in labelme. Each labels are different colors. Above suggestions would not help me because when i output All dataset . Same types of labels has different colors are found in different output Images. Is there any way to do same types of polygon labels has same colors  in others images.
Thanks!

_Originally posted by @kalyandahal008 in https://github.com/wkentaro/labelme/issues/288#issuecomment-466310439_

**Comment by wkentaro** [comment]
I'm not sure what exactly is your problem. You mean the `labelme2voc.py` doesn't work?
