### ISSUE TITLE
mouseclick event

### ISSUE THREAD

**Issue by lijingrenya** [wkentaro/labelme#338]
Hello!
When the mouse is double clicked, the label list will pop up. How to disable?

**Comment by wkentaro** [comment]
I'm not sure what exactly you are talking about. Please describe with screenshots.

**Comment by lijingrenya** [comment]
Sorry, due to the internet problem, I could not provide you the screenshot.
Please refer to the first picture in the module of README on the home page, it shows the prompt box of label list. 
The situation is when I clicked the button of ''create polygons", and during this process, if at this moment I double-clicked the mouse, it appeared the prompt box of label list. So if the prompt box could be no longer displayed through modifing the code? Hope to hear from you soon. Thank you for your support.

**Comment by wkentaro** [comment]
I click mouse 3 times on canvas in "create polygons" mode, the app shows the prompt box, but with a double-click (this is what you're talking about, right?), there will be no prompt box.

**Comment by wkentaro** [comment]
I don't quite understand:

1. how to reproduce your situation.
2. why you want to stop the situation.

**Comment by lijingrenya** [comment]
![snipaste_2019-03-04_09-02-19](https://user-images.githubusercontent.com/28614797/53705001-478f5580-3e5c-11e9-9c9b-c832d2ec6816.jpg)

1.As shown in the figure.
I need to labeling the face all by clicking the mouse continuously.
During the "Create polygons" process, double-clicking the mouse will pop up the prompt box.
2.Need to get the job done quickly with a continuous click of the mouse, so I'd like to disable this feature.
Thank you so much!

**Comment by lijingrenya** [comment]
![1](https://user-images.githubusercontent.com/28614797/53705285-43fcce00-3e5e-11e9-9fa9-15f87ed696e0.gif)

As the GIF shows

**Comment by Rchart** [comment]
Hello!

Could you disable this? I have the same problem here.

**Comment by wkentaro** [comment]
With https://github.com/wkentaro/labelme/pull/545, you can modify the behavior when you double-click:

```
cd examples/semantic_segmentation
labelme data_annotated --config '{canvas: {double_click: close}}'  # default (close polygon)
labelme data_annotated --config '{canvas: {double_click: null}}'     # do nothing
```
