### ISSUE TITLE
How to create a COCO-format training set

### ISSUE THREAD

**Issue by DarylWM** [wkentaro/labelme#34]
Thank you for sharing this tool. I'm interested in creating a COCO-format training set. I've looked at the COCO 2017 downloads and they seem to have a set of images and a single JSON file with instance information in it. I think that corresponds to the JSON output of LabelMe but I'm not clear. Is labelme_json_to_dataset intended to create a COCO-style training set?

**Comment by wkentaro** [comment]
Currently, labelme does not support making COCO-style training set, and you need to create a new script to create it.
COCO's annotation JSON file has all annotations for each image set (train, val, minival), so I think you can see all annotated file (ex. label.json) and merge them into a single JSON file in the script.

**Comment by gsujansai** [comment]
Hi @DarylWM 
Did you end up creating a script to merge all the individual JSON files to one file like in the coco format ?

**Comment by zeliangDing** [comment]
hello, wkentaro! Thank you for sharing this tool.
i find a bug. When i using the tools, Why dyed the same color to different classes。can you explain this phenomenon？

**Comment by wkentaro** [comment]
I added a script that generates coco format dataset (JSON annotation file) from annotation directory.
https://github.com/wkentaro/labelme/pull/309

**Comment by lintangsutawika** [comment]
Loading the `annotation.json` file generated from the script
```
from pycocotools.coco import COCO
coco = COCO("annotation.json)"
```

Results in error
```
KeyError                                  Traceback (most recent call last)
<ipython-input-17-b6495789f3cf> in <module>()
----> 1 coco = COCO("./annotations.json")

~/anaconda3/lib/python3.6/site-packages/pycocotools/coco.py in __init__(self, annotation_file)
     86             print('Done (t={:0.2f}s)'.format(time.time()- tic))
     87             self.dataset = dataset
---> 88             self.createIndex()
     89 
     90     def createIndex(self):

~/anaconda3/lib/python3.6/site-packages/pycocotools/coco.py in createIndex(self)
     96             for ann in self.dataset['annotations']:
     97                 imgToAnns[ann['image_id']].append(ann)
---> 98                 anns[ann['id']] = ann
     99 
    100         if 'images' in self.dataset:

KeyError: 'id'
```

**Comment by elnazsn1988** [comment]
@wkentaro @DarylWM can you @lintangsutawika can you tell exactly how you loaded you image to be annotated in COCO format after generating polygons?
