### ISSUE TITLE
Language transliteration.

### ISSUE THREAD

**Issue by lifeisshubh** [wkentaro/labelme#340]
Can it be possible to integrate some language multilingual-transliteration tool (for e.g. https://www.google.co.in/inputtools/try/)? It will be very helpful in annotating scene text data. 
Thanks.

#RequestForFeature

**Comment by wkentaro** [comment]
I'm not familiar with annotations for text detection and recognition, so I'm not sure how useful it is.
Also, I have no idea how much usually you need to annotate multi-languages at the same time.
I thought usually user annotates for single language at one time.

Are there enough reasons that make sense of adding this feature.

**Comment by lifeisshubh** [comment]
Annotation for scene text detection and recognition is very similar to object detection, the one thing in which they differ slightly is the labeling.
When we see text in the natural scene it often consists of multilingual text, especially in a diverse country like India. But typing in a different language requires domain knowledge of specific keys placement of those languages which is an additional barrier. Addition of transliteration can help to bring down this barrier.
Even it can help in single language annotation if someone wishes to prefer some other language for labeling.
Thanks.

**Comment by lifeisshubh** [comment]
I am able to do annotation with the help of google input tools.
