### ISSUE TITLE
I Can't launch labelme from another python application

### ISSUE THREAD

**Issue by loeblg** [wkentaro/labelme#342]

**Comment by loeblg** [comment]
Hi,
I'm trying to call the labelme directly from another Qt GUI . So after I installed it, I use the following code:
======================================
    def show_png_file(self):
        """ Open an OS .png file
         Using "labelme" free SW. it must be installed 1st.
         """
        row = self.pdf_files_table.currentRow()
        if row == -1:
            return

        img_file = self.png_list[row][0]
        path2 = Path(img_file)
        if not path2.exists():
            self.errorMessage('Error opening file', 'No such file: <b>%s</b>' % path2)
            return False
        # print(path2)
        lbl_app = QtWidgets.QApplication(sys.argv)
        lbl_app.setApplicationName(__appname__)
        lbl_app.setWindowIcon(newIcon('icon'))
        win = MainWindow(filename=path2)
        win.show()
.
.
.
================
So as it is here, it does not work. I can see that the window is opened for a split of a second, and then it disappears. 
But, when I run in through Pycharm with a break point and I single step into it, it opens normally. 
Do you have any Idea why? How can I call it from my application?

Also, another question,
I see you are using EXIF data to rotate the image if it is required. Is there a way to manually rotate it inside the tool? Is it possible to add a button to rotate?

and finally, is it possible to save the json data w/o the image? such that the file is much smaller?


Thanks for a great job!

Gabi

**Comment by wkentaro** [comment]
> So as it is here, it does not work. I can see that the window is opened for a split of a second, and then it disappears.
But, when I run in through Pycharm with a break point and I single step into it, it opens normally.
Do you have any Idea why? How can I call it from my application?

The easiest way is using `subprocess.call(shlext.split('labelme image.jpg'), shell=True)`.

> I see you are using EXIF data to rotate the image if it is required. Is there a way to manually rotate it inside the tool? Is it possible to add a button to rotate?

No, and at the moment I don't think it is not a  feature that should be covered by labelme.

>  is it possible to save the json data w/o the image? such that the file is much smaller?

Yes. You can use `--nodata` option.

**Comment by TommyHuang821** [comment]
Do you have any w/o image saving option in GUI?
Thanks.

**Comment by wkentaro** [comment]
> Do you have any w/o image saving option in GUI?
Thanks.
 
Actually, that has not implemented yet.
