### ISSUE TITLE
why  labelme 3.10.1 save json so big?

### ISSUE THREAD

**Issue by archwolf118** [wkentaro/labelme#346]
I upgraded labelme to newest version 3.10.1 (I use pip install labelme), and when I annotate the image and save it, I found the json-file is much bigger then the image-file. It is so weird, and load the image's speed is much slower than the previous version.
Thank you!

**Comment by wkentaro** [comment]
What is the last version you think it is good?

**Comment by archwolf118** [comment]
I think the 3.6version is the best. when you load a large picture in vision3.7~3.10, like 4000*3000，the saved json is about 10 times then the image file。

**Comment by thuzhf** [comment]
@wkentaro I encountered the same problem. The speed of loading an image is **much slower** than the previous version.

**Comment by thuzhf** [comment]
@wkentaro I have tested several recent versions, and found that v3.6.16 is unaffected and since v3.7.0 the problem occurs. After some code-reading I think the problem may be due to this commit: f1600ce.

**Comment by wkentaro** [comment]
Good catch! Thank you for finding the cause of this problem.
Maybe because it converts every file to PNG format even if it was originally JPEG file.
I will fix it soon.
