### ISSUE TITLE
Option to merge polygons

### ISSUE THREAD

**Issue by sdeleersnijder** [wkentaro/labelme#35]
In some images the middle of an object is occluded, causing two disjoint polygons belonging to the same instance. It would be nice if there was an option to merge polygons into a single object. 

Nice tool by the way, thanks for making this!

**Comment by wkentaro** [comment]
I think visualizing merged polygon and creating GUI to merge it is a bit hard to implement, and currently, I have no idea.

In my mind, I segment the instance and annotated polygon. The instance label will be decided by label name; if there are 2 horses and 1 person with overlap among them, I don't annotate `horse`, `horse`, `person`, but `horse`, `horse-2`, `person`. And the script later used to create dataset will recognize `horse-2` as `horse`.

**Comment by sdeleersnijder** [comment]
Yes, I guess I could use multiple instances of `horse-x` if there is a horse that is split into 2 disjoint polygons and use a script to merge them later. Thanks!

**Comment by wkentaro** [comment]
It seems merging polygon does not always work when there is no overlap among polygons, and using a script later is fine.
So I am closing this for now. Please request for reopen if anyone needs this feature.
