### ISSUE TITLE
Same Object Name but different color when converting to voc [bug?]

### ISSUE THREAD

**Issue by wtiandong** [wkentaro/labelme#351]
Hi wkentaro,
I notice that in [examples/instance_segmentation/data_dataset_voc/SegmentationObjectVisualization/2011_000003.jpg](https://github.com/wkentaro/labelme/blob/master/examples/instance_segmentation/data_dataset_voc/SegmentationObjectVisualization/2011_000003.jpg), the color rendered on the man on the right side seems wrong. His fingers on the left side of the bottle is yellow, while his body is green. However, the fingers are labeled as person-2.

**Comment by wkentaro** [comment]
Hi @wtiandong. Thank you for the report. I confirmed that this is a bug (actually I was using a different code in my project).
This bug will be fixed via #352.
