### ISSUE TITLE
Weird double label in --keep-prev situation

### ISSUE THREAD

**Issue by YuchenWang** [wkentaro/labelme#360]
I install it in Mac OS with python3,PyQt5
Let's take in video annotation in video
When I start labelme at first, it all works correct.
<img width="1331" alt="8260E210-1270-4AB2-97A6-00AEC35AAA8E" src="https://user-images.githubusercontent.com/15023991/55431229-04f59180-555e-11e9-8ddf-4bffb72dad1c.png">
But after I click next image, then it will duplicate the polygon.
<img width="1328" alt="B46F59AC-55E7-4DD9-AF4A-D31FD60A0535" src="https://user-images.githubusercontent.com/15023991/55431483-aa106a00-555e-11e9-9aac-1d61c76c227d.png">
If I save the label in this time, it will save 6 polygon which double the original polygon. If I I try to del the duplicate polygon before save, it will cause error and quit the program ValueError: list.remove(x): x not in list.

**Comment by wkentaro** [comment]
Thanks for the report. I will check it.

**Comment by YuchenWang** [comment]
I sat this case was closed. But I just update the new version and it seems that this problem still existed?

**Comment by wkentaro** [comment]
Are you sure?

**Comment by wkentaro** [comment]
First of all, I would say the duplicate label is expected behavior when you use `--keep-prev`.
What I fixed is making it deletable.

**Comment by YuchenWang** [comment]
Yes, I retry it again and also if I try to delete the duplicate label, it still give the same error. (I check my labelme --version, it is labelme 3.11.2, I hope it is the correct version which you fixed)

**Comment by wkentaro** [comment]
Could you upgrade to labelme >= 3.12.0 ?
![image](https://user-images.githubusercontent.com/4310419/56165889-0a29f600-5fcc-11e9-81df-2a9675b0aeec.png)

**Comment by YuchenWang** [comment]
Great, now I may remove the duplicate label correctly. Thanks for your quick response. 
But I still hope this kind of duplicate label could be solved, so it will not copy the label when the image move backward.

**Comment by wkentaro** [comment]
Yeah, it seems reasonable to not copying to already labeled image. Could you open an issue for that?

**Comment by YuchenWang** [comment]
Sure, I will open a new issue.
