### ISSUE TITLE
Point annotation without label

### ISSUE THREAD

**Issue by Ethanwl** [wkentaro/labelme#370]
I just want to use point annotation and save points' coordinate. I don't need labels.
1. How to disable label dialog? Or it automatically chooses a default label without label dialog.
2. Can labelme only save  points' coordinate without other information?

**Comment by wkentaro** [comment]
1. You can set `display_label_popup: false` in the config file e.g., `~/.labelmerc`. 

2. No it’s not possible.

**Comment by Ethanwl** [comment]
Thank you for your reply. But it doesn't work. The dialog still appears after every annotation. The version is 3.13.1. The config is as follows:


auto_save: false
display_label_popup: false
instance_label_auto_increment: true
store_data: true
keep_prev: false
logger_level: info

flags: null
labels: [h]
file_search: null
sort_labels: true
validate_label: null

Other configs are unchanged.

**Comment by Ethanwl** [comment]
Now I know what's wrong. I don't chose the label in label dock after launch the labelme. This is a key step.
