### ISSUE TITLE
keep-prev mode will copy label to previous image(which has been labeled)

### ISSUE THREAD

**Issue by YuchenWang** [wkentaro/labelme#375]
In keep-prev mode, if I jump an image which has been labeled, it will still copy label to that image. When I just move backward, the label in former image will be duplicated, it make a little bit confused.

**Comment by ChuhuaW** [comment]
I added a condition in app.py:1185
`if self._config['keep_prev'] and not self.labelList.itemsToShapes:`
Seems to solve the issue.
