### ISSUE TITLE
What does image data consist of ?

### ISSUE THREAD

**Issue by lifeisshubh** [wkentaro/labelme#376]
I thought that image data consist of the image in bytes or string form. 
So, I have tried to write it in the form of an image file.
```
red = open(annotation_img_file,'r')
data = json.load(red)
img = data['imageData']
rm = open('img.jpg','w')
rm.write(img)
rm.close()
```
I have checked the supposed the image file, and it is showing image is currupted.

I have also tried to image data assuming it is the original image using some other way,
```
image = Image.open(io.BytesIO(img))
```
This also throwing error.

**Comment by wkentaro** [comment]
You can see the logic here:
https://github.com/wkentaro/labelme/blob/11c0fc8f47ca4fb228ae53d1e7a243151227ba3c/labelme/label_file.py#L66-L71
