### ISSUE TITLE
labelme2voc.py: error: the following arguments are required: --labels

### ISSUE THREAD

**Issue by BillGreenHand** [wkentaro/labelme#380]
after runing  python ./labelme2voc.py -labels.txt  data_annotated data_dataset_voc,appear labelme2voc.py: error: the following arguments are required: --labels,i don't find the reason,you know?

**Comment by wkentaro** [comment]
Because label list is required to export dataset.

**Comment by BillGreenHand** [comment]
i know,but i put these folders labels.txt data_annotated data_dataset_voc  together,Why does this problem arise? and how should  i  solve it?

**Comment by wkentaro** [comment]
> but i put these folders labels.txt data_annotated data_dataset_voc together,

What do you mean by this?

**Comment by laurasels** [comment]
In which folder did you run: ./labelme2voc.py data_annotated data_dataset_voc --labels labels.txt?

because I got an error when I'm trying to run this line in the terminal.
