### ISSUE TITLE
how to get white masks?

### ISSUE THREAD

**Issue by SonOfCoding** [wkentaro/labelme#381]
Thank you for your contribution. I m using this tool to get the masks. However, when I am running labelme_json_to_dataset 000001.json. In the dataset,  I get the red mask with black background. how to get white mask with black background?  please help me, thank you. 

By the way, I have tried to change from

        colormap = label_colormap(255)
        lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
to

        colormap = np.ones((255, 3), dtype=float)
        colormap[0] = [0, 0, 0]
        lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())

but it does not work

**Comment by wkentaro** [comment]
Really, it works on my env. Please make sure your env is sane.

![image](https://user-images.githubusercontent.com/4310419/56503668-13581d00-650e-11e9-80ee-dd4f304a3557.png)

**Comment by SonOfCoding** [comment]
do I only need to make a change in io. py and then use labelme_json_to_dataset command?

**Comment by SonOfCoding** [comment]
import os.path as osp

import numpy as np
import PIL.Image

from labelme.logger import logger
from labelme.utils.draw import label_colormap


def lblsave(filename, lbl):
    if osp.splitext(filename)[1] != '.png':
        filename += '.png'
    # Assume label ranses [-1, 254] for int32,
    # and [0, 255] for uint8 as VOC.
    if lbl.min() >= -1 and lbl.max() < 255:
        lbl_pil = PIL.Image.fromarray(lbl.astype(np.uint8), mode='P')
        #colormap = label_colormap(255)
        colormap = np.ones((255, 3), dtype=float)
        colormap[0] = [0, 0, 0]
        lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
        lbl_pil.save(filename)
    else:
        logger.warn(
            '[%s] Cannot save the pixel-wise class label as PNG, '
            'so please use the npy file.' % filename
        )
I have changed the _io,py like this, but the mask is still red when i run edison@amax2:~/data1_edison/try_try_look/mit_label/labelme/examples/semantic_segmentation/data_dataset_voc/JPEGImages$ labelme_json_to_dataset 2011_000003.json

did i do something worng?

**Comment by wkentaro** [comment]
> do I only need to make a change in io. py and then use labelme_json_to_dataset command?

yes.

Maybe you didn't run `pip install .` after changing it.

**Comment by PattonYu** [comment]
> > do I only need to make a change in io. py and then use labelme_json_to_dataset command?
> 
> yes.
> 
> Maybe you didn't run `pip install .` after changing it.

the lable.png in default is r:128 g:0 b:0.
How can I change the red color to 255 in RGB?

**Comment by gg22mm** [comment]
？I can't

**Comment by gg22mm** [comment]
How can I get white?   我install: pip install labelme

How can I get white?   


import os
for i in range(1,260):	
	my_file =os.path.isfile(str(i) + ".json")
	if my_file == True :
		os.system("labelme_json_to_dataset " + str(i) + ".json")


I only get red. How does it turn white？

**Comment by gg22mm** [comment]
I can only use Adobe Photoshop CS2, That's stupid.
