### ISSUE TITLE
pyinstaller

### ISSUE THREAD

**Issue by mingweiY** [wkentaro/labelme#382]
您好，我用压缩包里自带的labelme.spec，用pyinstaller去打包成exe，竟然有200M，请问怎么解决这个问题

**Comment by wkentaro** [comment]
> Hi,
i have a problem,the labelme.exe is so big,i used the labelme.spec

https://github.com/wkentaro/labelme/issues/326

What is the expected size?

**Comment by mingweiY** [comment]
i thank 20-30M，but it has 200M,when i only use python not anacoda ,the exe is 67M,Is this normal？

---Original---

**Comment by wkentaro** [comment]
Why 20-30M? You're saying with the system Python, the size of .exe file is 67M, right?

I don't know what is normal, actually.

**Comment by mingweiY** [comment]
First, thank you for your answer.
my mean,is there a minimum size of the exe or a normal size of the size?




------------------ 原始邮件 ------------------
发件人: "Kentaro Wada"<notifications@github.com>; 
发送时间: 2019年4月23日(星期二) 上午9:57
收件人: "wkentaro/labelme"<labelme@noreply.github.com>; 
抄送: "A Student"<1337442535@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wkentaro/labelme] pyinstaller (#382)




Why 20-30M? You're saying with the system Python, the size of .exe file is 67M, right?
 
I don't know what is normal, actually.

**Comment by wkentaro** [comment]
> is there a minimum size of the exe or a normal size of the size?

I don't know. I think it depends on versions of every dependency, Python version, and platform.

**Comment by mingweiY** [comment]
Thank you,my teacher say the size is ok

---Original---

**Comment by Javacr** [comment]
> Thank you,my teacher say the size is ok
> […](#)

哥们儿，请问你打包成功后，能够运行吗？我打包完了，报错“failed to execute script__main_”

**Comment by mingweiY** [comment]
没遇到过这个问题，你用的什么打包





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Javacr"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 下午4:55
收件人:&nbsp;"wkentaro/labelme"<labelme@noreply.github.com&gt;;
抄送:&nbsp;"A Student"<1337442535@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wkentaro/labelme] pyinstaller (#382)





  
Thank you,my teacher say the size is ok
 …
  
哥们儿，请问你打包成功后，能够运行吗？我打包完了，报错“failed to execute script__main_”

**Comment by Javacr** [comment]
> 没遇到过这个问题，你用的什么打包
> […](#)

按照作者给的方法，先用conda创建一个环境，我用的是python3.6。下载一个labelme4.2.9压缩包，解压。进入建好的环境,再进入解压后的labeme文件夹，pip install .， 再pip install pyinstaller，之后对labelme.spec打包,打包完成后点击exe文件的时候就报以上错误了。请问我是不是哪里出错了呢？

**Comment by mingweiY** [comment]
你好，我刚才测试了一下，ModuleNotFoundError: No module named 'imgviz'，建议你先不要指行pyinstaller labelme.spec， 现在lableme文件夹内指行pyinstaller -F __main__.py，这样会把问题爆出来，如果这样没问题了，再用作者的.spec文件生成


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Javacr"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 下午5:11
收件人:&nbsp;"wkentaro/labelme"<labelme@noreply.github.com&gt;;
抄送:&nbsp;"A Student"<1337442535@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wkentaro/labelme] pyinstaller (#382)





  
没遇到过这个问题，你用的什么打包
 …
  
按照作者给的方法，先用conda创建一个环境，我用的是python3.6。下载一个labelme4.2.9压缩包，解压。进入建好的环境,再进入解压后的labeme文件夹，pip install .， 再pip install pyinstaller，之后对labelme.spec打包,打包完成后点击exe文件的时候就报以上错误了。请问我是不是哪里出错了呢？

**Comment by Javacr** [comment]
> 你好，我刚才测试了一下，ModuleNotFoundError: No module named 'imgviz'，建议你先不要指行pyinstaller labelme.spec， 现在lableme文件夹内指行pyinstaller -F __main__.py，这样会把问题爆出来，如果这样没问题了，再用作者的.spec文件生成
> […](#)

谢谢大佬，真的解决这个问题了。，的确，先执行main后，会提示缺包，然后再安装这些包就行了。
