### ISSUE TITLE
how to add attribute for classes

### ISSUE THREAD

**Issue by passion3394** [wkentaro/labelme#383]
thanks for your great work. I want to know whether this software contains the function of "add attribute for classes".

**Comment by wkentaro** [comment]
Do you mean something like below? Currently, you need to annotate like `person (standing, eating)`, `dog (walking,)` for labels,
and there is no other feature like a checkbox to select attributes. I think that would be useful if we have such features.

classes
- dog
- person

attributes
- standing
- walking
- eating

**Comment by passion3394** [comment]
yes, that's what I want. actually, I want to add some adjective for all the classes, such as difficult level.

**Comment by wkentaro** [comment]
That sounds useful.

**Comment by passion3394** [comment]
Yes, I think it's a useful function.

**Comment by caseymcc** [comment]
I need something similar so I am currently working on it, however I have a few questions on structure of the app and need to get some feedback on changes.

First seems that the QT dialog is the holder of all the information which seem a little counter intuitive. I plan to modify the LabelFile to hold all the information and have all the controls reference and alter it. Second the labels are referred to as shapes everywhere, I would like to change that to annotations as I plan to add the ability to add annotations that do not include a shape and may not be a label. That way you could annotate the image with just a value.

I would like to change the shapes to this structure

annotations=
[
    {
        "name": "",
        "type": "", #label, guide, and user configurable types, used to set default attrubutes
        "shapes": #optional
        [
            {
                "type": "", #polygon, circle, ...
                "line_color": [], #optional
                "fill_color": [], #optional
                "points": []
            },...
        ],
        "attributes"
        {
            "value": "",
            etc...
        },
        "children": [] #allow labels to be nested
    }
]

I also plan to create an attribute definition and editor so that the ui can handle some attribute types, something like

annotation_types
{
    "car_label":
    {
        "make":
        {
            "type": "enum_string",
            "enum": ["Chevy", "Ford", etc...]
            "default": 0
        },
        "model":
        {
            "type": "string",
            "default": ""
        },
        "color"
        {
            "type": "color"
            "default": [255, 255, 255, 255]
        }
    },
    "person_label":
    {
        "mood"
        {
            "type": "enum_string",
            "enum": ["happy", "sad", etc...]
            "default": 0
        }
    }
}

**Comment by wkentaro** [comment]
> First seems that the QT dialog is the holder of all the information which seem a little counter intuitive. I plan to modify the LabelFile to hold all the information and have all the controls reference and alter it. 

Yeah. I agree. Currently, that part is not really well organized.

> Second the labels are referred to as shapes everywhere, I would like to change that to annotations as I plan to add the ability to add annotations that do not include a shape and may not be a label

Yeah, you mean something like image captioning, right? Currently, we can annotate image class with `flags`, but an arbitrary text cannot be annotated.
I guess the easiest way start is adding "+" button to the polygon labels dialog, and they popup label annotation window. We can annotate arbitrary text into the `label` field.

**Comment by passion3394** [comment]
Yes, I have done the work with alternative idea: annotate arbitrary text into the label field. after annotation completed, I use a script to parse the label field of each pic.

**Comment by RajatGarg45** [comment]
While trying to generate VOC format dataset, I get following error. Is book class not defined?? Where do I need to define that if it's not defined? Thanks.

  File "labelme2voc.py", line 95, in <module>
    main()
  File "labelme2voc.py", line 83, in main
    label_name_to_value=class_name_to_id,
  File "C:\ProgramData\Anaconda3\envs\labelme\lib\site-packages\labelme\utils\shape.py", line 67, in shapes_to_label
    cls_id = label_name_to_value[cls_name]
KeyError: 'book'

**Comment by passion3394** [comment]
this error means that the dict label_name_to_value does not have key 'book', you should check it.

**Comment by wkentaro** [comment]
Closed via https://github.com/wkentaro/labelme/pull/401

**Comment by glisolana** [comment]
Hi Kentaro,

    I am using LabelMe to annotate our video files. I wonder how to adapt LabelMe for new usage by adding new submenu/items/button. I appreciate your any devise.

Look forward to hearing from you soon,

John
