### ISSUE TITLE
an error caused by non-latin label

### ISSUE THREAD

**Issue by passion3394** [wkentaro/labelme#385]
hi, I try to use the labelme tool to annotate the ocr dataset, and someone annotated some Chinese to the label in his computer, I use the json files and open the labelme tool, the error encountered like the following pic. How to fix this error, please help me, thanks.

![1556279866317](https://user-images.githubusercontent.com/14256482/56806123-999d9780-685d-11e9-89ff-08eb584c9658.jpg)

the json file looks like this:

![1556279943371](https://user-images.githubusercontent.com/14256482/56806192-c6ea4580-685d-11e9-8415-b726d9c0194b.jpg)

**Comment by wkentaro** [comment]
The "label" looks broken, right? Maybe you first need to make sure the `json` file has utf-8 encoding.

**Comment by wkentaro** [comment]
In my env (Python3.6, latest labelme). It can handle non-latin charactors for label.
In below, I replaced `person` to `人`.

![image](https://user-images.githubusercontent.com/4310419/56824736-36a50400-684f-11e9-8f3f-6c628140c6eb.png)

```diff
diff --git a/examples/semantic_segmentation/data_annotated/2011_000003.json b/examples/semantic_segmentation/data_annotated/2011_000003.json
index 59bd87a..6c52d26 100644
--- a/examples/semantic_segmentation/data_annotated/2011_000003.json
+++ b/examples/semantic_segmentation/data_annotated/2011_000003.json
@@ -1,7 +1,7 @@
 {
   "shapes": [
     {
-      "label": "person",
+      "label": "人",
       "line_color": null,
       "fill_color": null,
       "points": [
@@ -172,7 +172,7 @@
       ]
     },
     {
-      "label": "person",
+      "label": "人",
       "line_color": null,
       "fill_color": null,
       "points": [
@@ -386,7 +386,7 @@
       ]
     },
     {
-      "label": "person",
+      "label": "人",
       "line_color": null,
       "fill_color": null,
       "points": [
```

**Comment by passion3394** [comment]
thanks for your experiment, but how to specify the utf-8 encoding?

**Comment by passion3394** [comment]
the json was annotated in a Windows computer, and I check the json in my MAC, maybe that is the cause?

**Comment by passion3394** [comment]
@wkentaro I try to find the solution, someone says the following solution when save the annotation result:

json.dumps(js,ensure_ascii=False)

is that right?

**Comment by wkentaro** [comment]
>  how to specify the utf-8 encoding?

You already have json file, right? But maybe the file does not have utf-8 encoding.
A solution is that you use `nkf` (probably not available on Windows).

```
$ sudo apt install nkf
$ nkf -g your_json.json  # check encoding
UTF-8
$ nkf --in-place -w your_json.json  # encode to utf-8
```

**Comment by wkentaro** [comment]
> the json was annotated in a Windows computer, and I check the json in my MAC, maybe that is the cause?

I think it is an indirect cause, probably on the Windows computer, the json file is annotated with encoding of `shift-jis` or something others.
But `nkf` still works in most case to fix this.

**Comment by wkentaro** [comment]
> json.dumps(js,ensure_ascii=False)
>
> is that right?

I don't know where this `js` comes from..

**Comment by passion3394** [comment]
thanks, I will try your suggestion.

**Comment by passion3394** [comment]
![1556455516018](https://user-images.githubusercontent.com/14256482/56864572-912c9480-69f6-11e9-8702-769b99dff9da.jpg)

I install nkf using brew install nkf. and try to convert the encoding of the json file
the original encoding is EUC-JP, after converting the json encoding to utf-8, the label is not Chinese.

**Comment by passion3394** [comment]
maybe I should convert the encoding in the computer of annotation?

**Comment by wkentaro** [comment]
Yeah that may fix the problem. 
I’m not so familiar the problem of encoding between Windows and macOS. 

An easy way to go is you use macOS for both annotation and analysis.

**Comment by passion3394** [comment]
@wkentaro I have tried to convert the encoding of the json to utf-8 on the computer of annotation, but the error still occurs when I use the converted son

**Comment by wkentaro** [comment]
Hmm, sorry. I don't have any other idea how to fix this.
