### ISSUE TITLE
How change the fillColor of the polygon for the segmentation mask

### ISSUE THREAD

**Issue by essalahsouad** [wkentaro/labelme#387]
@wkentaro 
I'm using this tool to prepare my labels images (knowing that I have one object)
but I need to set the object as white instead of red I tried to edit polygon and change fill color to white but nothing has changed.
this my json file and the label.png (obtained by labelme/cli/json_to_dataset.py)
![Capture du 2019-05-02 16-20-37](https://user-images.githubusercontent.com/34586193/57096997-73b93c80-6d0e-11e9-9708-9df330c64b1f.png)
Any help ??

**Comment by wkentaro** [comment]
You can change the `colormap` here:

https://github.com/wkentaro/labelme/blob/4ec682f9f15983fb9f2b10d9426007b77a2e5fc6/labelme/utils/draw.py#L90

It's something like:
```python
# list of RGB
colormap = np.array([
  [0, 0, 0],
  [1, 0, 0],
  [0, 1, 0],
  [0, 0, 1],
 ...
], dtype=float)
```

**Comment by essalahsouad** [comment]
@wkentaro  thank you
