### ISSUE TITLE
Propose to exclude imageData from JSON annotation file. And use imagePath only for information purposes.

### ISSUE THREAD

**Issue by IlyaOvodov** [wkentaro/labelme#389]
Now if annotation is created in JSON file, image data also is stored in JSON file. Is there any arguments for this decision? I see only disadvantages of this:
1) sometimes it seems to be convenient to handle annotation files manually: create it for new image on the basis of one or may be several other files and then update using LabelMe editor. But now you need to do something with ImageData. Yes, I know about "keep previous" mode, but sometimes handcrafting is more convenient.
2) writing converter to LaberlMe annotation format becomes much more sofisticated.
3) JSON files have huge size (compared with normal json), it makes more time to copy them, more place to store, more difficult to open in text editor.
4) Storing the same information in to places always increase risk of misalignment errors. You can be sure that you annotate JPG file you have selected but you actually annotate only copy stored in json. Sometimes it can become not the same. But other tools that use your annotation  (NNets etc) uses JPG , and it will be hard to catch the mistake.

Last point also refers to imagePath field. Actually then you load JPG image (loadFile function) JPG  and JSON files are paired by filename. But then imagePath is read from JSON. This ambigulity also can cause problems. For instance, I expect that if I rename both JPG and JSON, it will be OK, but suddenly it appeares, that I also have to edit every JSON file.

I propose
1) exclude imageData from JSON at all
2) either exclude imagePath as well, or keep it just for information purposes (for human readiing in JSON), but don't use it in a program.

What do you think about it? Modification seems not to be difficult, I'm going to do it.

**Comment by wkentaro** [comment]
> 1. exclude imageData from JSON at all

You can use `labelme --nodata` to exclude imageData. 

> Last point also refers to imagePath field. Actually then you load JPG image (loadFile function) JPG and JSON files are paired by filename. But then imagePath is read from JSON. This ambigulity also can cause problems. For instance, I expect that if I rename both JPG and JSON, it will be OK, but suddenly it appeares, that I also have to edit every JSON file.

First of all, JSON file and JPEG file is not paired by filename. When loading, labelme always refers to `imagePath` in the JSON file. The case is that the default name of the JSON file is the same basename in the same directory as the JPEG file. However, you can also change the default saving directory with `--output-dir`. So I don't think removing `imagePath` is a good idea.

**Comment by IlyaOvodov** [comment]
> 1. You can use labelme --nodata to exclude imageData.
OK, i didn't see this option and I will use it (hope it works). Nevertheless I still don't see reason to store image data in JSON, moreover, do it by default (without this option)
> First of all, JSON file and JPEG file is not paired by filename
I'm not shure it is the case. When I open dir, app.imageList is filled by names of image files (*.jpg etc.).
When I select image file, app.loadFile is called where file extention is replaced to ".json" [here](https://github.com/wkentaro/labelme/blob/master/labelme/app.py#L1157) and possibly directory is changed as well. Then this JSON file is loaded, and either its imageData or imagePath is used to load image. So the image that I see and label can be quite different then image I've clicked at image list and was going to see. It does not seem clear and robust, especially taking into account that ML tools normally use image data from JPG files, not from JSON.

**Comment by wkentaro** [comment]
First of all, the existence of imageData is because of a historical reason. I agree that it should be disabled as default at some point with a major version release.

**Comment by wkentaro** [comment]
Does it make sense for you?
Or you think we should completely remove that feature?

**Comment by IlyaOvodov** [comment]
As soon as you pointed out to --nodata option, it is not critical. "Historical reason" sounds like aa basolutely valid argument. 
But it general and in perspective - yes, I think it is better to remove it (keepeng backward compatibility to load files with ImageData and ImagePath, possibly with warning). Asking a user to enter a filename to save an annotation into, but loading it by replacing "jpg" file extintion to "json", as well as loading image data not from file user have selected but from different place does't seem to be a good idea.

**Comment by wkentaro** [comment]
Maybe adding consistency check would be fine.

**Comment by marente** [comment]
Just wanted to add that I think the base64 feature makes sense because that way people new to the program don't have to handle two files. As soon as I read through the few examples and saw labelme -h, I realized how to use it for my needs.
Except something offtopic: I guess label-flags aren't supported in the GUI at the moment?!.

**Comment by wkentaro** [comment]
> I guess label-flags aren't supported in the GUI at the moment?!.

Yes, it's supported. https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation#annotation

**Comment by wkentaro** [comment]
> Just wanted to add that I think the base64 feature makes sense because that way people new to the program don't have to handle two files. As soon as I read through the few examples and saw labelme -h, I realized how to use it for my needs.

Thanks. I agree. Maybe I will keep `imageData` for a while.
