### ISSUE TITLE
How to generate ImageData?

### ISSUE THREAD

**Issue by rakhecha42** [wkentaro/labelme#390]
I have to create semantic segmentations for a lot of images for training. Instead of doing all of them manually, I annotated a few manually a trained a UNET model on them to generate semantic segmentations for the lot. They are obviously not very accurate since the training dataset was small.
What I'm looking to do now is use those segmentations to write json files and then use those json files in labelme so that I'll only have to edit the polygons and not actually make all of them from scratch, saving a considerable amount of time.
But, for that, I need to understand how to generate the value for the "ImageData" key in the json file. 
Any help/advice would be appreciated. Thanks.

**Comment by wkentaro** [comment]
See https://github.com/wkentaro/labelme/issues/376
