### ISSUE TITLE
create rotated ellipse

### ISSUE THREAD

**Issue by zfb-blog** [wkentaro/labelme#391]
I've referred issue [#298](https://github.com/wkentaro/labelme/issues/298), and tried to add ellipse. It is successful, but only can get a vertical or horizontal one. Is there a way to rotate it?

I'm defining the bounding rectangle by three points, one define center, second define left border (which can calc the theta of rotation angle), third define the height.

**Comment by wkentaro** [comment]
For annotating a rotated ellipse, I guess you only need 2 points.

1. First point is the center.
2. Second point is half of the longest axis.

So I think you don't need to rotate, but you need to define ellipse like above.

**Comment by RSKothari** [comment]
@wkentaro Could you perhaps provide an example of annotating a rotated ellipse in the repo?

**Comment by ShivaKothuru** [comment]
@zfb-blog I added an ellipse like you. I am now trying to rotate it. could you let me know if you've already implemented rotating an ellipse?
