### ISSUE TITLE
Invalid json

### ISSUE THREAD

**Issue by rakhecha42** [wkentaro/labelme#393]
I have to create semantic segmentations for a lot of images for training. Instead of doing all of them manually, I annotated a few manually and trained a UNET model on them to generate semantic segmentations for the lot. They are obviously not very accurate since the training dataset was small.
Then i created a json file for a sample segmented image which looks like this:

[00001 (copy).txt](https://github.com/wkentaro/labelme/files/3171382/00001.copy.txt)

(i have uploaded it as a text file since uploading json file isn't allowed)

what i'm looking to do is open the original image with this label file in labelme and then edit out the polygons instead of manually making them from scratch, hence saving time.

But, labelme shows that this is an invalid labelfile. Any pointers as to why?

**Comment by rakhecha42** [comment]
The json file reads version as 3.11.2 while the version i'm using currently is 3.14.1. Could that be the cause?

**Comment by rakhecha42** [comment]
This is the full error:

Error opening file
Incorrect padding
Make sure /home/vadmin/seg2json/00001.json is a valid label file.

**Comment by wkentaro** [comment]
It seems the `imageData` is corrupted. https://stackoverflow.com/questions/2941995/python-ignore-incorrect-padding-error-when-base64-decoding/49459036

**Comment by wkentaro** [comment]
You can use `imagePath` by setting `null` to `imageData`.

**Comment by rakhecha42** [comment]
Got it. Thanks a lot. It doesn't seem like as good an idea as it did in the beginning because there's way more vertices to deal with in the polygon in this manner. Now I'll look for a workaround to that.
Thanks for the help though. :)
