### ISSUE TITLE
hope can delete more points than only 1

### ISSUE THREAD

**Issue by cuulrr** [wkentaro/labelme#399]
first of all, many thanks for this cool tool.
I use labelme to annotate body keypoints for CPM data, however I just found that labelme can only undo the last one point. As the keypoint should be in order,  so if I forget one point in the middle, I cannot undo the latest few points to add it back. I just have to delete the relevant json file. that's really of great inconvenience.
please consider this kindly.

**Comment by wkentaro** [comment]
Ok, I will look at this. 

But can you demonstrate me how you annotate human keypoints by a video?

**Comment by cuulrr** [comment]
> Ok, I will look at this.
> 
> But can you demonstrate me how you annotate human keypoints by a video or JSON?

actually， I just utilize labelme to create 15 points in certain order, which individually represent 15 certain parts of human body, and then draw a bbox. That's all information I need.
since the label file of json is very easy to reformat, labelme can easily handle with my annotation job.

**Comment by cuulrr** [comment]
@wkentaro 
hi, I just found that I can use 'Edit Polygon' to move existed point and delete point from the 'Polygon Labels' window. that's really cool~
but if the labels in 'Polygon Labels' window can be draged to sort, so I can insert point in the sequence, things will be totally wonderful for my job.
hope you can take this into consideration, thank you~

**Comment by wkentaro** [comment]
I think you can drag and drop, no?

**Comment by IlyaOvodov** [comment]
I've made enhancement to handle several shapes at once (see #404, #405). Possibly it can simplify this one. 
At least it is better to do this enhancement in coordination with my PR to avoid conflicts.

**Comment by cuulrr** [comment]
> I think you can drag and drop, no?

yeah, I just figured it out, thank you

**Comment by ingramator** [comment]
Have you noticed that the delete polygon functionality doesn't work for deleting a point marker if you have the point tool selected? It seems to work if you reload the software and are in edit polygons mode but never after you select the create point tool. 

In addition, sometimes the delete polygon button is active in the context menu but when you click it you get this:
![image](https://user-images.githubusercontent.com/2769347/60638777-0edfa700-9e63-11e9-8f63-935bcc4a32e1.png)
saying there's 0 polygons.

I may need to create a new issue for this and then we can discuss a new PR to fix it @IlyaOvodov.

**Comment by krishvishal** [comment]
I have the same issue as @ingramator pointed out.

**Comment by wkentaro** [comment]
Can you open an issue for that?
