### ISSUE TITLE
Add per directory config files

### ISSUE THREAD

**Issue by caseymcc** [wkentaro/labelme#402]
Discussion for: https://github.com/wkentaro/labelme/pull/397

I would like to add per directory config files that allow the app to have options when opening label files.

I would like to be able to open a directory (with a config file) that can tell the app where images are located, where labels are located and the ability to add pre/post fixes to the label files.

For instance, I keep my data in a directory structure like this:

```
+-- data_directory
|   +-- data
|    |   +--0
|    |    |   +-- file1.json
|    |    |   +-- file2.json
|    |    |   +-- etc...
|    |   +--1
|    |    |   +-- file10.json
|    |    |   +-- file11.json
|    |    |   +-- etc...
|    |   +-- etc...
|   +-- images
|    |   +--0
|    |    |   +-- file1.png
|    |    |   +-- file2.png
|    |    |   +-- etc...
|    |   +--1
|    |    |   +-- file10.png
|    |    |   +-- file11.png
|    |    |   +-- etc...
|    |   +-- etc...
|   +-- config.yaml <- new per directory config 
```

This directory config:
```
label_directory: data
label_file_postfix: null
label_file_prefix: null
image_directory: images
relative_paths: true
output_directory: null
```

allows me open `data_directory`, the config is loaded and the app then knows to look into `data_directory/images` for images and `data_directory/data` for the label files. The `relative_paths` makes sure that if it reads in `data_directory/images/0/file1.png` that it looks into `data_directory/data/0` for `file1.json` label file (otherwise it would just look in `data_directory/data`). The output_directory option allows it to set the output folder different than the directory the config was in. The `label_file_postfix` and `label_file_prefix` allow you to prefix or post fix the label file compared to the image file, ie. if the image file was `file1.png` and `label_file_postfix: "_labelme"` then the app would look for (or create) a label file called `file1_labelme.json`

**Comment by wkentaro** [comment]
Is this different from below?

```
labelme data_directory/images --output data_directory/labels
```

**Comment by caseymcc** [comment]
yes with this I can just do this, labelme data_directory

**Comment by wkentaro** [comment]
To me, it doesn't look much different. Why you don't want to do like above?
