### ISSUE TITLE
Add group operation for shapes

### ISSUE THREAD

**Issue by IlyaOvodov** [wkentaro/labelme#404]
Now only one shape can be moved (as well as deleted, duplicated and assigned by color) at once.
It would be very useful to be able to select several (or all) shapes and handle (move  etc.) them together. It is required at least then two images are almost the same apart then one is shifted relative to another.

I've made appropriate changes to make this enhancement

**Comment by wkentaro** [comment]
Closed via #412 and https://github.com/wkentaro/labelme/pull/412

**Comment by wkentaro** [comment]
@IlyaOvodov Thank you for the PR. Now I have merged that feature, so can you please quickly check if the current `master` branch works as you expect?

**Comment by IlyaOvodov** [comment]
@wkentaro Yes, I've checked. It seems it works as expected. Thank you for a great tool!
