### ISSUE TITLE
Grouping segmentations

### ISSUE THREAD

**Issue by 1seck** [wkentaro/labelme#414]
Hi there,

sorry I am new to the repo and wondering whether I can group segmentation, like e.g. draw polygons for 
* person 
* shoes

but then also connect (or group) the shoes with the corresponding person so that the output structure contains the information of who is wearing which shoes.

Best regards

**Comment by wkentaro** [comment]
Maybe you can do like below to group annotations:

- person-1
- right-shoe-1
- person-2
- left-shoe-2

**Comment by 1seck** [comment]
That would make it easy without having to add code to structure the labels.
Thank you @wkentaro.
