### ISSUE TITLE
how to delete a point on the edge ?

### ISSUE THREAD

**Issue by thxkew** [wkentaro/labelme#415]
The program can add a point to edge but i have never seen the fuction to delete it. 
How to delete it ?
Thank you

**Comment by wkentaro** [comment]
There is no way of doing this at the moment.

**Comment by hetfmt** [comment]
I have added this feature in the fork on https://github.com/hetfmt/labelme. I tried to merge it into **master** but it failed, and I never got around to try again. I can't remember what the error message was.
Maybe I didn't implement it the right/optimal way, but it seems to work as I want it to.

**Comment by wkentaro** [comment]
Closed via https://github.com/wkentaro/labelme/pull/461
