### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by davechurchill** [wkentaro/labelme#417]
Note: These requests may currently be possible to achieve somehow, but I have not found any documentation to support them:

1. Ability to create and modify flags in the GUI. Currently I can only view the titles of the flags. For example, I'd like to be able to right click in the flags and create new, call it "date" and then give it a date as a string. Similarly, I could create a "description" to give an overall description to the image

2. Ability to define polygon vertices as image dimension percentages instead of pixel values. For example, if one vertex was at (100,100) inside a (200,200) image, it would instead be listed as (0.5, 0.5). This would make it easier to draw the vertices in custom software reading the json file no matter what size the image was being displayed at.

3. Ability to create a single JSON file for all fimages in a directory, rather than 1 file per image

**Comment by wkentaro** [comment]
For 1 and 2, I agree that would be useful and I am positive to include them, but 3 is not clear to me why we need to include it in labelme.

**Comment by wkentaro** [comment]
Please open separated issues if you still need this to make it easier to keep tracking.
