### ISSUE TITLE
labelme2coco.py  labels.txt bounding box coordinates format

### ISSUE THREAD

**Issue by sawhney-medha** [wkentaro/labelme#418]
Hello.
The label .txt file created by labelme2coco.py for each images has bounding box coordinates in what format?
is it xmin,ymin,xmax,ymax or x_center,y_center,width, height?
Thank you for you answer.

**Comment by wkentaro** [comment]
I'm not sure, you can check by trying this function
https://github.com/wkentaro/labelme/blob/master/examples/instance_segmentation/labelme2coco.py#L136

**Comment by sawhney-medha** [comment]
Okay. I will look into it thank you!
