### ISSUE TITLE
labelme_json_to_dataset and rename the label file

### ISSUE THREAD

**Issue by Jingchensun** [wkentaro/labelme#420]
I am going to make a semantic segmentation dataset by myself, but every time i run labelme_json_to_dataset , i will get four file like this:
![image](https://user-images.githubusercontent.com/44359618/59747091-c8a71700-92aa-11e9-984a-202aff0b234f.png)
 
I have to rename the label.png file when i make the dataset.Can i add the name of . json file to the labe.png file when i convert the json to dataset file ? Need I modify code for which python file? Thank you very much

**Comment by Darshan2701** [comment]
Hi, 
Where is this labelme_json_to_dataset file?

**Comment by Jingchensun** [comment]
> Hi,
> Where is this labelme_json_to_dataset file?

it's just a command:
`labelme_json_to_dataset  filename.json`

**Comment by Darshan2701** [comment]
If you could include the steps to reproduce what you are mentioning, could help out,may be!

**Comment by wkentaro** [comment]
@Jingchensun 
> I have to rename the label.png file when i make the dataset.Can i add the name of . json file to the labe.png file when i convert the json to dataset file ? 

```bash
for f in *.json; do
    labelme_json_to_dataset $f
    base=$(echo $f | sed 's/\.json//g')
    mv ${base}_json/label.png ${base}.png
done
```

@Darshan2701 
> Where is this labelme_json_to_dataset file?

https://github.com/wkentaro/labelme/blob/master/labelme/cli/json_to_dataset.py

**Comment by Jingchensun** [comment]
> @Jingchensun
> 
> > I have to rename the label.png file when i make the dataset.Can i add the name of . json file to the labe.png file when i convert the json to dataset file ?
> 
> ```shell
> for f in *.json; do
>     labelme_json_to_dataset $f
>     base=$(echo $f | sed 's/\.json//g')
>     mv ${base}_json/label.png ${base}.png
> done
> ```
> 
> @Darshan2701
> 
> > Where is this labelme_json_to_dataset file?
> 
> https://github.com/wkentaro/labelme/blob/master/labelme/cli/json_to_dataset.py

Thank you very much! it works!

**Comment by wkentaro** [comment]
:+1:
