### ISSUE TITLE
[Suggestion] Add support for import existing annotation

### ISSUE THREAD

**Issue by coffeehat** [wkentaro/labelme#421]
Hello, i really appreciate your work, the software really helps me a lot.
There's some suggestions:

1. Add support for **import existing annotation**.
In some cases annotations are firstly generated by beginners or primary algorthms, then inspected or corrected by the experienced. I work for medical image processing. In my case medial annotations labeled by various workers need to be inspected by experienced doctors to ensure the accuracy. This requires the support to import annotation file of others and modify them.

2. Add **Spline Curves** for segmentation annotation
To get smoothed boundary. e.g. organ, cell boundaries are not rigid.

**Comment by wkentaro** [comment]
> 1. Add support for import existing annotation.

I think this is already supported, and you can modify the existing annotations by adding new points.
Actually, the feature of deleting points is not supported currently.

> 2. Add Spline Curves for segmentation annotation

Maybe this kind of process would be a post-process after the annotations. However, I think that would be useful if we can visualize the segmentation after the post-process (e.g., smoothed mask) for verification by the annotator.

**Comment by coffeehat** [comment]
Yes I wasn't aware of how to import json at that moment, now I know it.
So do you consider deleting points as new feature? it's really useful in some conditions

As for spline curves, post-process is really a good idea.

**Comment by vpapaioannou** [comment]
How is the import done exactly?

Once it happened automatically but since then not again.
I have every image in a separate folder and in a subfolder
I have the previous json files.

Thanks.
