### ISSUE TITLE
Can We Run labelme on Google Colab ?

### ISSUE THREAD

**Issue by galoisgroupcn** [wkentaro/labelme#422]
Hi All,

Can We Run labelme on Google Colab ? Or does labelme only supports local machine ?

Thanks,

Amber
@wkentaro @mpitid @mbuijs

**Comment by wkentaro** [comment]
I don’t know. I never used Google Colab.

**Comment by MohnishJain** [comment]
Even i want to know how to run label me on google colab?

**Comment by Sailex-Salam** [comment]
Labelme can't be used in google colab
