### ISSUE TITLE
How does labelme calculates imageData?

### ISSUE THREAD

**Issue by mridul111998** [wkentaro/labelme#423]
I am trying to automate some annotation task and generating a JSON file for each image. I tried to generate image data for each image using the following code but labelme is showing an error. My code for generating image data is 
```
def img_arr_to_b64(filename):
    img_arr = cv2.imread(filename)
    img_pil = Image.fromarray(img_arr)
    f = io.BytesIO()
    img_pil.save(f, format='JPEG')
    img_bin = f.getvalue()
    if hasattr(base64, 'encodebytes'):
        img_b64 = base64.encodebytes(img_bin)
    else:
           img_b64 = base64.encodestring(img_bin)
    return img_b64
```
The error which I am getting is 
```Error opening file
Incorrect padding
Make sure /home/abc.json is a valid label file.
```
I have seen [this](https://github.com/wkentaro/labelme/issues/376) issue but could not solve my problem.

**Comment by AmitMalka94** [comment]
Hi,
I am also trying to generate labelme json files and I got stuck when creating the imageData field. I see here many ways in the other direction of reading this field and not about creating it. Would appreciate help. Thanks

**Comment by wkentaro** [comment]
If you have the corresponding image file, you can set `"imageData": null, "imagePath": "YOUR_IMAGE.jpg"` in the json to avoid getting troubles with `imageData`.

**Comment by Sarouch** [comment]
> If you have the corresponding image file, you can set `"imageData": null, "imagePath": "YOUR_IMAGE.jpg"` in the json to avoid getting troubles with `imageData`.

Hi @wkentaro, do you know how to change the name of "imagePath" in the json files ? I changed the names of my data so I can't open them on labelme anymore.
