### ISSUE TITLE
3.16.1

### ISSUE THREAD

**Issue by alexmyczko** [wkentaro/labelme#428]
--version still says 3.15.1...

**Comment by wkentaro** [comment]
Where? How to reproduce?

<img width="674" alt="Screen Shot 2019-06-27 at 13 48 48" src="https://user-images.githubusercontent.com/4310419/60267524-55bd2200-98e2-11e9-8581-27a8e254ea94.png">

**Comment by alexmyczko** [comment]
oops my fault, very sorry:

```
root@phd-sid:/var/www/debian# which labelme
/usr/local/bin/labelme
root@phd-sid:/var/www/debian# /usr/bin/labelme
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
root@phd-sid:/var/www/debian# /usr/bin/labelme
root@phd-sid:/var/www/debian# rm
root@phd-sid:/var/www/debian# rm /usr/local/bin/labelme
root@phd-sid:/var/www/debian# labelme --version
labelme 3.16.1
```

meanwhile there's a debian/ubuntu package:
http://phd-sid.ethz.ch/debian/labelme/

**Comment by wkentaro** [comment]
Ok fine.
