### ISSUE TITLE
Video annotation example

### ISSUE THREAD

**Issue by suravijayjilla** [wkentaro/labelme#430]
Hi,
Sorry for make you angry.
But I am new to this field. so please help me on this concepts.
Unable to understand the concept of video annotation.
I am using video_to_image.py to convert video frames to image file. Then I run labelme to label the images.
Then I have no idea to convert that images to video.
Finally if I run the final video it will show the created label in that video?

**Comment by wkentaro** [comment]
> Then I have no idea to convert that images to video.

Hmm. It's a kind of out-of-scope of this repo. There is information on the internet if you search on Google.
https://stackoverflow.com/questions/44947505/how-to-make-a-movie-out-of-images-in-python/44948030

Anyway, you can run something like below.

```bash
python video_to_images your_video.mp4

echo "dog\nperson" > labels.txt
labelme your_video/ --labels labels.txt

./labelme2voc.py your_video your_video_voc --labels labels.txt

pytohn images_to_video -i 'your_video_voc/SegmentationClassVisualization/*.jpg' out.mp4 --fixlowfps
```
Using my script: https://github.com/wkentaro/dotfiles/blob/master/local/bin/images_to_video

**Comment by suravijayjilla** [comment]
Hi,

If I try to execute this command
labelme your_video/ --labels labels.txt
i am facing the below issue,

labelme C:\Users\Admin\Downloads\video.mp4 --labels labels.txt

error:
https://user-images.githubusercontent.com/48546629/60431759-2c6fff00-9c1e-11e9-96da-c15d76289a69.png

Please help me on this.

**Comment by wkentaro** [comment]
See https://github.com/wkentaro/labelme/tree/master/examples/video_annotation#how-to-convert-a-video-file-to-images-for-annotation

**Comment by suravijayjilla** [comment]
Hi,
Thanks for your reply.
Everything is working fine. But last command does not work properly.

When i run this command
PS C:\Users\Admin\Downloads\labelme-master> .\images_to_video.py -i '.\video_voc_dataset\SegmentationClassVisualization\
*.jpg' C:\Users\Admin\Downloads\output_video.mp4 --fixlowfps

command run successfully, but the video was not created in this path.

**Comment by wkentaro** [comment]
I don't know how to fix it. Maybe you need to adapt the script for Windows, which I've never tried.

**Comment by annemacena** [comment]
> > Then I have no idea to convert that images to video.
> 
> Hmm. It's a kind of out-of-scope of this repo. There is information on the internet if you search on Google.
> https://stackoverflow.com/questions/44947505/how-to-make-a-movie-out-of-images-in-python/44948030
> 
> Anyway, you can run something like below.
> 
> ```shell
> python video_to_images your_video.mp4
> 
> echo "dog\nperson" > labels.txt
> labelme your_video/ --labels labels.txt
> 
> ./labelme2voc.py your_video your_video_voc --labels labels.txt
> 
> python images_to_video -i 'your_video_voc/SegmentationClassVisualization/*.jpg' out.mp4 --fixlowfps
> ```
> 
> Using my another script: https://github.com/wkentaro/dotfiles/blob/master/local/bin/images_to_video

images_to_video's link unavailable
