### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by anwar-kamil** [wkentaro/labelme#431]
json to dataset for multiple or bulk images. Any other suggestion?

**Comment by wkentaro** [comment]
You can check this. https://github.com/wkentaro/labelme/issues/420#issuecomment-503723238

**Comment by anwar-kamil** [comment]
Thank you for the reply.

But what I want to achieve is that the label.png should have the same colour codings for same labels. What the application is doing right now is that for e.g. it gives green colour to an object with the label car but if the same label (car) is repeated in another image, it gives red colour for e.g. which makes the label.png not suited to be re-used for model training. 

Anything helpful to resolve this issue would be highly valued. Thanks in advance.

**Comment by wkentaro** [comment]
Have you checked the advanced examples listed here? https://github.com/wkentaro/labelme#usage
