### ISSUE TITLE
Save json file without imagedata

### ISSUE THREAD

**Issue by nathannzw** [wkentaro/labelme#437]
Hi i’m working on automated annotation and would like to be able to save a json file without the imageData. How do i do this? i saw the —nodata command but not sure if it’s related. thanks. Or if there is no imagedata what do i fill in in the json file?null?

**Comment by JordanMakesMaps** [comment]
@nathannzw  were you able to do this? I'm looking at converting binary masks in the form on numpy arrays into a format that can be read directly into labelme so they can be edited manually.

What exactly is imageData? Is it literally the image data encoded?
