### ISSUE TITLE
[Command not found] labelme_draw_json and labelme_json_to_dataset

### ISSUE THREAD

**Issue by boycao** [wkentaro/labelme#438]
Hi there,
I am running labelme_draw_json and labelme_json_to_dataset on my mac, but neither of these two work. Both show a " Command not found ". Cloud you help me with this?
I installed through homebrew and command labelme works fine. Only these two(for now) do not work.

**Comment by wkentaro** [comment]
It's not supported. You can use `pip` to install full version of labelme.

**Comment by boycao** [comment]
> It's not supported. You can use `pip` to install full version of labelme.

Cool. Thanks!
