### ISSUE TITLE
[Request] Select from labels list instead of creating new every time

### ISSUE THREAD

**Issue by mrgloom** [wkentaro/labelme#44]
It will great if we can select from labels list instead of creating new label every time like in `labelImg`

![gui](https://user-images.githubusercontent.com/4003908/33013099-e2f5c08e-cdf3-11e7-8869-1bff50b9c148.PNG)

Predefined classes are stored in `predefined_classes.txt` files that is near binary file.

**Comment by psabour** [comment]
yes, that would be great.

**Comment by ad-si** [comment]
I'd also make it possible to specify the labels via a cli flag: `labelme --labels=dog,person,cat file.jpg`

**Comment by wkentaro** [comment]
https://github.com/wkentaro/labelme/pull/76 will resolve this issue.
