### ISSUE TITLE
How to solve the 'UnicodeEncodeError' problem?

### ISSUE THREAD

**Issue by cpuxzb** [wkentaro/labelme#441]
The pictures are labeled with labelme in mac.I use ‘labelme_json_to_dataset <filename>.json’ in windows and encounter problems as following screenshot.
The problem screenshot is as follows：https://github.com/cpuxzb/Question/blob/master/problem.JPG

**Comment by wkentaro** [comment]
Maybe you should check the version of Python and Labelme on Windows to make sure this is a bug of the current labelme.

**Comment by cpuxzb** [comment]
> Maybe you should check the version of Python and Labelme on Windows to make sure this is a bug of the current labelme.
I  use the python2.7 and didn‘t find out the solution.

**Comment by cpuxzb** [comment]
I have solved the problem.
In conclusion,the question is ‘(UnicodeEncodeError 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128))’.
The solution is to add the following code in the problematic py file.
import sys
reload(sys)   
sys.setdefaultencoding('utf8')

**Comment by YokkaBear** [comment]
Another Solution: Change the language all the way to the image into English.
