### ISSUE TITLE
bug in app.py editLabel function

### ISSUE THREAD

**Issue by xieclgithub** [wkentaro/labelme#445]
the assignment shape.label = text and shape.flags = flags should be assigned at the function of "labelItemChanged" after the "if label != shape.label: ", I find this because I set up the color of specific label for my own labelme and it didn't work

**Comment by xieclgithub** [comment]
It may delete the assignment of shape.label = text and it works

**Comment by wkentaro** [comment]
Sorry, but I'm not sure how to reproduce this.

**Comment by xieclgithub** [comment]
In script app.py, I think the expression below `if label != shape.label:` in function `labelItemChanged` is never be executed because the assignment `shape.label = text` in function  `editLabel`  update the value of shape.label
