### ISSUE TITLE
problem viewing mask using labelme_json_to_dataset

### ISSUE THREAD

**Issue by amitnativ** [wkentaro/labelme#45]
Hi.
the utility looks great. 
however, I was unable to view the mask saved to the *.json file.

I tried running
labelme_json_to_dataset <my file>, but got the following messege:
'labelme_draw_json' is not recognized as an internal or external command,
operable program or batch file.

I ran the anaconda installation and the GUI works fine.

Thanks

**Comment by USTC-SQQ** [comment]
hello, I meet the same problem with you, have you solved the problem?

**Comment by amitnativ** [comment]
Unfortunately no...

**Comment by USTC-SQQ** [comment]
okay, thanks

**Comment by wkentaro** [comment]
Do you run on Windows? Actually, I never run `labelme` on Windows, because I only have mac or Ubuntu os.

**Comment by amitnativ** [comment]
Yes. On windows

**Comment by XiaotianM** [comment]
In windows, you may can save these scripts as *.py, and in the path of these scripts, run and you may get the results

**Comment by wkentaro** [comment]
@XiaotianM Can your solution be automated by `setup.py`?

**Comment by XiaotianM** [comment]
@wkentaro , No, It's  just a temporary solution for windows

**Comment by wkentaro** [comment]
@XiaotianM Thanks.

**Comment by wkentaro** [comment]
I think https://github.com/wkentaro/labelme/commit/91154a74e3584967c3e531ecb0078d2a1179366f fixes this issue.
Could someone try it?

**Comment by wkentaro** [comment]
Please request for reopening if you still have the same/similar issue.

**Comment by DougStanley14** [comment]
I got this to work once
