### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by ankit-gitscience** [wkentaro/labelme#453]
I'm getting the below error: Please help

C:\Users\Ankit Srivastava\Desktop\DataAnnot>labelme_json_to_dataset car1.json -o car_json

[33m[WARNING][0m This script is aimed to demonstrate how to convert theJSON file to a single image dataset, and not to handlemultiple JSON files to generate a real-use dataset. ([1mjson_to_dataset.py[0m:15)
Traceback (most recent call last):
  File "C:\Users\Ankit Srivastava\AppData\Local\Programs\Python\Python36\Scripts\labelme_json_to_dataset-script.py", line 11, in <module>
    load_entry_point('labelme==3.16.2', 'console_scripts', 'labelme_json_to_dataset')()
  File "c:\users\ankit srivastava\appdata\local\programs\python\python36\lib\site-packages\labelme\cli\json_to_dataset.py", line 60, in main
    utils.lblsave(osp.join(out_dir, 'label.png'), lbl)
  File "c:\users\ankit srivastava\appdata\local\programs\python\python36\lib\site-packages\labelme\utils\_io.py", line 17, in lblsave
    lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
  File "c:\users\ankit srivastava\appdata\local\programs\python\python36\lib\site-packages\PIL\Image.py", line 1712, in putpalette
    data = bytes(data)
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by uzck** [comment]
I solve the the same problem in ubuntu18.04 and Python version is 3.6.0 Pillow version is 6.1.0
I found the reason is python3 builtins function bytes() now receive a list as input
in PIL/Image.py Line:1712 `data = bytes(data)` where the data is np.ndarray 
so add a convert will help like  `data = data.tolist()`

**Comment by ahuxjz** [comment]
> I solve the the same problem in ubuntu18.04 and Python version is 3.6.0 Pillow version is 6.1.0
> I found the reason is python3 builtins function bytes() now receive a list as input
> in PIL/Image.py Line:1712 `data = bytes(data)` where the data is np.ndarray
> so add a convert will help like `data = data.tolist()`

hello,I didn't find “data = bytes(data）” in line 1712，

**Comment by ahuxjz** [comment]
> 我在ubuntu18.04中解决了相同的问题，Python版本是3.6.0，枕头版本是6.1.0，
> 我发现原因是python3内置函数bytes（）现在
> 在PIL / Image.py Line：1712 `data = bytes(data)`中收到输入列表数据是np.ndarray，
> 所以添加转换将有助于 `data = data.tolist()`

it didn't work

**Comment by solved1** [comment]
> data.tolist()

Thanks, this fixed the issue for me.
