### ISSUE TITLE
how to fix the category  number of the annotation

### ISSUE THREAD

**Issue by singaloo** [wkentaro/labelme#454]
I would like to ask how to fix the category of the annotation (indicated by numbers).  When some pictures do not have a certain category, the number of categories will be rearranged.
![image](https://user-images.githubusercontent.com/52092581/61675123-9bc2a580-ad29-11e9-9230-6bacc6971545.png)
![image](https://user-images.githubusercontent.com/52092581/61675138-a8df9480-ad29-11e9-96b8-50d3388cb9b3.png)

**Comment by wkentaro** [comment]
See https://github.com/wkentaro/labelme/issues/282

**Comment by beizhengren** [comment]
@singaloo Hi, have you solve the probelm?
