### ISSUE TITLE
Add shortcut for ‘Add Point to Edge’

### ISSUE THREAD

**Issue by stormlands** [wkentaro/labelme#459]
Hello, i really appreciate your work, the software really helps me a lot.

I want to add  shortcut for ‘Add Point to Edge’, but it does not work. The mouse needs to be in a specific location, how can I add shortcut?

**Comment by wkentaro** [comment]
With https://github.com/wkentaro/labelme/pull/468 you can use `Ctrl+Shift+P` to add a new point while you are selecting an edge of a polygon.

**Comment by elepherai** [comment]
@wkentaro Hi, Ctrl+Shift+P is not working on Windows.

Version: 3.16.3
