### ISSUE TITLE
drag point outside the image area  will crash

### ISSUE THREAD

**Issue by maoxianfei** [wkentaro/labelme#464]
![GIF](https://user-images.githubusercontent.com/17768860/62849963-1e7cc600-bd14-11e9-9640-c26a0cce505b.gif)

error:
min() arg is an empty squence

env:
window 10
Python 3.7.3
labelme                3.16.2

**Comment by wkentaro** [comment]
I finally managed to test this on Windows, and I reproduced this problem.
https://github.com/wkentaro/labelme/pull/467 should fix this problem. Please test it once it is merged.

**Comment by wkentaro** [comment]
Released 3.16.3, so please test it if it fixed this problem.
```
pip install 'labelme==3.16.3' --no-cache-dir
```

**Comment by wkentaro** [comment]
Thanks for report. This is same issue as https://github.com/wkentaro/labelme/issues/398, so please follow it.
