### ISSUE TITLE
How to supress add change_color labels 

### ISSUE THREAD

**Issue by RCC-GIT** [wkentaro/labelme#470]

**Comment by RCC-GIT** [comment]
I am working with anaconda/Windows , I don't see any way to suprress or change the color of the labels 
Add is easy , Ok , but I don't need all of the predefined ones .
I would like also to have a specific color per label .
Let me know

**Comment by wkentaro** [comment]
Actually, suppressing is not supported. For class-specific color, https://github.com/wkentaro/labelme/issues/386 is the issue for that.
