### ISSUE TITLE
did anybody try to build it on xcode(for iOS)? 

### ISSUE THREAD

**Issue by dedoogong** [wkentaro/labelme#476]
I've wanted to enjoying labeling using my big iPad while i'm on the way to my office. 
I think pythonista or pyqt5 can be built for iOS, so it seems to be OK to run labelme on iOS.
But I have no mac book, so if anybody kindly can try this, and share your results, 
it must be amazing~!

Thank you.

**Comment by 7LFB** [comment]
Recently I meet the same problem. I also want to label the large data using iPad. Have you solved the problem? @dedoogong
