### ISSUE TITLE
Video annotation saving on custom data

### ISSUE THREAD

**Issue by abhigoku10** [wkentaro/labelme#477]
@latticetower @ompugao @rogerthat94 @serycjon   THanks for the wonderful feature , i have few queries 
1. I have followed the instructions mentioned in the example which works fine 
2. on custom video i am able to convert it to the images but when i start the annotation in first frame how will is progress it to the second frame and n consecutive frames

**Comment by serycjon** [comment]
Are you asking how to navigate to the next video frame? Or rather how to automatically copy the current annotation into the next frame?

**Comment by abhigoku10** [comment]
@serycjon how to automatically copy the current annotation into the next frame since i could not find any command or steps

**Comment by serycjon** [comment]
I haven't tested it, but I think holding ctrl+shift when clicking to the next frame should work. Or you can toggle "keep prev" mode with ctrl+P, then the annotations should be copied automatically, I think.

**Comment by abhigoku10** [comment]
i tried to use both the methods was not successfull in that , how was the example video generated ?? during saving
