### ISSUE TITLE
How to fix the index of same label among different images?

### ISSUE THREAD

**Issue by beizhengren** [wkentaro/labelme#479]
About semantic segmentation.
Here, I have 3 images, naming image1, image2, image3.
There are 2 classes in the 3 images in total, respectively being "apple", "pea".
- 1.class of image:
```
image1:"apple", "pea"
image2:"pea"
image3:"apple", "pea"
```
And now,  using **json_to_dataset.py** to generate 3 label.png, I found the index is not same for the same class.
- 2.index of image:
```
image1: apple-->1,  pea-->2
image2: pea-->1
image3: pea-->1, apple-->2

```
As above showing, In image1, apple's index is 1, pea's index is 2.
So, in image2, pea's index should be 2, and in image3 the index of apple and pea should be the same with image1.
But, I got index of pea is 1 in image2, image3, and of apple is 2 in image3.
How should I to fix the index of label.png generated by json_to_dataset.py?
Thanks!

**Comment by beizhengren** [comment]
I've got it. Thank you  [lalelme2voc](https://github.com/wkentaro/labelme/blob/master/examples/semantic_segmentation/labelme2voc.py)

**Comment by leedoge** [comment]
> I've got it . In lalelme2voc.
> Thank you!

hello,i have the same problem,could you please tell me how to slove it?thank  you very much!

**Comment by beizhengren** [comment]
Hello@leedoge ,
you should run [./labelme2voc.py data_annotated data_dataset_voc --labels labels.txt](https://github.com/wkentaro/labelme/tree/master/examples/semantic_segmentation)
