### ISSUE TITLE
How to use the json file? which framework can train this json.

### ISSUE THREAD

**Issue by lpnueg4** [wkentaro/labelme#48]
Help me, thanks!

**Comment by wkentaro** [comment]
I usually convert the JSON file to set of RGB image and label file, with [`labelme_json_to_dataset` script](https://github.com/wkentaro/labelme/blob/master/scripts/labelme_json_to_dataset).
And then, I use the `image.jpg` and `label.png` to train segmentation network, for example [FCN](https://www.cv-foundation.org/openaccess/content_cvpr_2015/html/Long_Fully_Convolutional_Networks_2015_CVPR_paper.html) with [Chainer implementation of it](https://github.com/wkentaro/fcn).
The concrete example of this usage is shown here (the data loading class for Chainer): https://github.com/wkentaro/fcn/blob/master/examples/apc2016/datasets/jsk.py
I corrected segmentation dataset for a robotics challenge.

**Comment by lpnueg4** [comment]
@wkentaro many thanks! I will try it.
