### ISSUE TITLE
questions on labeltococo.py

### ISSUE THREAD

**Issue by hikalomoni** [wkentaro/labelme#487]
"annotations": [{"id": 0, "image_id": 0, "category_id": 1, "segmentation": [[215.94202898550722, 101.20289855072463, 797.1014492753623, 165.695652173913, 798.5507246376811, 270.04347826086956, 766.6666666666666, 330.9130434782608, 225.3623188405797, 276.5652173913043], [181.15942028985506, 422.94202898550725, 183.0, 449.0, 394.0, 449.0, 394.0, 449.0], [255.79710144927535, 0.4782608695652044, 255.0724637681159, 6.999999999999986, 792.0289855072463, 67.86956521739128, 799.0, 56.0, 799.0, 0.0, 256.0, 0.0]], "area": 121366.0, "bbox": [181.0, 0.0, 619.0, 450.0], "iscrowd": 0}
as is shown above, there are TWO segmentations in one image, but the code generates only ONE bbox, why is that? 
is there something incorrect with the code or something wrong with my labelling?
Thank you very much

**Comment by wkentaro** [comment]
You are using 'instance_segmentation' example, right? In that case, you need to label like "person-1", "person-2".

**Comment by deep-practice** [comment]
@wkentaro 假如第一张图片标记了person1 person2，那第二张图片是person1 person2还是person3 person4?

**Comment by wkentaro** [comment]
Well, this issue is relatively out-of-date. Now, labelme supports instance annotation by "group id". See examples in examples/instance_segmentation.

**Comment by wkentaro** [comment]
But the answer to your question is that you can annotate person-1, person-2 for the second image, if I understood correctly.
