### ISSUE TITLE
Is there a way to convert coco annotation file to labelme annotation files?

### ISSUE THREAD

**Issue by XiaohangZhan** [wkentaro/labelme#490]
I want to load LVIS annotation file (in the same format as coco) to labelme and modify the instance segmentations. It should be the inverse process of examples/instance_segmentation/labelme2coco.py.

Is there such a script?

**Comment by wkentaro** [comment]
No, but sounds useful.

**Comment by cm107** [comment]
I made a converter for COCO to Labelme.
https://github.com/cm107/annotation_utils/blob/master/build/lib/annotation_utils/converter/labelme_coco_converter.py

You could do something similar for converting COCO to Labelme as well.
You would have to make assumptions though. For example, all Labelme point annotations are keypoints, all rectangles are bounding boxes, and all polygons are segmentation. You would also have to assume that all point labels are contained in either a rectangle or polygon.

Labelme Parser: https://github.com/cm107/annotation_utils/blob/master/build/lib/annotation_utils/labelme/annotation/labelme_annotation.py
COCO Parser: https://github.com/cm107/annotation_utils/blob/master/build/lib/annotation_utils/coco/annotation/coco_annotation.py

**Comment by travishsu** [comment]
Here is link to my script to covert COCO to LabelMe

https://gist.github.com/travishsu/6efa5c9fb92ece37b4748036026342f6

**Comment by travishsu** [comment]
https://gist.github.com/travishsu/6efa5c9fb92ece37b4748036026342f6

**Comment by Noiredd** [comment]
@WandererGuy Nice script, doesn't even read COCO data 👎
