### ISSUE TITLE
Possibility of alignment when one edge of polygon matches with the other edge of neighbour polygon? 

### ISSUE THREAD

**Issue by vigneshrajap** [wkentaro/labelme#491]
It's a great annotation tool overall. 

But there seems to be an issue with the accuracy of labeling with the neighboring objects. When one object is labeled by a polygon then another nearby object in the image is set to be labeled with another polygon, there is no indication whether both the nearby polygons aligned perfectly to each other.

Due to this, there is either an overlap of one class over another or there is an empty space containing a small set of pixels that automatically belongs to the class "_background_" but it should belong to one of the neighboring classes instead.

**Comment by ZhangIceNight** [comment]
Can someone teach me how to solve this problem？
