### ISSUE TITLE
Encountered `IndexError: list index out of range` and sudden shutdown of labelme

### ISSUE THREAD

**Issue by AsserAboElkhair** [wkentaro/labelme#498]
I got this error using your tool:
`RuntimeWarning: invalid value encountered in double_scalars
  return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
Traceback (most recent call last):
  File "c:\users\asser\anaconda3\envs\labelme\lib\site-packages\labelme\widgets\canvas.py", line 253, in mouseMoveEvent
    elif shape.containsPoint(pos):
  File "c:\users\asser\anaconda3\envs\labelme\lib\site-packages\labelme\shape.py", line 198, in containsPoint
    return self.makePath().contains(point)
  File "c:\users\asser\anaconda3\envs\labelme\lib\site-packages\labelme\shape.py", line 222, in makePath
    path = QtGui.QPainterPath(self.points[0])
IndexError: list index out of range`

This happens when there is an empty polygon in the JSON file i.e with empty `points` list like this:
`{
      "label": "plant",
      "line_color": null,
      "fill_color": null,
      "points": [],
      "shape_type": "polygon",
      "flags": {}
}`

**Comment by AsserAboElkhair** [comment]
Since labeling by diagonals is boring work, I built a tool to automatically draw the diagonals around the object then write the diagonal to a JSON file with the same format as your label tool to annotate the objects manually, I encountered this problem but then after tracing my tool sometimes skip very small objects but it doesn't skip it totally it only skip the points, I thought it wouldn't make a problem but it made your tool crash if only there's empty polygon.

I suggest to handle this in Labelme, I already handled it in my tool, but you can add an `if condition` to check if the length of the polygon points is more than one at the error location.

**Comment by smilexin** [comment]
I met the same question when remove the selected point

**Comment by smilexin** [comment]
> Since labeling by diagonals is boring work, I built a tool to automatically draw the diagonals around the object then write the diagonal to a JSON file with the same format as your label tool to annotate the objects manually, I encountered this problem but then after tracing my tool sometimes skip very small objects but it doesn't skip it totally it only skip the points, I thought it wouldn't make a problem but it made your tool crash if only there's empty polygon.
> 
> I suggest to handle this in Labelme, I already handled it in my tool, but you can add an `if condition` to check if the length of the polygon points is more than one at the error location.

@AsserAboElkhair  If you can share how to workaround this?

**Comment by wkentaro** [comment]
I'm not willing to support empty points field, so closing this.
