### ISSUE TITLE
Unexpected order or bounding box point 

### ISSUE THREAD

**Issue by ArtificialNotImbecile** [wkentaro/labelme#507]
When annotate the image using `create rectangle` . The order of the points is `[[xmin, ymin], [xmax, ymax]]` if I draw the box from top left corner to bottom right corner. But this is problematic if I draw the box from bottom right to top left corner.

**Comment by wkentaro** [comment]
Please do like this https://github.com/wkentaro/labelme/blob/1d6ea6951c025a7db0540c7eac77577bc1507efa/examples/bbox_detection/labelme2voc.py#L103-L105
