### ISSUE TITLE
json2mask

### ISSUE THREAD

**Issue by jmzelectronica** [wkentaro/labelme#508]
How can I convert the file json to mask for semantic segmentation?

**Comment by wkentaro** [comment]
This one didn't work?
https://github.com/wkentaro/labelme/tree/master/examples/tutorial#convert-to-dataset

**Comment by lneeraj97** [comment]
I have a similar question but I did not want to create another issue for it, so I'm posting it here. My images are in grayscale, and when I run `python ./labelme2voc.py data_annotated data_annotated_voc --labels labels.txt --no-data`, it throws an error `AssertionError: rgb must be 3 dimensional`

```
Traceback (most recent call last):
  File "./labelme2voc.py", line 105, in <module>
    main()
  File "./labelme2voc.py", line 96, in main
    img=imgviz.rgb2gray(img),
  File "/home/neeraj/miniconda3/envs/ml/lib/python3.7/site-packages/imgviz/color.py", line 19, in rgb2gray
    assert rgb.ndim == 3, 'rgb must be 3 dimensional'
AssertionError: rgb must be 3 dimensional

```
How do I make it work for grayscale images?

**Comment by wkentaro** [comment]
Please create new issue.

**Comment by asifahmed1997bd** [comment]
> 

same problem. have u found any way to solve it .
