### ISSUE TITLE
Error in installation with ubuntu

### ISSUE THREAD

**Issue by wangzhengheu** [wkentaro/labelme#51]
When I use these commands to install the application, error. How to solve this problem？

Ubuntu
sudo apt-get install python-qt4 pyqt4-dev-tools
sudo pip install labelme

root@wangzheng:~# pip install labelme
The directory '/home/wangxheng/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/wangxheng/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting labelme
  Downloading labelme-2.6.4.tar.gz (201kB)
    100% |████████████████████████████████| 204kB 99kB/s 
Requirement already satisfied: matplotlib in /usr/local/lib/python2.7/dist-packages (from labelme)
Requirement already satisfied: Pillow>=2.8.0 in /usr/local/lib/python2.7/dist-packages (from labelme)
Requirement already satisfied: scipy in /usr/local/lib/python2.7/dist-packages (from labelme)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from labelme)
Requirement already satisfied: PyYAML in /usr/lib/python2.7/dist-packages (from labelme)
Requirement already satisfied: numpy>=1.7.1 in /usr/local/lib/python2.7/dist-packages (from matplotlib->labelme)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python2.7/dist-packages (from matplotlib->labelme)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from matplotlib->labelme)
Requirement already satisfied: subprocess32 in /usr/local/lib/python2.7/dist-packages (from matplotlib->labelme)
Requirement already satisfied: python-dateutil>=2.0 in /usr/local/lib/python2.7/dist-packages (from matplotlib->labelme)
Requirement already satisfied: backports.functools-lru-cache in /usr/local/lib/python2.7/dist-packages (from matplotlib->labelme)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python2.7/dist-packages (from matplotlib->labelme)
Installing collected packages: labelme
  **Running setup.py install for labelme ... error**
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2IkUCH/labelme/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-46kHpg-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    Please install pyrcc5 command.
    (See https://github.com/wkentaro/labelme.git)
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2IkUCH/labelme/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-46kHpg-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-2IkUCH/labelme/

**Comment by wkentaro** [comment]
See the error message:

```
Please install pyrcc5 command.
(See https://github.com/wkentaro/labelme.git)
```

**Comment by wkentaro** [comment]
Maybe you installed both PyQt5 and PyQt4.
In that case, you should install `pyqt5-dev-tools`, because the installation program assumes that you want to use PyQt5.

**Comment by wangzhengheu** [comment]
@wkentaro 

I hsve solved the problem according to what you said. Thank you very much!

**Comment by wkentaro** [comment]
:+1:
