### ISSUE TITLE
Feature Request: Delete the image not labeled

### ISSUE THREAD

**Issue by kchaitanyabandi** [wkentaro/labelme#515]
Hi wkentaro,

First off, thanks a lot for this amazing labeling tool you built. It's super intuitive and easy to label almost anything.

I am currently working on drawing polygons for segmentation. One feature I want to request is to have the option of deleting the image that is not labeled (basically, assuming it has not been labeled because the image is useless). This will help me sort out files that I labeled today and copy them to another location and since the unlabeled data files have been deleted, I can focus on the remaining set of images for the next day.

Please let me know if my explanation isn't clear.

**Comment by wkentaro** [comment]
It's clear, but I feel that you can create a simple script to remove them.
something like below (I haven't tested)
```bash
for f in *.png; do
  if [ ! ${f/.png/.json} ]; then
    rm $f
  fi
done
```
