### ISSUE TITLE
How to generate occluded segments in annotations.jason 

### ISSUE THREAD

**Issue by sonozuka** [wkentaro/labelme#517]
How to generate occluded segments in annotations.jason 

examples/instance_segmentation/data_dataset_coco/annotations.json

I tried use labelme as the example below;
labelme data_annotated --labels labels.txt --nodata --labelflags '{.*: [occluded, truncated], person-\d+: [male]}'

and label person-1, person-2 with occlude flag checked.
How ever the generated annotations.json, multiple segments are not generated by labelme2coco.py.

In my annotations.json, person-1, person-2 are separated segment field.

**Comment by sonozuka** [comment]
My output for annotations.jason ,
no occluded segments are generated by labelme2coco.py,
only one segment separated category person-1 and person-2.
{
    "images": [
        {
            "height": 338,
            "width": 500,
            "id": 0,
            "file_name": "2011_000003.jpg"
        }
    ],
    "categories": [
        {
            "supercategory": "",
            "id": 0,
            "name": ""
        },
        {
            "supercategory": "bottle",
            "id": 1,
            "name": "bottle"
        },
        {
            "supercategory": "person-1",
            "id": 2,
            "name": "person-1"
        },
        {
            "supercategory": "person-2",
            "id": 3,
            "name": "person-2"
        }
    ],
    "annotations": [
        {
            "segmentation": [
                [
                    250.984126984127,
                    106.92063492063491,
                    229.984126984127,
                    118.92063492063491,
                    221.984126984127,
                    134.9206349206349,
                    223.984126984127,
                    147.9206349206349,
                    217.984126984127,
                    160.9206349206349,
                    202.984126984127,
                    167.9206349206349,
                    192.984126984127,
                    199.9206349206349,
                    194.984126984127,
                    221.9206349206349,
                    199.984126984127,
                    226.9206349206349,
                    191.984126984127,
                    233.9206349206349,
                    197.984126984127,
                    263.92063492063494,
                    213.984126984127,
                    294.92063492063494,
                    214.984126984127,
                    319.92063492063494,
                    221.984126984127,
                    326.92063492063494,
                    235.984126984127,
                    325.92063492063494,
                    240.984126984127,
                    322.92063492063494,
                    235.984126984127,
                    297.92063492063494,
                    238.984126984127,
                    286.92063492063494,
                    234.984126984127,
                    267.92063492063494,
                    254.22222222222223,
                    260.55555555555554,
                    264.984126984127,
                    263.92063492063494,
                    256.984126984127,
                    272.92063492063494,
                    259.984126984127,
                    281.92063492063494,
                    284.984126984127,
                    287.92063492063494,
                    297.984126984127,
                    277.92063492063494,
                    288.984126984127,
                    269.92063492063494,
                    281.984126984127,
                    269.92063492063494,
                    283.984126984127,
                    263.92063492063494,
                    292.984126984127,
                    260.92063492063494,
                    308.984126984127,
                    235.9206349206349,
                    313.984126984127,
                    216.9206349206349,
                    309.984126984127,
                    207.9206349206349,
                    312.984126984127,
                    201.9206349206349,
                    308.984126984127,
                    184.9206349206349,
                    291.984126984127,
                    172.9206349206349,
                    269.984126984127,
                    158.9206349206349,
                    261.984126984127,
                    153.9206349206349,
                    264.984126984127,
                    141.9206349206349,
                    273.984126984127,
                    136.9206349206349,
                    278.984126984127,
                    129.9206349206349,
                    270.984126984127,
                    120.92063492063491
                ]
            ],
            "iscrowd": 0,
            "area": 15479.0,
            "image_id": 0,
            "bbox": [
                191.0,
                106.0,
                122.0,
                220.0
            ],
            "category_id": 2,
            "id": 1
        },
        {
            "segmentation": [
                [
                    482.0,
                    85.0,
                    468.0,
                    90.0,
                    460.0,
                    110.0,
                    460.0,
                    127.0,
                    444.0,
                    137.0,
                    419.0,
                    153.0,
                    410.0,
                    163.0,
                    403.0,
                    168.0,
                    394.0,
                    170.0,
                    386.0,
                    168.0,
                    386.0,
                    184.0,
                    392.0,
                    182.0,
                    410.0,
                    187.0,
                    414.0,
                    192.0,
                    437.0,
                    189.0,
                    434.0,
                    204.0,
                    390.0,
                    195.0,
                    386.0,
                    195.0,
                    387.0,
                    208.0,
                    381.0,
                    212.0,
                    372.0,
                    212.0,
                    372.0,
                    216.0,
                    400.0,
                    270.0,
                    389.0,
                    272.0,
                    389.0,
                    274.0,
                    403.0,
                    282.0,
                    444.0,
                    283.0,
                    443.0,
                    259.0,
                    426.0,
                    244.0,
                    462.0,
                    256.0,
                    474.0,
                    270.0,
                    477.0,
                    280.0,
                    473.0,
                    289.0,
                    471.0,
                    296.0,
                    472.0,
                    317.0,
                    480.0,
                    332.0,
                    494.0,
                    335.0,
                    498.0,
                    329.0,
                    494.0,
                    308.0,
                    499.0,
                    297.0,
                    499.0,
                    90.0
                ]
            ],
            "iscrowd": 0,
            "area": 16888.5,
            "image_id": 0,
            "bbox": [
                372.0,
                85.0,
                127.0,
                250.0
            ],
            "category_id": 3,
            "id": 2
        },
        {
            "segmentation": [
                [
                    374.0,
                    159.0,
                    369.0,
                    170.0,
                    369.0,
                    210.0,
                    375.0,
                    212.0,
                    387.0,
                    209.0,
                    385.0,
                    185.0,
                    385.0,
                    168.0,
                    385.0,
                    165.0,
                    382.0,
                    159.0
                ]
            ],
            "iscrowd": 0,
            "area": 817.5,
            "image_id": 0,
            "bbox": [
                369.0,
                159.0,
                18.0,
                53.0
            ],
            "category_id": 1,
            "id": 3
        },
        {
            "segmentation": [
                [
                    370.0,
                    170.0,
                    366.0,
                    173.0,
                    365.0,
                    182.0,
                    368.0,
                    185.0
                ]
            ],
            "iscrowd": 0,
            "area": 42.0,
            "image_id": 0,
            "bbox": [
                365.0,
                170.0,
                5.0,
                15.0
            ],
            "category_id": 3,
            "id": 4
        },
        {
            "segmentation": [
                [
                    338.0,
                    266.0,
                    313.0,
                    269.0,
                    297.0,
                    277.0,
                    282.0,
                    288.0,
                    273.0,
                    302.0,
                    272.0,
                    320.0,
                    279.0,
                    337.0,
                    428.0,
                    337.0,
                    432.0,
                    316.0,
                    423.0,
                    296.0,
                    403.0,
                    283.0,
                    370.0,
                    270.0
                ]
            ],
            "iscrowd": 0,
            "area": 9315.0,
            "image_id": 0,
            "bbox": [
                272.0,
                266.0,
                160.0,
                71.0
            ],
            "category_id": 0,
            "id": 5
        }
    ]
}

**Comment by sonozuka** [comment]
Please let me know quickly yes or no, do I have to develop or modify labelme2coco.py to set occluded segments in annotations.jason?

**Comment by wkentaro** [comment]
labelme2coco.py won't respect flags. If you want, you need to modify it.
