### ISSUE TITLE
2 minor remarks: flashing when zapping through, saving keep-prev

### ISSUE THREAD

**Issue by marente** [wkentaro/labelme#518]
Hi I am currently using LabelMe to go through frames of videos and I wanted to mention that my eyes would love it if the old image would stay in place until the next video is loaded, at the moment I have a split second of grey background everytime I advance.
It might be a hussle to make this change tho, so that wouldn't be worth it then.
Bai

**Comment by marente** [comment]
Also it would be useful if one had an additional option to not only autosave, but also autosave labels from --keep-prev - previous images, (except one deletes them.)
At the moment I have to move every box a little.

**Comment by wkentaro** [comment]
- flashing when zapping through 
  - See https://github.com/wkentaro/labelme/issues/536
- saving keep-prev
  - See #577
