### ISSUE TITLE
Visualization Legend Bugs?

### ISSUE THREAD

**Issue by Lecanyu** [wkentaro/labelme#52]
Hi, 

I have tried to visualize a labeled .json file. But the visualization result is wrong.

Specifically, I labeled one image in labelme and it looks like
![image](https://user-images.githubusercontent.com/30331417/34700270-e336ce14-f4a7-11e7-95e3-bb0ad95ce135.png)

Then I visualized labeled json file.
![image](https://user-images.githubusercontent.com/30331417/34700291-0febdf8a-f4a8-11e7-8692-758d563ad1c8.png)

As you can see, the legend in visualization is wrong.

I guess that the error is caused by overlapped label area between water (red polygon in the first image) and lamppost (blue polygon in the first image)

Is it a bug? Does this error cause wrong label id in final dataset? 

Any solutions will be appreciated.

**Comment by wkentaro** [comment]
I think something is wrong on your environment or in your annotation.
And I think you can check the sanity of your annotation with 

sample file:
- https://github.com/wkentaro/labelme/blob/master/static/apc2016_obj3.json

and utility scripts:
- https://github.com/wkentaro/labelme/blob/master/scripts/labelme_draw_json
- https://github.com/wkentaro/labelme/blob/master/scripts/labelme_json_to_dataset

Maybe you should try below:

```bash
./labelme_draw_json ../static/apc2016_obj3.json
./labelme_draw_json <your json file>

# check what is different
labelme ../static/apc2016_obj3.json
labelme <your json file>
less ../static/apc2016_obj3.json
less <your json file>
```

**Comment by Lecanyu** [comment]
Hi,

I have tried your sample file by your scripts and my installed scripts. They produce the same result.

your sample file looks like
![image](https://user-images.githubusercontent.com/30331417/34793320-9259da1c-f610-11e7-9533-f820be47e6aa.png)

In labelme.
![image](https://user-images.githubusercontent.com/30331417/34793430-f199d7c0-f610-11e7-9db4-690750f8a686.png)

They look like good.


However, your scripts and my installed scripts don't work in my json file. 
You can try it in [this link](https://drive.google.com/open?id=1J3_cr5dL6OKnc6skP9p4pqukeqx7QSuw)

**Comment by wkentaro** [comment]
@Lecanyu 
#59 fixes this issue, and I got the result below. Does this look okay for you?

![figure_1](https://user-images.githubusercontent.com/4310419/35700962-d882cc78-07d7-11e8-9917-a2318a3bde62.png)

**Comment by Lecanyu** [comment]
Yes. I think it works normally now.

Did you upload you newest code?

**Comment by wkentaro** [comment]
Yeah, Please use the current master branch.
