### ISSUE TITLE
How to change label.png color

### ISSUE THREAD

**Issue by PattonYu** [wkentaro/labelme#520]
I found that,the points label generated is **R:128,G:0,B:0** and a black( **R:0,G:0,B:0** ) background in default. So, how to get a label.png with black background ,and red( **R:255,G:0,B:0** ) mask

And I want to make a dataset like TRANCOS

Thank u!

**Comment by PattonYu** [comment]
And, I tried to chang my _io.py like this
`python
 colormap = label_colormap(255)
 colormap[0] = [255, 0, 0]
`
but the background of label.png became **R:1,G:0,B:0**

**Comment by wkentaro** [comment]
Maybe you are missing `pip install .` after editing the file.
