### ISSUE TITLE
Instance segmentation not working

### ISSUE THREAD

**Issue by aditya-krish** [wkentaro/labelme#527]
SegmentationObjectPNG and SegmentationClassPNG have same type of images and not showing different colors for different instances.
<img src=https://user-images.githubusercontent.com/55757328/71172201-9db37500-2285-11ea-9758-e8decca2be09.png width=30% > <img src=https://user-images.githubusercontent.com/55757328/71172208-a441ec80-2285-11ea-92f0-5c145f4059dc.png width=30%>

Even though while labelling I labelled as classname-1, classname-2
The labels.txt file has only classname once as you have shown in the instance segmentation example.
What could I be doing wrong? I really want different instances in different colors

**Comment by wkentaro** [comment]
Can you tell me how to reproduce?

**Comment by aditya-krish** [comment]
Hi, you can close this issue I have resolved it myself, I think I was
missing a couple of lines of code in the labelme2voc.py file, due to
incorrectly deleting it. I think this was the resolution to the best of my
recollection.
