### ISSUE TITLE
Category_Id to start at 1 instead of 0?

### ISSUE THREAD

**Issue by Mogarbobac** [wkentaro/labelme#531]
I was wondering how I could change labelme2coco.py to have the "id":0 list to begin at 1 instead of 0? this would also have to update the Category_Id properly.

so from
![image](https://user-images.githubusercontent.com/45700961/71549377-58302f80-298a-11ea-8b43-c7080d61c743.png)
to
![image](https://user-images.githubusercontent.com/45700961/71549385-65e5b500-298a-11ea-8e42-05d14df2a914.png)
 and then from
![image](https://user-images.githubusercontent.com/45700961/71549389-71d17700-298a-11ea-93d3-87a4d3b25fc5.png)
Thank you!

**Comment by wkentaro** [comment]
Maybe you can change this part https://github.com/wkentaro/labelme/blob/9ed44c854926aef03c7e7c60222075aa7adda8bd/examples/instance_segmentation/labelme2coco.py#L68-L80
