### ISSUE TITLE
 How to add point for my annotated polygons?

### ISSUE THREAD

**Issue by chegnyanjun** [wkentaro/labelme#533]
Hi,thanks for your great work.But i met some problem recently.I have annotated some datas for sementic works before, and i want to add some points for per polygon in images i annotated,but i don't want to delete the annotated polygons to annotate again,I just want to add one or two point for the annotated polygon.But i don't find way how to do it.Does the labelme supports such operator?tkx.

**Comment by bganglia** [comment]
@chegnyanjun Select "Edit Polygons" from the menu on the left. Then, click on the polygon you want to edit, right-click on an edge, and then select "Add Point to Edge". You can also hover over the edge and press Ctrl+Shift+P. Either way, make sure you are hovering on the side inside the polygon, otherwise it will not know what you are doing.

Is that what you wanted to know?

**Comment by chegnyanjun** [comment]
@bganglia,thank you for your help, I got it.

**Comment by sun-png** [comment]
> Hi,thanks for your great work.But i met some problem recently.I have annotated some datas for sementic works before, and i want to add some points for per polygon in images i annotated,but i don't want to delete the annotated polygons to annotate again,I just want to add one or two point for the annotated polygon.But i don't find way how to do it.Does the labelme supports such operator?tkx.

Hello, I want to ask about the picture that has been marked before. I have saved the generated JSON file. I want to change the category of a box in the picture that has been marked before. When I open the picture that has been marked before, I get an error and can't open the picture. I don't want to annotate again, so please ask how to edit the already annotated graphics.

**Comment by sun-png** [comment]
> Hi,thanks for your great work.But i met some problem recently.I have annotated some datas for sementic works before, and i want to add some points for per polygon in images i annotated,but i don't want to delete the annotated polygons to annotate again,I just want to add one or two point for the annotated polygon.But i don't find way how to do it.Does the labelme supports such operator?tkx.

Hello, I want to ask about the picture that has been marked before. I have saved the generated JSON file. I want to change the category of a box in the picture that has been marked before. When I open the picture that has been marked before, I get an error and can't open the picture. I don't want to annotate again, so please ask how to edit the already annotated graphics.

**Comment by Maioy97** [comment]
when I got a similar error before it was something wrong with the json file 
either a tag was missing or a closing brackt was missing like ] or }
I think you should check your json file for that image
