### ISSUE TITLE
Why loading imgs winkle?

### ISSUE THREAD

**Issue by chegnyanjun** [wkentaro/labelme#536]
Hi, i am use labelme3.18.0,but i find when i was use keyboards shortcuts D or A to scan my own dataset imgs fastly,there is a blank window int the window's center exist between one img and two img,and it is not convenient for me to check my annotated datas fastly.Does anyone can help to deal with it?tkx.

**Comment by wkentaro** [comment]
It looks like this issue is mitigated now in the latest version. Please reopen if it is still a problem
