### ISSUE TITLE
batch process mutilple json files failed

### ISSUE THREAD

**Issue by li-zheng-hao** [wkentaro/labelme#539]
## Problem
i used the code in `labelme/examples/semantic_segmentation/labelme2voc.py`  and the output result is not correct:
![微信截图_20200106100307](https://user-images.githubusercontent.com/22129824/71790497-c56b5100-306b-11ea-9893-5a1ed716d179.png)
I'm sure there is no problem with my markup,However, the output labeling result is incorrect.

1. how can i get the file `labels_file` in `labelme2voc.py`, i just create the file and input my labels manually,like:
```python
__ignore__
_background_
obj
```
2. why the mask and origin image is not match, like the mask rotate 90°?

## my env:
1. labelme: 3.16.0
2. system: win10
3. python: 3.6.0

**Comment by wkentaro** [comment]
Which one is rotated in the images you present? The gray background image (the real image) or red annotation?

**Comment by li-zheng-hao** [comment]
I update labelme version from 3.16.0 to 3.18.0. And here are my images:

1. origin image
![0](https://user-images.githubusercontent.com/22129824/72058793-b4d90600-330b-11ea-9347-4cb12f9cfd31.jpg)

2. generate JPEGImages folder image
![0](https://user-images.githubusercontent.com/22129824/72058889-e0f48700-330b-11ea-919b-869621eae05b.jpg)

3. generate SegmentationClassPNG folder image
![0](https://user-images.githubusercontent.com/22129824/72058941-f9fd3800-330b-11ea-8de2-db66b7cae60a.png)

4. generate SegmentationClassVisualization folder image
![0](https://user-images.githubusercontent.com/22129824/72058966-097c8100-330c-11ea-91a6-9a3f84bc6301.jpg)

the code is copy from [labelme2voc.py](https://github.com/wkentaro/labelme/blob/master/examples/semantic_segmentation/labelme2voc.py)

@wkentaro

**Comment by li-zheng-hao** [comment]
and all images' shape is 4000×3000 ( width × height )

**Comment by wkentaro** [comment]
Can you possibly upload related files (original image, annotated json file, exported files) as zip?
You can upload zip on GitHub comments.

**Comment by li-zheng-hao** [comment]
[files.zip](https://github.com/wkentaro/labelme/files/4040039/files.zip)

**Comment by wkentaro** [comment]
The JSON file is missing?

**Comment by li-zheng-hao** [comment]
[json.zip](https://github.com/wkentaro/labelme/files/4040051/json.zip)

sorry ,I forgot it ...

**Comment by wkentaro** [comment]
I reproduced. https://github.com/wkentaro/labelme/pull/543 will fix this.

**Comment by li-zheng-hao** [comment]
thank you very much

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can remove the EXIF orientation flags from images and convert images to the front orientation. If necessary, you can rotate the image right/left by 90 degrees.
If necessary, you can export/import the Labelme JSON format.
https://rectlabel.com/help#remove_exif_orientation_flags
