### ISSUE TITLE
I find a bug when I edit polygons

### ISSUE THREAD

**Issue by zemofreedom** [wkentaro/labelme#541]
In edit polygons model, when i move one point to edge(espicially in right edge and down edge), the window will closed. If i move the boundingbox, it works well.

**Comment by zemofreedom** [comment]
I have solve the problem. It cause by the function outOfPixmap(canvas.py). When press and move the point, i will get the value over img_h and img_w. It also happens in move shapes. Only use offet to calulator the point after moving will get some error value in edge(like value small than 0 and value > w or h)

**Comment by wkentaro** [comment]
Can you send the solution as a PR?
