### ISSUE TITLE
label changing issue after converting the json file

### ISSUE THREAD

**Issue by fishman2008** [wkentaro/labelme#546]
Suppose the first image has cat, dog, and people classes, and the second image has cat and people classes, after using the labelme_json_to_dataset command to convert the json file, the people in second image will have the same labeling color as dog in first image? That means the converted label image will be wrong? Could you help clarify this? Thanks.

**Comment by wkentaro** [comment]
See https://github.com/wkentaro/labelme/tree/master/examples/semantic_segmentation
