### ISSUE TITLE
May I install labelme without conda?

### ISSUE THREAD

**Issue by crissallan** [wkentaro/labelme#551]
Nice job!
I installed labelme just use pip(because I did't install anaconda for my Windows computer).
The installation works fine, however when I tried to launch labelme in the CMD prompt, it failed, the error is " FileNotFoundError: [Errno 2] No such file or directory: the_current_path\\.labelmerc"

So I tried to use python -m labelme to launch labelme, it failed as well.

Is there any solution for this? Many thanks!

**Comment by cate-cj** [comment]
I successfully installed labelme on win 10 computers several weeks ago, with anaconda and docker.
But when I tried to install labelme using anaconda only on win 7 yesterday, encountered the same error:

←[37m[INFO]←[0m Loading config file from: C:\Users\admin\.labelmerc (←[1mmain.py←
[0m:147)
Traceback (most recent call last):e
  File "C:\Users\admin\Anaconda3\envs\labelme\Scripts\labelme-script.py", line 10
, in <module>
    sys.exit(main())
  File "C:\Users\admin\Anaconda3\envs\labelme\lib\site-packages\labelme\main.py",
 line 148, in maintest
    with open(config) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\.labelmerc'

Need help. Thanks very much!

**Comment by crissallan** [comment]
> I successfully installed labelme on win 10 computers several weeks ago, with anaconda and docker.
> But when I tried to install labelme using anaconda only on win 7 yesterday, encountered the same error:
> 
> ←[37m[INFO]←[0m Loading config file from: C:\Users\admin.labelmerc (←[1mmain.py←
> [0m:147)
> Traceback (most recent call last):e
> File "C:\Users\admin\Anaconda3\envs\labelme\Scripts\labelme-script.py", line 10
> , in
> sys.exit(main())
> File "C:\Users\admin\Anaconda3\envs\labelme\lib\site-packages\labelme\main.py",
> line 148, in maintest
> with open(config) as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\admin\.labelmerc'
> 
> Need help. Thanks very much!

Actually, I solved this problem yesterday. Just new a .labelmerc file and paste the code below in the file, then you can launch labelme in the CMD prompt.
PATSE CODE BELOW INTO YOUR .labelmerc FILE:

auto_save: true
display_label_popup: true
instance_label_auto_increment: true
store_data: true
keep_prev: false
logger_level: info
 
flags: null
label_flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null
 
# main
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true
 
# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false
 
epsilon: 10.0
 
shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete
 
  open_next: [D, Ctrl+Shift+D]
  open_prev: [A, Ctrl+Shift+A]
 
  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F
 
  create_polygon: [C, Ctrl+N]
  create_rectangle: Ctrl+R
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  edit_polygon: [E, Ctrl+J]
  delete_polygon: Delete
  duplicate_polygon: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  add_point_to_edge: Ctrl+Shift+P
  edit_label: Ctrl+E
  edit_line_color: Ctrl+L
  edit_fill_color: Ctrl+Shift+L
  toggle_keep_prev_mode: Ctrl+P

**Comment by cate-cj** [comment]
The problem is solved! Thank you so much!!!

**Comment by ZhenhuiTang** [comment]
Follow your suggestion. a new error is printed:

```
[37m[INFO][0m Loading config file from: C:\Users\Admin\.labelmerc ([1mmain.py[0m:147)
[33m[WARNING][0m Skipping unexpected key in config: show ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: closable ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: movable ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: floatable ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: column ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: row ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: close ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: open ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: open_dir ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: quit ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: save ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: save_as ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: save_to ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: delete_file ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: open_next ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: open_prev ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: zoom_in ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: zoom_out ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: zoom_to_original ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: fit_window ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: fit_width ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: create_polygon ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: create_rectangle ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: create_circle ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: create_line ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: create_point ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: create_linestrip ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: edit_polygon ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: delete_polygon ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: duplicate_polygon ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: undo ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: undo_last_point ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: add_point_to_edge ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: edit_label ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: edit_line_color ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: edit_fill_color ([1m__init__.py[0m:18)
[33m[WARNING][0m Skipping unexpected key in config: toggle_keep_prev_mode ([1m__init__.py[0m:18)
Traceback (most recent call last):
  File "c:\users\admin\anaconda3\envs\labelme1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\admin\anaconda3\envs\labelme1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\Anaconda3\envs\labelme1\Scripts\labelme.exe\__main__.py", line 7, in <module>
  File "c:\users\admin\anaconda3\envs\labelme1\lib\site-packages\labelme\main.py", line 180, in main
    output_dir=output_dir,
  File "c:\users\admin\anaconda3\envs\labelme1\lib\site-packages\labelme\app.py", line 170, in __init__
    if self._config[dock]['closable']:
TypeError: 'NoneType' object is not subscriptable
```

can you provide the .labelmerc file?

**Comment by wkentaro** [comment]
@crissallan thanks. #555 will fix this problem
