### ISSUE TITLE
Cannot find .labelmerc file on MacOS Mojave installation

### ISSUE THREAD

**Issue by darwinharianto** [wkentaro/labelme#554]
I have installed labelme using 

brew install pyqt 
pip install labelme 

on python 3.6

After I run labelme, it gives me error on file not found.
On the docs, I can find that labelme should automatically create labelmerc on home directory. 
Unfortunately, I can't find that file.

How do I make labelme config files?

**Comment by YuxinZou** [comment]
same porblem under Ubuntu. any help?

**Comment by wkentaro** [comment]
Thanks for the report. https://github.com/wkentaro/labelme/pull/555 will fix this problem
