### ISSUE TITLE
Typo of your name Bibtex reference on the README.md

### ISSUE THREAD

**Issue by jallemand** [wkentaro/labelme#558]
Just wanted to point out that it appears you've spelt your name wrong in the bibtex entry when I went to use it.

Thought you might want to correct so people can cite you correctly :)

Very grateful for your software and was nice and easy to use for my master thesis.

**Comment by wkentaro** [comment]
Oops. Thanks!

**Comment by wkentaro** [comment]
Closed via 6aa70229b62c20192904fb53fb1b377c18087d09
