### ISSUE TITLE
label.png are zeros

### ISSUE THREAD

**Issue by SunAnLan** [wkentaro/labelme#56]
all the label.png generated are zeros

**Comment by wkentaro** [comment]
Please provide your json file or more information.

**Comment by wkentaro** [comment]
Maybe #59 fixes this issue, so could you please check again?

**Comment by simonsayshi** [comment]
@wkentaro 
hi, i used labelme_json_to_dataset and the label.png I have is a black picture and all pixel value are zero. but the label_viz.png looks fine, why is that??

**Comment by wkentaro** [comment]
@simonsayshi 
Do you mean "all pixel value are zero" as `assert np.all(lbl == 0) is True`?
label.png must be loaded by `PIL.Image` as described in the README: https://github.com/wkentaro/labelme#usage
