### ISSUE TITLE
pip install labelme still has missing labelmerc file

### ISSUE THREAD

**Issue by PulkitMishra** [wkentaro/labelme#560]
This error was fixed with #555 . But on installing with pip, the error persists.

**Comment by wkentaro** [comment]
Can you copy-and-paste the command and error messages?

**Comment by PulkitMishra** [comment]
Sorry for the delayed response @wkentaro . I did a simple pip3 install labelme on an ubuntu 19.10 system. 

i got a file not found error. labelmerc file was not being generated. I made the changes as done in #555 and it worked.

**Comment by wkentaro** [comment]
Good to hear that :+1:
