### ISSUE TITLE
Error when delete points from shape

### ISSUE THREAD

**Issue by gzhang8** [wkentaro/labelme#576]
When I delete a point from a polygon, I see the following error:

```
Traceback (most recent call last):
  File "/home/gzhang8/bin/labelme-v4/labelme/widgets/canvas.py", line 295, in removeSelectedPoint
    index = shape.nearestVertex(point, self.epsilon)
AttributeError: 'NoneType' object has no attribute 'nearestVertex'
```
I am using python 3.6.7. Run the instance_segmentation can reproduce the error. Thanks.

**Comment by wkentaro** [comment]
Can you write how to reproduce?

**Comment by stvon** [comment]
When I try to add a point to edge,  I see the following error:
Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\labelme\widgets\canvas.py", line 282, in addPointToEdge
    shape.insertPoint(index, point)
AttributeError: 'NoneType' object has no attribute 'insertPoint'.

**Comment by gzhang8** [comment]
@wkentaro @stvon the same thing. I tested the master branch. 

@wkentaro to reproduce: add or import a labeled polygon and then add or remove a polygon vertex. The error will appear
