### ISSUE TITLE
Fast Way For Converting To New Json Format

### ISSUE THREAD

**Issue by cm107** [wkentaro/labelme#587]
I have a lot of labelme annotations that use the old labelme format (3.18.0).
Since the recent update, some keys have disappeared while some new keys have been added to the dictionary.
I am aware that you can convert to the new format (4.2.5) by opening each image one-by-one and doing a 'Save As', but this is too time consuming.
Is there a script where I can just specify the image directory and the json directory and have it automatically convert all of the annotations over to the new format without opening the GUI?

**Comment by wkentaro** [comment]
They are compatible in most case, what kind of issue did you get?

**Comment by cm107** [comment]
@wkentaro The tools that I made made references to the keys in the old format, but they don't exist in the new format. e.g. lineColor
I made a quick fix in my code so that both formats can be used, but it still just kind of bothers me that I have two different formats.

**Comment by wkentaro** [comment]
I'm not sure I understood correctly. Which one do you mean? Do you want to remove all deprecated keys from old JSON files? or You want to add all deprecated keys to the new JSON files? I'm not sure what kind of tools do you use.

I feel adjusting your tools seems easy if they were Python files:

```python
for json_file in glob.glob('*.json'):
    data = json.load(open(json_file))
    line_color = data.get('lineColor', (0, 255, 0))  # works on both v3 and v4
    for shape_data in data['shapes']:
        line_color = shape_data.get('lineColor', (0, 255, 0))  # works on both v3 and v4
```
