### ISSUE TITLE
json to dataset not working

### ISSUE THREAD

**Issue by RuijtenP** [wkentaro/labelme#588]
I get an error when running labelme_json_to_dataset on my json-files.

  File "...\anaconda3\envs\labelme\lib\site-packages\imgviz\color.py", line 21, in rgb2gray
    assert rgb.shape[2] == 3, 'rgb shape must be (H, W, 3)'

import labelme also not working. (as expected)

So I guess my question: how to get png masks from the json files generated by labelme ?

**Comment by wkentaro** [comment]
I guess you're using gray image instead of RGB, right?

**Comment by wkentaro** [comment]
> So I guess my question: how to get png masks from the json files generated by labelme ?

See examples.

**Comment by RuijtenP** [comment]
My utils.img_b64_to_arr command gave a (w,h,4) image, with the last dimension just being the type (uint8 in my case). So I was working with colored images, but solved it by throwing away that last "dimension": 

    img2 = utils.img_b64_to_arr(imageData)
    img= np.zeros((1080,1920,3),np.uint8)
    for i in range(1080):
        for j in range(1920):
                img[i][j]=img2[i][j][:-1]

Now it seems to be working fine. 

I guess it`s the same type of problem as using gray images. 

Thanks for the responses!
