### ISSUE TITLE
Opening directory whit multiple json files

### ISSUE THREAD

**Issue by aleksandragrzegorczyk** [wkentaro/labelme#592]
Hi! Is it possible to open directory that contains multiple json files with annotations? I want to be able to switch between different jsons using next/previous image buttons.

**Comment by wkentaro** [comment]
See example: https://github.com/wkentaro/labelme/tree/master/examples/semantic_segmentation#annotation

**Comment by aleksandragrzegorczyk** [comment]
In the example that you mentioned there are both image files and corresponding labels in the same folder. What i would like to have is ability to open folder with only json files inside. Yesterday I managed to make small modifications that enables that by myself. Still i am wondering if that functionality is provided without need for code modification?

**Comment by wkentaro** [comment]
I see. That's not possible, and I think hard to integrate nicely with the current UI.

**Comment by aleksandragrzegorczyk** [comment]
The solution i came up with (which is not very elegant) is to display in FileList paths to images which those json files belongs to (basically displaying "imagePath" field from json).

Thank you for your answer!

**Comment by wkentaro** [comment]
If you still have the image directory, you can do like below:

```bash
% ls data_annotated_separately/image
2011_000003.jpg  2011_000006.jpg  2011_000025.jpg

% ls data_annotated_separately/json
2011_000003.json  2011_000006.json  2011_000025.json

% grep imagePath data_annotated_separately/json/2011_000003.json
  "imagePath": "../image/2011_000003.jpg",

# works
% labelme data_annotated_separately/image --output data_annotated_separately/json
```

But if you don't have the image directory, it won't work
```bash
# won't work!
% labelme /tmp --output data_annotated_separately/json
```

**Comment by aleksandragrzegorczyk** [comment]
Thank you! This is what i was looking for
