### ISSUE TITLE
cursor exits polygon, polygon is still filled with color

### ISSUE THREAD

**Issue by leo234-sw** [wkentaro/labelme#594]
labelme==4.2.7
when cursor exits polygon, polygon is still filled with color
![g1](https://user-images.githubusercontent.com/60990598/74385430-d0946800-4df3-11ea-938b-48bbde315f9e.gif)

**Comment by thanvietduc1997** [comment]
I have the same issue and I figure out it myself :D 

You can add the follwing line in unHighlight method of Canvas class in widgets/canvas.py
self.hVertex, self.hShape, self.hEdge = None, None, None
<img width="1792" alt="Screen Shot 2020-02-14 at 1 49 46 PM" src="https://user-images.githubusercontent.com/46135455/74508144-e0659680-4f30-11ea-8d5e-509e916f9eba.png">

**Comment by thanvietduc1997** [comment]
@wkentaro you've forgotten to clear highlighted shape after the cursor leave polygon
