### ISSUE TITLE
Can't use shortcuts for add_point_to_edge

### ISSUE THREAD

**Issue by stvon** [wkentaro/labelme#602]
labelme==4.2.9, win10
when edit, it can add point but can't use shortcuts for add_point_to_edge. 
I try to change "None" in app.py of line 335 to "shortcuts['add_point_to_edge']". It works occasionally.
BTW, Can you add shortcut for remove point?

**Comment by wkentaro** [comment]
> It works occasionally.

Yes, because it is only activated when the mouse cursor is close to the edge of a polygon.

> Can you add shortcut for remove point? 

That's possible, but I don't think it's going to be useful.

**Comment by stvon** [comment]
> Yes, because it is only activated when the mouse cursor is close to the edge of a polygon.
I mean it is unstable in 4.2.9. If I rolled back to 4.1.4, it works smoothly.
In both version, I do move mouse cursor  close to the edge of a polygon.
