### ISSUE TITLE
how to convert json which only contains points to dataset?

### ISSUE THREAD

**Issue by zener90818** [wkentaro/labelme#606]
i meet an error as below:
assert len(xy) > 2, 'Polygon must have points more than 2'
AssertionError: Polygon must have points more than 2

**Comment by wkentaro** [comment]
Which script are you using?

**Comment by alphapibeta** [comment]
I got the same error I am using 

**./labelme2coco.py data_annotated data_dataset_coco --labels labels.txt**

**Comment by dasmehdix** [comment]
Same here.

> I got the same error I am using
> 
> **./labelme2coco.py data_annotated data_dataset_coco --labels labels.txt**

Same here.
