### ISSUE TITLE
【BUG】labelme2voc.py convert error in high version lableme

### ISSUE THREAD

**Issue by Ronales** [wkentaro/labelme#614]
When I covert lableme dataset to voc format dataset.Owe to the big version update of labelme,I can't finish convert process until change the 3.16.1 version.so I think we sholud revise this error about moudels import.

Thanks in advance! 

The error display the error is can't import labelme.utils.draw_instances function.
![Uploading image.png…]()

**Comment by wkentaro** [comment]
Can you please upload the image? I can't see the image.png

**Comment by Ronales** [comment]
@wkentaro Sorry,I have deleted this image.In previous convert code,I exactly find this problems, which tips: "can't import labelme.utils.draw_instances function".That due to high labelme version not suit current convert code,Finally I descend the labelme version.

I use this lableme2voc.py provided by you.

**Comment by wkentaro** [comment]
So how can I reproduce?
