### ISSUE TITLE
Image size exceeds limit of * pixels, could be decomperssion bomb DOS attack.

### ISSUE THREAD

**Issue by vpapaioannou** [wkentaro/labelme#618]
I have an image for which I created already the labels and the .json files already exist. I want to make some corrections but I am getting the following error when I try to open the image and .json file is being loaded. How can I increase the limit in the context of labelme?

![image](https://user-images.githubusercontent.com/6065702/76362350-4e666900-62f7-11ea-8834-4157509be5a3.png)

**Comment by wkentaro** [comment]
This should be fixed with https://github.com/wkentaro/labelme/pull/548
Can you check your installed labelme includes this change?
