### ISSUE TITLE
modifying the code???

### ISSUE THREAD

**Issue by geokalom** [wkentaro/labelme#619]
Οn line 125 of  __main__.py we can load a txt file with some labels. How do I modify the code so that when we compile the labelme in exe form, it will also maybe create or read(i dont know) a labels.txt file with our own tags, and when the labelme is in exe form and execute it, it will load the labels from the labels.txt that we had written. Simply we put the labels in Label List we want from the labels.txt instead of creating, without removing this capability. I know that we can load a txt file with labels using labelme --labels labels.txt. 
    Βefore we make the exe can we  modify the code to do this without using command prompt at all and then to compile the labelme.exe which can load a txt.file automatically?

**Comment by geokalom** [comment]
Οn line 125 of __main__.py we can import the txt file. How do I modify the code so that when we compile the labelme in exe form, it will also create a labels.txt file with our own tags, and when the labelme is in exe form and execute it, it will load labels.txt had just been created as well. Simply we put the labels in Label List we want in labels.txt instead of creating our own, without removing this capability. I know that we can load a txt file with labels using labelme --labels labels.txt. 
    Βefore we make the exe can we  modify the code to do this without using command prompt at all and then to compile the labelme.exe which can load a txt.file automatically?

**Comment by wkentaro** [comment]
Sorry, I don't understand what you want to do. Please describe more simply.

**Comment by geokalom** [comment]
What I mean is that:
 I want to do the following: every time when I open labelme.exe, i want it to reads the labels from the txt file without actually loading the txt manually using --labels option or labels: key in ~/.labelmerc . Can this be done automatically? What will be the changes in the source code??
And when i write changes, i mean hard-coding changes. Can you please help if possible?
Thanks in advance...
