### ISSUE TITLE
Sometime undo does not work

### ISSUE THREAD

**Issue by iperov** [wkentaro/labelme#620]
![2020-03-13_21-06-49](https://user-images.githubusercontent.com/8076202/76643515-9b07a980-656e-11ea-8e3a-02152b472b34.gif)

**Comment by wkentaro** [comment]
Do you have any idea when this happens?

**Comment by iperov** [comment]
crap labeling tool. I created my own tool called XSegEditor for DeepFaceLab, which is much better than your shit.

**Comment by jfemiani** [comment]
Just encountered this issue. 
This happens when autosave is enabled. 
You never call actions.undo.setEnabled if you save the document
