### ISSUE TITLE
FileNotFoundError when trying to save GUI annotations started from command line

### ISSUE THREAD

**Issue by nlin5** [wkentaro/labelme#628]
Error Trackback:
Traceback (most recent call last):
  File "labelme/app.py", line 1326, in saveFile
  File "labelme/app.py", line 1369, in _saveFile
  File "labelme/app.py", line 930, in saveLabels
  File "os.py", line 220, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: ''
Abort trap: 6

Command Line Code:
`labelme my_file.png -O myfile.json`

Situation:
The above command line code opens up the Labelme GUI and I am able to create polygons to annotate segments of my image. However, when I click "Save", Labelme closes and I get the above error traceback.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Labelme Version: 3.6.10

**Comment by wkentaro** [comment]
I can't reproduce. 
```
cd examples/tutorial
rm -rf *json
labelme apc2016_obj3.jpg -O apc2016_obj3.json  # it exits with 0
```
