### ISSUE TITLE
Cannot mix incompatible Qt library

### ISSUE THREAD

**Issue by Yangxiaojun1230** [wkentaro/labelme#630]
I run in a conda env just setup follow the step. And installed labelme successfully. But when i run labelme, it occured error:
[INFO] Loading config file from: /home/yangjeff/.labelmerc (__init__.py:73)
Cannot mix incompatible Qt library (version 0x50907) with this library (version 0x50905)
Aborted (core dumped)
Do anyone could help me.
The system is ubuntu16.04

**Comment by wkentaro** [comment]
The CI is working perfectly with Conda on Ubuntu 16.04.
https://github.com/wkentaro/labelme/actions?query=workflow%3Aci

Maybe you have something wrong in the apt installed libraries.

**Comment by mfaramarzi** [comment]
> I run in a conda env just setup follow the step. And installed labelme successfully. But when i run labelme, it occured error:
> [INFO] Loading config file from: /home/yangjeff/.labelmerc (**init**.py:73)
> Cannot mix incompatible Qt library (version 0x50907) with this library (version 0x50905)
> Aborted (core dumped)
> Do anyone could help me.
> The system is ubuntu16.04

@Yangxiaojun1230 
I have the same problem. Could you fix it?

**Comment by Yangxiaojun1230** [comment]
At last i fix it by reinstall conda env,  it's wrong with my env since i use same version python with host.
