### ISSUE TITLE
Error opening file 'line color'

### ISSUE THREAD

**Issue by Ruolingdeng** [wkentaro/labelme#631]
I met with a problem: Error opening file 'linecolor'. I annotated my images using labelme software in windows system. And now I want to use the json file to do training in Ubuntu 16.04, but it occurred "FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/train2017/..\ResizeImage\000010.jpg'." When I used the labelme software in Ubuntu system to open the json file, it occurred "make sure /home/xbd/000000.json is a valid label file" 
Could anybody help me, please? I will be very appreciated with you.

**Comment by wkentaro** [comment]
On Windows, the separation character of directories is `\`, but it is `/` on Ubuntu.
So I think you need to modify them somehow by using sed or Python small script.

**Comment by Ruolingdeng** [comment]
@wkentaro I have changed the separation character of directories from \ to /, but it still doesn't work. The problem still occurred. When I annotated the images in labelme software in windows system, the different instances have different colour can be seen in the labelme GUI, but not in Ubuntu system.

**Comment by wkentaro** [comment]
Okay. It seems you need to deeply look into the JSON file to fix this.

Since I don't have that JSON file and Window system, I don't think I can debug this.

**Comment by jeffreyameyer** [comment]
I saw this on MacOSX after:
a) opening a directory with a newer version of labelme (4.4)
b) trying to open the directory on a different machine with an older (3.x.x) version of labelme 

So, I don't think it's an OS or file path issue (glad to be wrong).

@Ruolingdeng - can you confirm the versions of labelme you were using in Windows vs. Ubuntu?

**Comment by wkentaro** [comment]
@jeffreyameyer So you're trying to open a JSON file with labelme v3 annotated with labelme v4? Then this error is expected, right? Since v4 is not compatible to v3, though v3 is compatible to v4.

**Comment by jdhao** [comment]
I have also met this issue on Windows. The json file is annotated with labelme 4.4, and my labelme version is 3.x. It complains the same error:

> Error opening file
> 'lineColor'
> Make sure xxx.json is a valid label file.

**Comment by wkentaro** [comment]
Closing with https://github.com/wkentaro/labelme/issues/631#issuecomment-635558804

**Comment by AbhishekMaity001** [comment]
**This issue can be easily solved** : Just remember one thing **You cannot open NEW labelme version(4.x.x) json files in  your old labelme version(3.x.x). app**  So just download the new version of  labelme app json and then try to load the files.... it will be supported... (HINT : You can go inside the json file and check which version of labelme was used to annotate this file)

**Comment by phiyodr** [comment]
Hi, btw you can convert `\` to `/` in all json files within a directory using this one line:

```bash
sudo apt-get install jq 
sudo apt-get install moreutils # for sponge
for FILE in *; do jq '(.imagePath)|=(gsub("\\\\";"/"))' $FILE | sponge $FILE; done
```
