### ISSUE TITLE
labelme2voc.py Does not generate ImageSets/Segmentation/train.txt test.txt trainval.txt val.txt

### ISSUE THREAD

**Issue by azeemabbas** [wkentaro/labelme#635]
I followed this https://youtu.be/3kme_TdiwwU and started annotating my images with LabelMe. After Spending two days annotating it, finally got this information that LabelMe does not support tfrecord. 

I converted LabelMe annotations (from Json) to PASCALVOC with labelme2voc.py.. Thanks for that.

BUT labelme2voc.py does not generate ImageSets/Segmentation Folder containing lists for training and validation. 

I am following this script for converting VOC to tfrecord.
https://github.com/tensorflow/models/blob/master/research/deeplab/datasets/build_voc2012_data.py

Can you help?

There must be a tutorial on LabelMe and Tensorflow for Object Detection. All object detection tutorials refers to LabelImg and Tensorflow.

**Comment by wkentaro** [comment]
First of all, I'm not a TensorFlow user, so I haven't created such a tutorial before. If anyone created it, that would be great.

> labelme2voc.py does not generate ImageSets/Segmentation Folder containing lists for training and validation.

It's just a text file, so it's quite an easy task to create it, and nothing has to do with this annotation tool because normally people want to use their own split of training, testing and validation data.

**Comment by azeemabbas** [comment]
Can anyone help, that what would ImageSets/Segmentation look like if I have 2.jpg, 3.jpg and 4.jpg as training and 5.jpg,6.jpg as test.

I have created train.txt and test.txt that contains image name per line. But it does not work.

**Comment by wkentaro** [comment]
Probably without `.jpg` like this VOC example:
https://raw.githubusercontent.com/shelhamer/fcn.berkeleyvision.org/master/data/pascal/seg11valid.txt

**Comment by azeemabbas** [comment]
Thanks alot, 

The ImageSets/Segmentation/train.txt  contain names of images without .jpg
Similarly, the build_voc2012_data.py uses 

./VOCdevkit/VOC2012/SegmentationClassRaw
Replace it with 

./VOCdevkit/VOC2012/SegmentationClassPNG

In   build_voc2012_data.py file  use 
tf.compat.v1. 
instead of 
tf 
if you have currently installed tensorflow v2.
