### ISSUE TITLE
[BUG] Crash on editing a polygon label when new value is not in the label list

### ISSUE THREAD

**Issue by aksharpatel47** [wkentaro/labelme#636]
**Describe the bug**
When I edit the label on a polygon if the new label is not in the list of labels, the app crashes.
However, if I create a new polygon with the new label, I'm able to change the label on other polygons to the new label. The output of the crash:

`Traceback (most recent call last):
  File "c:\users\aksha\miniconda3\lib\site-packages\labelme\app.py", line 921, in editLabel
    item.setData(role=Qt.UserRole, value=shape.label)
TypeError: setData() takes no keyword arguments`

**To Reproduce**
1. Open a directory with labelme annotations
2. Try to edit the label on a polygon shape, to a value that is not a part of the label list

**Expected behavior**
The app should allow editing labels to any value even if it's not a part of the label list.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Labelme Version 4.2.9

**Comment by Javacr** [comment]
I have the same issue as you, but the version I used is 4.2.7

**Comment by wkentaro** [comment]
Released 4.2.10, please install it.

**Comment by wkentaro** [comment]
Closed via a8db0cfbf895994c555e0c67d9b3db46cbaabc0c
