### ISSUE TITLE
[Feature] Allow saving file with no annotations

### ISSUE THREAD

**Issue by aksharpatel47** [wkentaro/labelme#637]
**Is your feature request related to a problem? Please describe.**
When verifying labels on instance segmentation datasets, I frequently come across images for which
I need to remove all the annotations. When I now try to go to save the image, I get the popup saying that there are no objects labeled.

**Describe the solution you'd like**
I would suggest a solution where the app allows saving the file with no annotations and saves the annotation JSON with the `shapes` key as an empty array.

**Comment by wkentaro** [comment]
Makes sense :+1:

**Comment by aksharpatel47** [comment]
If you can point me in the right direction, I can try creating a pull request for this.

**Comment by wkentaro** [comment]
Well, just edit app.py accordingly. If you're not sure, please wait.

**Comment by josephdenieul** [comment]
Hi, sorry to open this issue again but is this commit implemented in the pip package ? I am trying to save images without any instances but labelme won't let me save them. Is there something to do in the configuration file ?
Many thanks !
