### ISSUE TITLE
[BUG]Image suffixes above 50000 Overflow

### ISSUE THREAD

**Issue by CarlisleJonah** [wkentaro/labelme#639]
**Describe the bug**
Image suffixes above 50000 overflow to lower indexes when saving labels.

**To Reproduce**
1. Save label of image with suffix above 50000

**Desktop (please complete the following information):**
 - OS: Windows 10
- Python 3.7.6
 - Labelme Version 4.2.9

Video of bug:
https://www.youtube.com/watch?v=BNmDn8arKoE

Edit:

I am using the same erroneous dataset as charlieLehman below, so that is the cause of the error.

**Comment by wkentaro** [comment]
I don't think this is because of the suffix..., but not sure why

**Comment by charlieLehman** [comment]
I just reproduced this and found something else related.  

In the above video auto-save is used.  If auto-save is not used then a new JSON file is not created.  Instead the imagePath is altered to the overflowed name.

Arch Linux
Python 3.8.2
Labelme Version 4.2.9

**Comment by wkentaro** [comment]
> Maybe something to enforce the imageDir to match the filename regardless of the presence of imageData?

I think it's inconvenient to be enforced imageDir to be same as the directory of JSON file.
