### ISSUE TITLE
Suppress one class/label from a dataset when producing VOC-dataset?

### ISSUE THREAD

**Issue by Asa-Nisi-Masa** [wkentaro/labelme#640]
Is it possible to generate VOC-style masks while ignoring a certain label? I am following [this](https://github.com/wkentaro/labelme/tree/master/examples/semantic_segmentation).

Say my labels.txt looks like

```
# labels.txt
__ignore__
_background_
dog
cat
```

and I have corresponding dataset with labelled dogs and cats. But say I don't want to produce masks for dogs right now - only cats. Removing `dogs` from `labels.txt` and running command found in the link above gives an error 

```
Traceback (most recent call last):
  File "./labelme2voc.py", line 105, in <module>
    main()
  File "./labelme2voc.py", line 87, in main
    label_name_to_value=class_name_to_id,
  File "/home/gytis/.local/lib/python3.6/site-packages/labelme/utils/shape.py", line 68, in shapes_to_label
    cls_id = label_name_to_value[cls_name]
KeyError: 'dog'
```

Is there a way to suppress a certain label?

**Comment by wkentaro** [comment]
You can add `continue` to somewhere in the Python script.

**Comment by Asa-Nisi-Masa** [comment]
> You can add `continue` to somewhere in the Python script.

In the end I did this:

```
# labelme2voc.py
# line 83
label_file.shapes = label_file.shapes[0:1]
```
to slice only the label I needed.
