### ISSUE TITLE
When i label two objects for example, in an image, a json file is saved , but only one json and not two.Why is this happening? Are the two labels in 1 json file, or better, does jsson file represent the objects which i labeled???[BUG]

### ISSUE THREAD

**Issue by geokalom** [wkentaro/labelme#643]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Labelme Version [e.g. 4.2.9]

**Additional context**

**Comment by wkentaro** [comment]
Are you asking if why each polygon label is stored in a different file?
If so, one image corresponds to one JSON file with multiple polygon labels.

**Comment by geokalom** [comment]
Υes i am. Ok i get it. Thanks for your response....
