### ISSUE TITLE
[Feature]Support label multi class by selecting and clicking

### ISSUE THREAD

**Issue by huiwenzhang** [wkentaro/labelme#647]
**Describe the solution you'd like**
For multi class labelling task, we may want to load labels from predefined file, e.g. a yaml file, then a dropout list will show in the window. Labelling an instance become easier by just selecting and clicking instead of typing.

**Comment by wkentaro** [comment]
This is already included. Please refer to the example. (--labels option)
https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation#annotation
