### ISSUE TITLE
[Feature] Import/Convert yolo annotation to labelme

### ISSUE THREAD

**Issue by x0rzkov** [wkentaro/labelme#650]
Hi guys,

Hope you are all well !

I found scripts to convert labelme to yolo so that's fine but I was wondering if there is a way to import a yolo custom dataset with annotation in .txt format to labelme ?

Thanks in advance for any insights or inputs on that topic.

Cheers,
X

**Comment by x0rzkov** [comment]
I fixed it, created my own script

**Comment by sakibk** [comment]
@x0rzkov Can You please share script you found that converts labelme to yolo?

**Comment by x0rzkov** [comment]
@sakibk 

I finally wrote it in golang but before I found these two references in python:
- https://github.com/ivder/LabelMeYoloConverter
- https://github.com/heleizj/LabelmeToYolo

Hope it helps you.

**Comment by sakibk** [comment]
@x0rzkov Thank you very much, I made it. 😊

**Comment by PaleNeutron** [comment]
> @sakibk
> 
> I finally wrote it in golang but before I found these two references in python:
> 
> * https://github.com/ivder/LabelMeYoloConverter
> * https://github.com/heleizj/LabelmeToYolo
> 
> Hope it helps you.

Why script process json format as text!

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel, you can import the YOLO text files and export to the Labelme JSON files.
https://rectlabel.com/help#yolo_to_xml
https://rectlabel.com/help#xml_to_labelme

Please give us your feedback about the combination of Labelme and RectLabel.

**Comment by gyupro** [comment]
You also need a feature to convert polygon format.

I created a repo to do so, https://github.com/gyupro/LabelMeToYoloSegmentation 

Take a look and give it a start please, ^^!

**Comment by adeel-maker** [comment]
I also made a pip package for converting Annotations of YOLO-TXT to Labelme-JSON:
[https://github.com/adeel-maker/yolotolabelme](url)
