### ISSUE TITLE
When I use labelme on win10, if the label is Chinese, it will be stored in ansi format, can I choose to store it in other encoding format? Such as utf-8?

### ISSUE THREAD

**Issue by 1428679766** [wkentaro/labelme#651]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wkentaro** [comment]
It seems this is Windows-specific problem since I don't see this on Linux and Mac.

**Comment by wuranran** [comment]
如何切换中文输入法，我在window 下使用切换不了
