### ISSUE TITLE
[BUG] cannot see the delete file icon

### ISSUE THREAD

**Issue by x0rzkov** [wkentaro/labelme#652]
Hi,

Hope you are all well !

I cannot see the "delete file" icon as per the screenshot below.
![alt text](https://raw.githubusercontent.com/wkentaro/labelme/master/examples/instance_segmentation/.readme/annotation.jpg)

How can I activate it ? Is there a specific flag for that ?

Cheers,
X

**Comment by wkentaro** [comment]
Is it supposed to exist?

**Comment by lucmichalski** [comment]
check the screenshot in the left corner

**Comment by wkentaro** [comment]
I see. I can also find that in my environment.
I don't think there's any flag or something.

**Comment by x0rzkov** [comment]
I am on Mac OSX

**Comment by wkentaro** [comment]
Please reopen if you still have this issue.
