### ISSUE TITLE
excuse me,How to convert background picture with no objection to coco datasets?

### ISSUE THREAD

**Issue by wangziyan1234** [wkentaro/labelme#653]

**Comment by cm107** [comment]
@wangziyan1234 
I'm not quite sure how to convert labelme annotations to a COCO dataset using the method proposed in the documentation here, but I created a conversion tool that I think has a lot more flexibility.

```console
pip install pyclay-annotation_utils
```

Here's an example of how to use it:
https://github.com/cm107/annotation_utils/blob/development/test/coco/labelme2coco_example.py

@wkentaro 
Does your COCO conversion tool account for Rectangle->Bounding Box, Polygon->Segmentation, and Point->Keypoint annotations?
If not, I think it would be pretty easy to integrate my package into yours.

Here's a usage walkthrough that I wrote.
https://hackmd.io/@cm107/labelme_walkthrough
