### ISSUE TITLE
[BUG] shift_auto_shape_color config for semantic segmentation on Windows 10 not working

### ISSUE THREAD

**Issue by coded5282** [wkentaro/labelme#657]
- OS: Windows 10
- Labelme Version: 4.2.10

The "shift_auto_shape_color" config doesn't seem to be working. I'm on Windows 10 and am running this command (based on the semantic segmentation example):

```
labelme data_annotated --labels labels.txt --nodata --validatelabel exact --config                               
 '{shift_auto_shape_color: -2}'
```

I end up getting this error:
```
usage: labelme [-h] [--version] [--reset-config]
               [--logger-level {debug,info,warning,fatal,error}]
               [--output OUTPUT] [--config CONFIG] [--nodata] [--autosave]
               [--nosortlabels] [--flags FLAGS] [--labelflags LABEL_FLAGS]
               [--labels LABELS] [--validatelabel {exact,instance}]
               [--keep-prev] [--epsilon EPSILON]
               [filename]
labelme: error: unrecognized arguments: -2}'
```

Is this a bug or something wrong with how I'm using it? Thanks.

**Comment by wkentaro** [comment]
I'm not sure about Windows, but have you tried with double quote? `"{shift_auto_shape_color: -2}"`

**Comment by coded5282** [comment]
@wkentaro Thanks for your response! Yes, I've tried that and get:

```
labelme data_annotated --labels labels.txt --nodata --validatelabel exact --config "{shift_auto_shape_color: -2}"
[33m[WARNING][0m Skipping unexpected key in config: shift_auto_shape_color ([1m__init__.py[0m:18)
```

**Comment by wkentaro** [comment]
Then, you probably need to upgrade it.

**Comment by hyungju-song** [comment]
HI @wkentaro

Through your code, I was able to finish labeling successfully.  Thank you. 

But there is a small problem.

I am having the same problem like @coded5282 

**So could you please explain which upgrade means?**

Thanks in advance.

**OS: Window10
LabelMe version: 4.5.6**
