### ISSUE TITLE
Possibly unused code

### ISSUE THREAD

**Issue by tianjiaoding** [wkentaro/labelme#66]
https://github.com/wkentaro/labelme/blob/58693e6e9b485c6c61c704095a0f5620d31f2c8a/labelme/app.py#L124
in labelme/app.py
line 117 - 125 
`        listLayout = QVBoxLayout()
        listLayout.setContentsMargins(0, 0, 0, 0)
        listLayout.addWidget(self.labelList)
        self.editButton = QToolButton()
        self.editButton.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        self.labelListContainer = QWidget()
        self.labelListContainer.setLayout(listLayout)
        listLayout.addWidget(self.editButton)#, 0, Qt.AlignCenter)
        listLayout.addWidget(self.labelList)`

1. The _listLayout_ added _self.labelList_ twice.
2. The _listLayout_ added _self.editButton_, but I didn't see the button in the polygon labels dock. I tested by drawing multiple polygons and delete them, however, there's no sign of this button. Maybe I didn't cover the right usage.
3. The app works the same if I delete the last two lines of the snippet.

git blame shows that the code was introduced like 6 years ago. The readability will be improved if unused code is deleted.

**Comment by RunningCool** [comment]
My apologies. I just turned on advanced mode and saw the edit button. However, I don't quite understand the purpose of adding _self.labelList_ twice. Could someone please explain this a little bit?

**Comment by wkentaro** [comment]
Hmm, sorry, but that's not where I wrote. And I can't explain it at this moment.

**Comment by wkentaro** [comment]
I found you're right, and the line can be removed.
This will be resolved via #121

**Comment by tianjiaoding** [comment]
Thanks for checking, though it’s a minor problem. I discovered that when making my own fork to adapt the tool to label images from multiple cameras. I will release that tool and acknowledge this repository. :)

**Comment by wkentaro** [comment]
Yeah, nice catch. Thanks!
