### ISSUE TITLE
[Feature]Navigation improvements

### ISSUE THREAD

**Issue by eVen-gits** [wkentaro/labelme#660]
**Is your feature request related to a problem? Please describe.**
It is hard to annotate large images with small features. Mainly because in order to move the zoomed view, the drag bars need to be used (small on some desktop environments).

**Describe the solution you'd like**
A standard way to move pan window - middle mouse drag do move pan area.

Furthermore, smoothing would be welcome (when zooming/panning), so that it's easier to follow features displayed in the photo.

**Comment by wkentaro** [comment]
Moved to https://github.com/wkentaro/labelme/issues/660
