### ISSUE TITLE
[BUG] Labelme2voc.py can't convert JSON to XML using binary image (mask image)

### ISSUE THREAD

**Issue by TiasM** [wkentaro/labelme#669]
Hi, i'd like to ask
when i try to make XML bounding-box annotation from mask image (binary image), the labelme2voc.py genereate an error while converting the JSON file to XML 

What i did:
1. Provide mask image (binary image) to data_annotated folder
2. Open labelme.exe to make the bounding-box and generate the JSON file
3. Run the labelme2voc.py file
4. Got error. This is the screenshot of the error
![image](https://user-images.githubusercontent.com/45141188/83030883-19e48c80-a05e-11ea-8ccd-3699b9c5a9ee.png)

this is the sample of image i am using:
![image](https://user-images.githubusercontent.com/45141188/83031485-ce7eae00-a05e-11ea-90fd-ce970c6f1d5d.png)
and this is the original image:
![image](https://user-images.githubusercontent.com/45141188/83031613-f9690200-a05e-11ea-8e82-971a939ce40f.png)

Does this has anything to do with the binary image itself ? Because i tried using the original image (colored) and it works just fine. Not sure what's wrong

Note : 
1. The binary mask image i am using is from http://groups.inf.ed.ac.uk/f4k/GROUNDTRUTH/RECOG/
2. I personally modify the labelme2voc.py a little bit (so it can read and generate .PNG image file instead of .JPG because the dataset i am using are all using .PNG format, but that's all that i change, not more)

Thank You, and sorry for the bad english.

**Comment by wkentaro** [comment]
It worked with no error on my env.
![image](https://user-images.githubusercontent.com/4310419/85444019-cf393000-b589-11ea-83e7-bb2c0fcf86f4.png)

**Comment by TiasM** [comment]
Hi, thanks for the reply.After i read some discussion on the web, seems like problem is caused by the binary image itself which can't be process by PIL. However i'm not sure why it's working on your env.

Since i already find the way to work around this problem for my case, it's ok now. I'll just close the issue, Thank You :)
