### ISSUE TITLE
consistency of label colors to multiple images 

### ISSUE THREAD

**Issue by mwangaz** [wkentaro/labelme#67]
I have a question about using labelme to create image labels for training the fully convolutional network (FCN). I find the color of the label depends on the order of creating the polygon: 2 objects will be labelled with red and green color. But what if I have another 2 different objects on an new image? The label color for them will still be red and green, which would affect the label images for training the segmentation model. How can I make sure the label color of the same object on different images is the same? Thanks.

**Comment by wkentaro** [comment]
I usually create a python script that converts all label images to have the consistent label value.
Maybe I will create a sample in a few weeks if I have time.

**Comment by NiklasDL** [comment]
Any news regarding this issue? I am also trying to label multiple images for segmentation but apparently the coloring pattern differentiates from image to image.

**Comment by wkentaro** [comment]
You can use `labelme2voc.py`: https://github.com/wkentaro/labelme/blob/master/examples/semantic_segmentation/labelme2voc.py
The output is the consistent colors of labels: 

![](https://github.com/wkentaro/labelme/raw/master/examples/semantic_segmentation/data_dataset_voc/SegmentationClassPNG/2011_000003.png)
![](https://github.com/wkentaro/labelme/blob/master/examples/semantic_segmentation/data_dataset_voc/SegmentationClassPNG/2011_000006.png?raw=true)

**Comment by shivarajkarki** [comment]
Thank you, it worked
