### ISSUE TITLE
how to solve this problem?

### ISSUE THREAD

**Issue by Aiz-wallenstein** [wkentaro/labelme#673]
usage: labelme2coco.py [-h] --labels LABELS input_dir output_dir
labelme2coco.py: error: the following arguments are required: input_dir, output_dir, --labels

**Comment by wkentaro** [comment]
you need to provide arguments. 
https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation#convert-to-coco-format-dataset

**Comment by Aiz-wallenstein** [comment]
I know that. and i have try, but it not work. So ,can you tell me  in detail. thanks
