### ISSUE TITLE
[BUG] labelme does not read jpg images

### ISSUE THREAD

**Issue by off99555** [wkentaro/labelme#675]
**Describe the bug**
In version 4.2.9, it still reads the jpg images. But after I upgraded to >=4.3, it stops reading the jpg images. You can see clearly this issue by trying to open an image and in the list of image types, you won't find the jpg in there.

**To Reproduce**
1. Install labelme 4.3 using `pip install labelme==4.3` or any latest version
2. Try to open the image with Open button.
3. You will find out that you won't see jpg images.

**Expected behavior**
The jpg images must be seen.

**Screenshots**
This is an example of version 4.2.9 (which have jpg type in the list)
![image](https://user-images.githubusercontent.com/15215732/84859800-0a25fa00-b098-11ea-8ccd-54f084357cf1.png)

This is version 4.5.1 (does not have jpg in the list)
![image](https://user-images.githubusercontent.com/15215732/84859741-f11d4900-b097-11ea-83c0-0925e78d8598.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Labelme Version > 4.3

**Additional context**
Maybe this is an intended feature because it cannot be a mistake that some guys decided to remove jpg and other extensions from the list. But then why do this? It causes a backward compatibility issue.

**Comment by azibit** [comment]
I am experiencing the same exact issue. My boss has labeled some images and wants me to label the rest. Now I cannot open the files as they are jpg. I guess I must downgrade to get this to work for now

**Comment by CodePothunter** [comment]
Experiencing the same problem ...

**Comment by sakibk** [comment]
Experiencing the same problem on mac, it does not want to load *.jpg or *.heic

**Comment by wkentaro** [comment]
Can you guys give me the output of below command?
```
ipython

In [1]: from qtpy import QtGui

In [2]: QtGui.QImageReader.supportedImageFormats()
Out[2]:
[PyQt5.QtCore.QByteArray(b'bmp'),
 PyQt5.QtCore.QByteArray(b'cur'),
 PyQt5.QtCore.QByteArray(b'gif'),
 PyQt5.QtCore.QByteArray(b'heic'),
 PyQt5.QtCore.QByteArray(b'heif'),
 PyQt5.QtCore.QByteArray(b'icns'),
 PyQt5.QtCore.QByteArray(b'ico'),
 PyQt5.QtCore.QByteArray(b'jp2'),
 PyQt5.QtCore.QByteArray(b'jpeg'),
 PyQt5.QtCore.QByteArray(b'jpg'),
 PyQt5.QtCore.QByteArray(b'pbm'),
 PyQt5.QtCore.QByteArray(b'pgm'),
 PyQt5.QtCore.QByteArray(b'png'),
 PyQt5.QtCore.QByteArray(b'ppm'),
 PyQt5.QtCore.QByteArray(b'svg'),
 PyQt5.QtCore.QByteArray(b'svgz'),
 PyQt5.QtCore.QByteArray(b'tga'),
 PyQt5.QtCore.QByteArray(b'tif'),
 PyQt5.QtCore.QByteArray(b'tiff'),
 PyQt5.QtCore.QByteArray(b'wbmp'),
 PyQt5.QtCore.QByteArray(b'webp'),
 PyQt5.QtCore.QByteArray(b'xbm'),
 PyQt5.QtCore.QByteArray(b'xpm')]
```
on my mac, it gives jpeg as well.

**Comment by off99555** [comment]
@wkentaro 
![image](https://user-images.githubusercontent.com/15215732/85279032-01765f00-b4b0-11ea-9261-2851e6ceb12f.png)
Here it is. Though the labelme version is 4.2.9

**Comment by sakibk** [comment]
![image](https://user-images.githubusercontent.com/5898766/85298661-aa1ec180-b4a4-11ea-9ad0-2634a45befc7.png)
Here it goes, labelme -V 4.5.0

**Comment by wkentaro** [comment]
> @wkentaro
> ![image](https://user-images.githubusercontent.com/15215732/85279032-01765f00-b4b0-11ea-9261-2851e6ceb12f.png)
> Here it is. Though the labelme version is 4.2.9

So this issue is probably related to your PyQt5 version or something not labelme version.
Please check the PyQt5 version to see when jpeg will be listed.

**Comment by wkentaro** [comment]
> ![image](https://user-images.githubusercontent.com/5898766/85298661-aa1ec180-b4a4-11ea-9ad0-2634a45befc7.png)
> Here it goes, labelme -V 4.5.0
> 
> `[ERROR ] label_file:load_image_file:39 - Failed opening image file: /Users/sakibkurtic/Desktop/Horizontal_Traffic_Sign_Train_Data/0420.jpg`
> 
> This is detailed error I got.

There's jpeg, but still you can't open it?

**Comment by sakibk** [comment]
> > ![image](https://user-images.githubusercontent.com/5898766/85298661-aa1ec180-b4a4-11ea-9ad0-2634a45befc7.png)
> > Here it goes, labelme -V 4.5.0
> > `[ERROR ] label_file:load_image_file:39 - Failed opening image file: /Users/sakibkurtic/Desktop/Horizontal_Traffic_Sign_Train_Data/0420.jpg`
> > This is detailed error I got.
> 
> There's jpeg, but still you can't open it?

![image](https://user-images.githubusercontent.com/5898766/85326780-1cf06280-b4ce-11ea-94ef-e0f8b4538346.png)
Here is the image folder with images. I am able to load images with labelme version 3.5, but any later does not work.

**Comment by wkentaro** [comment]
@sakibk "does not work" means there's no jpeg listed in the OpenFile dialog? as in here? https://github.com/wkentaro/labelme/issues/675#issue-630578377

**Comment by wkentaro** [comment]
> Here it goes, labelme -V 4.5.0
[ERROR ] label_file:load_image_file:39 - Failed opening image file: /Users/sakibkurtic/Desktop/Horizontal_Traffic_Sign_Train_Data/0420.jpg

If you're talking about this, this seems a different issue, so can you open another issue?

**Comment by off99555** [comment]
> > @wkentaro
> > ![image](https://user-images.githubusercontent.com/15215732/85279032-01765f00-b4b0-11ea-9261-2851e6ceb12f.png)
> > Here it is. Though the labelme version is 4.2.9
> 
> So this issue is probably related to your PyQt5 version or something not labelme version.
> Please check the PyQt5 version to see when jpeg will be listed.

Following is the version of `qtpy` when labelme is 4.2.9
![image](https://user-images.githubusercontent.com/15215732/85337150-28617f00-b50a-11ea-9c00-2b4f08103606.png)
I also tried to install labelme 4.5.3, I still see the same qtpy version: 1.9.0

I have also reproduced this problem in another person's PC. So this problem is related to the labelme version.

Note that I don't see `jpg` in the list from Qtpy but I see `jpg` in the list of file extension in labelme 4.2.9. So the list of extensions that you saw from qtpy above does not match the list from labelme.
I'm suspecting that you are probably not using qtpy in labelme 4.2.9 then later you use it. That's a clue from me.

**Comment by wkentaro** [comment]
Can you check the version of PyQt5 instead of qtpy? qtpy is just a wrapper.

**Comment by wkentaro** [comment]
> I'm suspecting that you are probably not using qtpy in labelme 4.2.9 then later you use it. That's a clue from me.
If the list from Qtpy should match with the list from labelme, then we have found the bug.

Actually, both 4.2.9 and 4.5.3 use qtpy. And the logic in `app.openFile` was not changed.
Can you try 4.2.10 as well to see when it happens? Or something below to find where the error happens 
```
git clone https://github.com/wkentaro/labelme
cd labelme
git checkout v4.2.10
pip install -e .
labelme examples/semantic_segmentation  # check if jpeg is read
git checkout HEAD~1  # previous version
labelme examples/semantic_segmentation  # check if jpeg is read
git checkout HEAD~1  # previous version
labelme examples/semantic_segmentation  # check if jpeg is read
...
```

**Comment by off99555** [comment]
> Can you check the version of PyQt5 instead of qtpy? qtpy is just a wrapper.

Here it is:
```
>>> from PyQt5.Qt import PYQT_VERSION_STR
>>> PYQT_VERSION_STR
'5.9.2'
```
I am not sure if that's the right way to check the version. I just found it from a thread in Quora.

Anyway, the PyQt5 version is the same when I uninstall labelme 4.2.9 and install 4.5.3

**Comment by off99555** [comment]
![image](https://user-images.githubusercontent.com/15215732/85338345-4d56f180-b50c-11ea-996a-d80b4b1f2bbd.png)
Here's the extension list from 4.2.10

**Comment by wkentaro** [comment]
> Anyway, the PyQt5 version is the same when I uninstall labelme 4.2.9 and install 4.5.3

I see. What is the output of `QImageReader.supportedImageFormats()` in 4.2.10?

**Comment by off99555** [comment]
> > Anyway, the PyQt5 version is the same when I uninstall labelme 4.2.9 and install 4.5.3
> 
> I see. What is the output of `QImageReader.supportedImageFormats()` in 4.2.10?

Exact same as 4.2.9

**Comment by wkentaro** [comment]
So there's no jpeg .. strange. I'm not sure why jpeg could be listed in openFile with it.

**Comment by off99555** [comment]
Can you check the difference between 4.3.0 and 4.2.10. Because that's where the problem happens. 4.3.0 does not have jpg.

**Comment by off99555** [comment]
Here is some more info:
- I use anaconda 3.7.6
- I install using pip install
- I install in non-admin mode.

**Comment by wkentaro** [comment]
> Can you check the difference between 4.3.0 and 4.2.10? Because that's where the problem happens. 4.3.0 does not have jpg.

I almost know which code change made this happen, but I'm not sure why this could happen.
Anyway, can you check this PR? #697

**Comment by off99555** [comment]
> > Can you check the difference between 4.3.0 and 4.2.10? Because that's where the problem happens. 4.3.0 does not have jpg.
> 
> I almost know which code change made this happen, but I'm not sure why this could happen.
> Anyway, can you check this PR? #697

Yep. That PR shows all the long extension list. It seems to work.

**Comment by nanase-123** [comment]
In labelme V5.5.0,i meet the same question which does not have jpg in the openlist.please help me to analyze the reason.
