### ISSUE TITLE
[BUG] How to drag/edit the rectangle?

### ISSUE THREAD

**Issue by sdfghjkyuio** [wkentaro/labelme#689]
**Describe the bug**
I change the order in the Polygon Labels Dialog since I want to drag the small rectangle,  but the original rectangle is still there (which should be removed), so there are two identical rectangles on the image.

**Screenshots**
![捕获](https://user-images.githubusercontent.com/67036136/84881011-e1195f80-b0bf-11ea-9303-4b6f1cf39ef3.PNG)

**Expected behavior**
It would be better if the polygon label corresponding to the yellow rectangle is clicked, then the yellow rectangle can be topped so it can be moved or editted freely.

![捕获2](https://user-images.githubusercontent.com/67036136/84852019-59672d00-b08e-11ea-8f1d-41acad7fc78e.PNG)

 - OS: Windows 10
 - Labelme Version 4.5.0

**Comment by sdfghjkyuio** [comment]
Thank you!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kentaro Wada"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 上午9:03
收件人:&nbsp;"wkentaro/labelme"<labelme@noreply.github.com&gt;;
抄送:&nbsp;"一叶知秋"<582458933@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wkentaro/labelme] [BUG] How to drag/edit the rectangle? (#689)





 
Closed #689 via #696.

**Comment by wkentaro** [comment]
Thanks for the bug report!
