### ISSUE TITLE
label.png is a black image

### ISSUE THREAD

**Issue by simonsayshi** [wkentaro/labelme#69]
Hi all
the sample apc2016_obj3.png generated by  labelme_json_to_data is a totally black image, how can it be a label image for a FCN model?

**Comment by wkentaro** [comment]
It is black image because the label values like `0, 1, 2, 3` is very low value compared to normal values like `255, 127`.
You should load it by `PIL.Image` and `numpy`, and use `skimage.color.label2rgb` to visualize it.

**Comment by wkentaro** [comment]
I'm not sure, but probably, `plt.imshow(np.asarray(PIL.Image.open('label.png')));plt.show()` works.

**Comment by simonsayshi** [comment]
thanks for reply, but perhaps I was not clear enough
for example, if I'm going to train a FCN model by using your images, so the label.png in your tutorial/apc2016_obj3_json can be the ground truth image for apc2016_obj3.jpg? but it is a black image(like you said the pixel value is very low), unlike the label images in VOC2012 dataset, the object and the background is obvious(like the bicycle man, the body, bike and background have different color ). Maybe I missed something..... but I don't think the black label.png can be the ground truth for training 


![2007_000039](https://user-images.githubusercontent.com/31574218/36947128-eacb0406-1f95-11e8-8bc2-6cd983c01a8f.png)

**Comment by wkentaro** [comment]
Hmm, maybe you have several misunderstandings.
I think firstly you should learn about how to train FCN by reading:
paper: https://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Long_Fully_Convolutional_Networks_2015_CVPR_paper.pdf
code: https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/voc_layers.py#L113
my chainer implementation: https://github.com/wkentaro/fcn/blob/master/fcn/datasets/voc.py#L74-L76
