### ISSUE TITLE
Customized Annotation

### ISSUE THREAD

**Issue by RaghavaAlajangi** [wkentaro/labelme#691]
@wkentaro 
I would like to convert a group of images into list of JSON files automatically with each JSONfile having 3 default polygons and respective remaining data such as ImageData and shape of the image so that I can modify the each polygon there after with some list of points. I tried to create JSON files manually but I don't know how to generate ImageData: key value pair from the image. Please help me out ion this matter.  
Thank you

**Comment by wkentaro** [comment]
```
imageData = open("image.jpg", "rb").read()
imageData = base64.b64encode(imageData).decode("utf-8")
```

**Comment by RaghavaAlajangi** [comment]
Thank you for your reply.
Could you please share the code to convert .png file to .json file with 2 default polygons with list of n no of points? I tried but its throwing lot of errors.

**Comment by wkentaro** [comment]
> I tried but its throwing lot of errors.

Can you share the code and errors?

**Comment by RaghavaAlajangi** [comment]
imageData = open(file, "rb").read()
    imageData = base64.b64encode(imageData).decode("utf-8")
    #print(imageData)
    filename = os.path.basename(file).replace('.png', '.json')
    path = os.path.join(json_path, filename)
    if os.path.exists(path) is False:
          json_dict = {}
          json_dict['version'] = "4.4.0"
          json_dict['flags']  =  {}
          json_dict['shapes'] = [{"label": "partner_A",
                                  "points": [point for point in poly1],
                                  #"group_id": 0,
                                  "shape_type": "polygon",
                                  "flags": {}
                                  },
                                 {"label": "seam",
                                  "points": [point for point in poly2],
                                  #"group_id": 0,
                                  "shape_type": "polygon",
                                  "flags": {}
                                  },
                                 {"label": "partner_B",
                                  "points": [point for point in poly3],
                                  #"group_id": 0,
                                  "shape_type": "polygon",
                                  "flags": {}
                                  }
                                 ]
          json_dict['imagePath'] = str(file)
          json_dict['imageData'] = imageData
          json_dict['imageHeight'] = str(270)
          json_dict['imageWidth'] = str(270)
          with open(path, 'w') as handle:
              json.dump(json_dict, handle, indent=2)

**Comment by RaghavaAlajangi** [comment]
imageData = open(file, "rb").read()
    imageData = base64.b64encode(imageData).decode("utf-8")
    #print(imageData)
    filename = os.path.basename(file).replace('.png', '.json')
    path = os.path.join(json_path, filename)
    if os.path.exists(path) is False:
          json_dict = {}
          json_dict['version'] = "4.4.0"
          json_dict['flags']  =  {}
          json_dict['shapes'] = [{"label": "poly1",
                                  "points": [point for point in poly1],
                                  #"group_id": 0,
                                  "shape_type": "polygon",
                                  "flags": {}
                                  },
                                 {"label": "poly2",
                                  "points": [point for point in poly2],
                                  #"group_id": 0,
                                  "shape_type": "polygon",
                                  "flags": {}
                                  },
                                 {"label": "poly3",
                                  "points": [point for point in poly3],
                                  #"group_id": 0,
                                  "shape_type": "polygon",
                                  "flags": {}
                                  }
                                 ]
          json_dict['imagePath'] = str(file)
          json_dict['imageData'] = imageData
          json_dict['imageHeight'] = str(270)
          json_dict['imageWidth'] = str(270)
          with open(path, 'w') as handle:
              json.dump(json_dict, handle, indent=2)

**Comment by wkentaro** [comment]
https://gist.github.com/wkentaro/833fdc921b51a0fa2285cbf8e36d6e24

**Comment by RaghavaAlajangi** [comment]
Thanks a lot
