### ISSUE TITLE
single Labelling

### ISSUE THREAD

**Issue by heizie** [wkentaro/labelme#694]
**Is your feature request related to a problem? Please describe.**
I always need to click the yes button to select a single label. for example I've only one class, name human. So in each pictures I'll need to click "ok" to choose "human"

**Describe the solution you'd like**
single label mode, without enter

**Comment by wkentaro** [comment]
You can use `labelme --config '{display_label_popup: false}'`, and when annotating, you first select 'human' label from the label list.

**Comment by heizie** [comment]
thanks for your reply.
May i ask, if i want to keep using same label with same group id, is it possible?

**Comment by heizie** [comment]
> You can use `labelme --config '{display_label_popup: false}'`, and when annotating, you first select 'human' label from the label list.
thanks for your reply.
May i ask, if i want to keep using same label with same group id, is it possible?

so there is another suggestion. Maybe we could label for the human pose with specific mode.
It'll like changing the default label (left shoulder, right shoulder...) so that we could save amount of time to switching for the label and group id. 
I think this kind of label task should be the most unsupported.

**Comment by wkentaro** [comment]
> keep using same label with same group id, is it possible?

default group id is None, so it is the same, right?

**Comment by wkentaro** [comment]
> > You can use `labelme --config '{display_label_popup: false}'`, and when annotating, you first select 'human' label from the label list.
> > thanks for your reply.
> > May i ask, if i want to keep using same label with same group id, is it possible?
> 
> so there is another suggestion. Maybe we could label for the human pose with specific mode.
> It'll like changing the default label (left shoulder, right shoulder...) so that we could save amount of time to switching for the label and group id.
> I think this kind of label task should be the most unsupported.

In that case, you always annotate in a specific order? like left-shoulder first and right-shoulder second? In this case, line-strip would be fine (you can change mode of LabelMe). The problem with this would be how to handle the case where we can't see the left-shoulder in the image. (in this case 1st point in line-strip would indicate right-shoulder).

 I need to understand what is the specific procedure of annotation.

**Comment by wkentaro** [comment]
> > > You can use `labelme --config '{display_label_popup: false}'`, and when annotating, you first select 'human' label from the label list.
> > > thanks for your reply.
> > > May i ask, if i want to keep using same label with same group id, is it possible?
> > 
> > 
> > so there is another suggestion. Maybe we could label for the human pose with specific mode.
> > It'll like changing the default label (left shoulder, right shoulder...) so that we could save amount of time to switching for the label and group id.
> > I think this kind of label task should be the most unsupported.
> 
> In that case, you always annotate in a specific order? like left-shoulder first and right-shoulder second? In this case, line-strip would be fine (you can change mode of LabelMe). The problem with this would be how to handle the case where we can't see the left-shoulder in the image. (in this case 1st point in line-strip would indicate right-shoulder).
> 
> I need to understand what is the specific procedure of annotation and edge cases.

For further discussion, can you open a new issue for this?
