### ISSUE TITLE
[BUG] Cannot open JPEG

### ISSUE THREAD

**Issue by sakibk** [wkentaro/labelme#699]
**Describe the bug**
Labelme v4.5 does not want to load *.jpg or *.heic. I can see them in the picker view, and it does allow me to select it, but it does not want to load. 

**To Reproduce**

You will find out that you won't see jpg images.
1. Install Labelme 4.5.0 using pip3 install labelme
2. Click on OpenDir/Open
3. Choose Dir or single image in .jpg or .heic format
4. Observe error

**Expected behavior**
The jpg images must be seen.

**Screenshots**
Here is the folder structure with image names and format.
![image](https://user-images.githubusercontent.com/5898766/85702156-67e0c480-b6de-11ea-854d-4afe56da8d9e.png)

Here is the error I get
![image](https://user-images.githubusercontent.com/5898766/85702571-d6be1d80-b6de-11ea-9eb9-bffb44e13b65.png)

List of applicable image formats
![image](https://user-images.githubusercontent.com/5898766/85702261-847cfc80-b6de-11ea-94ad-854b153e88fc.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina v10.15.5
 - Labelme Version [v4.5]

**Additional context**
[ERROR ] label_file:load_image_file:39 - Failed opening image file: /Users/sakibkurtic/Desktop/Horizontal_Traffic_Sign_Train_Data/0420.jpg
This is a detailed console error I got.

**Comment by wkentaro** [comment]
Can you try old versions as well? e.g., 4.4, 4.3

**Comment by wkentaro** [comment]
Can you also try below in your IPython.
```python
import PIL.Image
PIL.Image.open("/Users/sakibkurtic/Desktop/Horizontal_Traffic_Sign_Train_Data/0420.jpg")
```
