### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by alinecespindola** [wkentaro/labelme#700]
To get the mask of several images you need to use the labelme2voc.py, but how can I include the inputs into the code? (input_dir, output_dir, --labels)

![image](https://user-images.githubusercontent.com/51926293/85738622-147b7000-b6f8-11ea-9f55-dde9fe90289b.png)

PS C:\Users\aline> conda activate labelme
PS C:\Users\aline> & C:/Users/aline/Anaconda3/envs/labelme/python.exe c:/Users/aline/semantic_segmentation/labelme2voc.py
usage: labelme2voc.py [-h] --labels LABELS [--noviz] input_dir output_dir
labelme2voc.py: error: the following arguments are required: input_dir, output_dir, --labels

**Comment by twinsben94** [comment]
Sir,, I have a same problem. May I ask how did you solve this problem?? I really want to solve it ....
