### ISSUE TITLE
Easy way to change color of a label [Feature]

### ISSUE THREAD

**Issue by beyse** [wkentaro/labelme#702]
**Is your feature request related to a problem? Please describe.**
To the best of my knowledge, the graphical user interface does not provide an easy way to change the color of a label.

**Describe the solution you'd like**
My suggestion is to have a context menu that opens up if the user clicks on a label in the 'Label List' on the right. The context menu could have an entry that is called 'change color'. This opens up a color selection dialog or at least lets you enter the RGB or HEX code of a color. 

**Describe alternatives you've considered**
An alternative option could be to add an entry in the context menu that opens up if you right click on a polygon (or circle, or rectangle) and provide the color change option in there.

**Additional context**
![labelme-screeny](https://user-images.githubusercontent.com/5306790/85865983-05172800-b7c7-11ea-9e1a-dbe320fa7260.png)

**Comment by wkentaro** [comment]
I think you can try version 3 of Labelme, in which you have this feature.

```
pip install labelme==3.22.2
```

**Comment by wkentaro** [comment]
But just curious, why do you want to change the color of polygon?

**Comment by wkentaro** [comment]
If the reason is just that the red color is hard to see on the grapes, you can use
```
labelme data_annotated/ --config '{shift_auto_shape_color: 1}'
```

**Comment by beyse** [comment]
Thank you for the reply. 
Yes, I find the color of the already annotated circles very hard to see on the red grapes.
I have tried out the second solution you suggested. However I geht the following error:

```
(labelme) C:\Users\<username>\Documents>labelme --labels "grape" --config '{shift_auto_shape_color: 1}'
Traceback (most recent call last):
  File "c:\anaconda3\envs\labelme\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\labelme\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\labelme\Scripts\labelme.exe\__main__.py", line 7, in <module>
  File "c:\anaconda3\envs\labelme\lib\site-packages\labelme\__main__.py", line 145, in main
    config = get_config(config_file_or_yaml, config_from_args)
  File "c:\anaconda3\envs\labelme\lib\site-packages\labelme\config\__init__.py", line 67, in get_config
    config_from_yaml = yaml.safe_load(config_file_or_yaml)
  File "c:\anaconda3\envs\labelme\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "c:\anaconda3\envs\labelme\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\anaconda3\envs\labelme\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "c:\anaconda3\envs\labelme\lib\site-packages\yaml\composer.py", line 35, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "c:\anaconda3\envs\labelme\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "c:\anaconda3\envs\labelme\lib\site-packages\yaml\parser.py", line 143, in parse_implicit_document_start
    StreamEndToken):
  File "c:\anaconda3\envs\labelme\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "c:\anaconda3\envs\labelme\lib\site-packages\yaml\scanner.py", line 247, in fetch_more_tokens
    return self.fetch_single()
  File "c:\anaconda3\envs\labelme\lib\site-packages\yaml\scanner.py", line 652, in fetch_single
    self.fetch_flow_scalar(style='\'')
  File "c:\anaconda3\envs\labelme\lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "c:\anaconda3\envs\labelme\lib\site-packages\yaml\scanner.py", line 1151, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_spaces(double, start_mark))
  File "c:\anaconda3\envs\labelme\lib\site-packages\yaml\scanner.py", line 1239, in scan_flow_scalar_spaces
    "found unexpected end of stream", self.get_mark())
yaml.scanner.ScannerError: while scanning a quoted scalar
  in "<unicode string>", line 1, column 1:
    '{shift_auto_shape_color:
    ^
found unexpected end of stream
  in "<unicode string>", line 1, column 26:
    '{shift_auto_shape_color:
                             ^
```

I will now try your first suggested sulution, that is using version 3 of LabelMe

**Comment by beyse** [comment]
So, I tried version 3 which has the feature I needed. Thank you very much for your help. In my humble opionion, this feature is a must for LabelMe, this leads me to the question: is there a good reason not to always use version 3 of LabelMe?

**Comment by wkentaro** [comment]
> this feature is a must for LabelMe

When do you think this feature is useful? If you have many classes (e.g., ~40) it seems quite unreasonable to modify color for each annotation. I think automating the colors with `shift_auto_shape_color` can be comfortable in most case.

**Comment by wkentaro** [comment]
BTW, have you tried with double quote? Do you know why it does not work on Windows?
```
labelme --labels "grape" --config "{shift_auto_shape_color: 1}"
```

**Comment by beyse** [comment]
No, I have not tried it with double quote. I will do it and let you know. As far as my knowledge goes single quote and double quote should both work just fine on Windows.

**Comment by beyse** [comment]
> > this feature is a must for LabelMe
> 
> When do you think this feature would be useful? If you have many classes (e.g., ~40) it seems quite unreasonable to modify color for each annotation. I think automating the colors with `shift_auto_shape_color` can be more comfortable in most case.

As a user that would like to create annotations in an easy and fast way, I would expect that feature. For example because I find it easier to think a certain class naturally is linked to a certain color or not linked to the preselected color. My other reasoning behind this is, that I draw stuff onto an image. It is of course no piece of art, but every time a computer program lets me draw something onto a canvas, it also let's me choose the color. There can be exceptions of course, but the majority of programs does and I believe the majority of users does expect it. When it comes to user experience, one golden rule is to minimize the surprises of the UI to the user. In my opinion drawing something without being able to change the color is a surprise and should therefore at least be questioned. 

While it is true that picking a color for each of class out of 40 classes is tedious, I think the arguments hold that a user at least would like to change a few of the colors.

**Comment by beyse** [comment]
> BTW, have you tried with double quote? Do you know why it does not work on Windows?
> 
> ```
> labelme --labels "grape" --config "{shift_auto_shape_color: 1}"
> ```

So, I have tried running the command with double quotes and it works without error. So the problem indeed was the single quote.

**Comment by karenscientist** [comment]
Hi @wkentaro @beyse 

I'm a beginner in Labelme and i'm doing a 300 photos dataset , each photo with approximately 5 different labels. I would need all kind of labels (e.g.: vehicle = red, people=green, traffic_signs=yellow) were the same colour in all of photos?.  This command could help me?

labelme --labels "xxx" --config "{shift_auto_shape_color: x}"

thanks a lot!

**Comment by wkentaro** [comment]
In that case, you can try

```
# labelme --labels "vehicle,people,traffic_signs"  --config "{shift_auto_shape_color: 0}"
# or below (shift_auto_shape_color is 0 by default)
labelme --labels "vehicle,people,traffic_signs" 
```

**Comment by karenscientist** [comment]
@wkentaro 

Thank you for your quickly response. I'll try and I'll let you know. 

 
In that case, you can try
> 
> ```
> # labelme --labels "vehicle,people,traffic_signs"  --config "{shift_auto_shape_color: 0}"
> # or below (shift_auto_shape_color is 0 by default)
> labelme --labels "vehicle,people,traffic_signs" 
> ```
> 
> ![image](https://user-images.githubusercontent.com/4310419/95871226-53940680-0d65-11eb-9908-c420b0bff9c7.png)

**Comment by rds-itga** [comment]
pull request  #864 is related to this problem

**Comment by wkentaro** [comment]
@rds-itga Please open a new issue for that.

**Comment by demirciogluX** [comment]
> @wkentaro
> 
> Thank you for your quickly response. I'll try and I'll let you know.
> 
> In that case, you can try
> 
> > ```
> > # labelme --labels "vehicle,people,traffic_signs"  --config "{shift_auto_shape_color: 0}"
> > # or below (shift_auto_shape_color is 0 by default)
> > labelme --labels "vehicle,people,traffic_signs" 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/4310419/95871226-53940680-0d65-11eb-9908-c420b0bff9c7.png)
im doing similar work as you did. did it work?
