### ISSUE TITLE
How to handle number of instances > 255, which cannot be saved as PNG

### ISSUE THREAD

**Issue by liburning** [wkentaro/labelme#704]
If the number of instances is bigger than 255,we cannot save the pixel-wise class label as PNG, so please use the npy file ,how do I deal with it?

**Comment by wkentaro** [comment]
You can use npy files in `SegmentationObject` dir
https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation/data_dataset_voc/SegmentationObject
