### ISSUE TITLE
Pre-Compiled Binaries?

### ISSUE THREAD

**Issue by yurikleb** [wkentaro/labelme#705]
The main readme states that "there are pre-built executables in the release section."
I tried downloading several releases but could not find bin files in any of them.

Could you please say which versions include executables in them or add a page with downloads of the latest stable version? if possible for Mac / Windows / Linux.

I can help compile on any of the above OS.

**Comment by wkentaro** [comment]
Sorry that readme was kind of out-of-date at that point.
I've added pre-built binaries for mac and linux here, so please try it.
https://github.com/wkentaro/labelme/releases/tag/v4.5.5

If you have Windows, can you have a try pyinstaller on your env?

**Comment by yurikleb** [comment]
Awesome thanks! will try and report.

**Comment by yurikleb** [comment]
I tried running the v4.4.5.dmg on Catalina OS and it seems to work fine.
I also managed to compile on windows using pyinstaller following those instructions: https://github.com/wkentaro/labelme#how-to-build-standalone-executable
However when I try running the .exe I'm getting a "Failed to execute script pyi_rth_pkgres"

**Comment by wkentaro** [comment]
Related to this? https://stackoverflow.com/questions/37815371/pyinstaller-failed-to-execute-script-pyi-rth-pkgres-and-missing-packages

**Comment by wkentaro** [comment]
I have successfully compiled binary on Windows 10 with this change https://github.com/wkentaro/labelme/pull/722. You can download Labelme-4.5.5.exe from below:
https://github.com/wkentaro/labelme/releases/tag/v4.5.5

**Comment by yurikleb** [comment]
amazing thank you!
