### ISSUE TITLE
[Feature]A commandline option to export different labels to different json files

### ISSUE THREAD

**Issue by abinashdash17** [wkentaro/labelme#706]
If I annotate dogs and humans in an image and export as json, I get all of those in a single json file. I want to get those in separate files (say img_dog.json containing dog labels and img_human.json containing human labels). A command line option to export only specific labels to another json file from a json file containing multiple labels would be a very good solution.

**Comment by wkentaro** [comment]
I think most people don't need this, so probably you can create a simple python file to separate the single JSON file.

**Comment by abinashdash17** [comment]
Thanks. I will try that workaround.
