### ISSUE TITLE
how to label instance segmentation dataset when multiple objects of the same class in one picture

### ISSUE THREAD

**Issue by deep-practice** [wkentaro/labelme#709]
when run labelme_json_to_dataset xxx.json,no info.yaml generated.
I use the latest version.

**Comment by wkentaro** [comment]
It's deprecated and replaced by label_names.txt.

**Comment by deep-practice** [comment]
When I  use labelme2coco.py  to convert my dataset for instance segmentation training,the model I trained is strange.It takes all the objects of the same class as a whole. @wkentaro

**Comment by deep-practice** [comment]
If I label the objects of the same class in one picture as obj1,obj2,when converting to coco format,does obj1,obj2 are different classes?And do I need to label obj3,obj4 when change to the next picture? @wkentaro

**Comment by wkentaro** [comment]
See example/instance_se

**Comment by deep-practice** [comment]
@wkentaro  The objects of the same class assign diffirent group ids?

**Comment by deep-practice** [comment]
I assign diffirent group ids to the diffirent objects with the same class,nothing changes,all the objects are taken as a whole.

**Comment by wkentaro** [comment]
That's strange. If I visualize annotations.json in examples/instance_segmentation/data_dataset_coco, it seems working.

https://gist.github.com/wkentaro/84f14a29a7e4888d3cb5e4270c0398c0

![2011_000003](https://user-images.githubusercontent.com/4310419/86355404-8b69b900-bc62-11ea-8eb1-84382c0ff7ac.jpg)
![2011_000006](https://user-images.githubusercontent.com/4310419/86355407-8c9ae600-bc62-11ea-9502-78c752fe4a9f.jpg)
![2011_000025](https://user-images.githubusercontent.com/4310419/86355410-8c9ae600-bc62-11ea-9dbb-c23399ea7b25.jpg)

**Comment by deep-practice** [comment]
Solved using the latest code.Thx. @wkentaro

**Comment by hande6688** [comment]
@wkentaro 
How to label a single category with labelme? I read the custom data set, but I didn’t point out a label naming method. Sometimes there is only one category in a picture. Is it cat, cat, cat or cat0, cat1, cat2 or cat-0 , Cat-1, cat-2, thank you!

I use cat-0, cat-1, cat-2 for annotation, and use labelme2coco to convert annotations.json, where the annotation is [], what's the matter?
