### ISSUE TITLE
how to extract Encoded PNG for each label for building TF Record

### ISSUE THREAD

**Issue by seahawks8** [wkentaro/labelme#71]
I have trained several datasets, but am new to using mask
RCNN. I have already built a script to do the following with the output JSON file from labelme

- read image, get height width
- get normalized box coordinates (calculated by reading the points and getting min, max for X and Y)

my question, is how do I get a serialized PNG image for each label?
example
`image/object/mask = ["\x89PNG\r\n\x1A\n\x00\x00\x00\rIHDR\...", ...]`

**Comment by wkentaro** [comment]
I think you can use `lableme.utils.polygon_to_mask` function:
https://github.com/wkentaro/labelme/blob/58693e6e9b485c6c61c704095a0f5620d31f2c8a/labelme/utils.py#L69-L75

Then convert the numpy array to serialized PNG image.

**Comment by seahawks8** [comment]
Thanks. I tried running that and I just end up with a blank png. A function that exports or shows how to get individual png files for each mask would be ideal. I will keep working on this.

**Comment by seahawks8** [comment]
Hey so I ended up being able to plot and see the Mask by modifying the function a little bit.
this will draw the PNG just black (background) and the mask will be white.
I wonder if I can just save that polygon png as-is and do the training with that
```
mask = PIL.Image.fromarray(mask)
xy = list(map(tuple, polygons))
draw = ImageDraw.Draw(mask)
draw.polygon(xy=xy, outline=3, fill=1)
mask.show()
```

**Comment by seahawks8** [comment]
Ok i ended up with this to get the serialized PNG
```
    mask = PIL.Image.fromarray(mask)
    xy = list(map(tuple, polygons))
    draw = ImageDraw.Draw(mask)
    draw.polygon(xy=xy, outline=1, fill=1)
    imgByteArr = io.BytesIO()
    mask.save(imgByteArr, format='PNG')
    imgByteArr = imgByteArr.getvalue()
```

output will be something along the lines of
b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x07\x80\x00\x00\x048\x08\x00 .....
