### ISSUE TITLE
[QUESTION] How to manually set label line colour?

### ISSUE THREAD

**Issue by guinevere-chan** [wkentaro/labelme#712]
Hi there, 

I would like to be able to set label line colour as below.

If I have four labels:

1_label_a
1_label_b
2_label_a
2_label_b

I want to be able to set the same colour for 1_label_a and 1_label_b, then a different colour for 2_label_a and 2_label_b.

How can I achieve this?

Thanks in advance.

**Comment by travishsu** [comment]
After reading [this](https://github.com/wkentaro/labelme/blob/master/labelme/app.py#L1135) and [this](https://github.com/wkentaro/labelme/blob/master/labelme/config/default_config.yaml#L18), my understanding is that you can set your .labelmerc like this:

```yaml
shape_color: 'manual'
label_colors: {'1_label_a': [r1, g1, b1], '1_label_b': [r1, g1, b1], '2_label_a': [r2, g2, b2], '2_label_b': [r2, g2, b2]}
```

if I'm wrong please correct me.
