### ISSUE TITLE
What does "Group ID" mean?

### ISSUE THREAD

**Issue by harolddu** [wkentaro/labelme#714]
I have a question about how to use "Group ID".
Can several polygons having the same "Group ID" be assumed as one instance?

Or， if I want to use some polygons in the same image to present one instance, what should I do?

**Comment by wkentaro** [comment]
> Can several polygons having the same "Group ID" be assumed as one instance?

This is correct. See examples/instance_segmentation for some examples.

**Comment by wkentaro** [comment]
Please refer this for more detail: https://github.com/wkentaro/labelme/issues/633
