### ISSUE TITLE
hao to run labelme_json_to_dataset

### ISSUE THREAD

**Issue by fishfishson** [wkentaro/labelme#72]
I use windows 10 and install  labelme by conda. 
I can use command labelme but I dont know how to use command labelme_json_to_dataset. When I type it on cmd, it tells me such command does not exist.

**Comment by wkentaro** [comment]
Maybe this is the same problem as https://github.com/wkentaro/labelme/issues/45.

**Comment by wkentaro** [comment]
I think https://github.com/wkentaro/labelme/commit/91154a74e3584967c3e531ecb0078d2a1179366f fixes this issue.
Could you try it?

**Comment by boycao** [comment]
@wkentaro 
Hi there,
I am running labelme_draw_json and labelme_json_to_dataset on my mac, but neither of these two work. Both show a " Command not found ". Cloud you help me with this? 
I installed through homebrew and command labelme works fine. Only these two(for now) do not work.
