### ISSUE TITLE
可以添加图像的放大缩小功能吗，有些标签太密集，不好划分[Feature]

### ISSUE THREAD

**Issue by lx-rookie** [wkentaro/labelme#726]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ILXR** [comment]
You can zoom in and out by pressing Ctrl and sliding the mouse wheel at the same time

**Comment by xie2020xie** [comment]
Chinese is a easy language    ctrl加鼠标滚轮放大缩小
