### ISSUE TITLE
[BUG] Pascal Voc conversion - white outlining

### ISSUE THREAD

**Issue by crouchjt** [wkentaro/labelme#728]
**Describe the bug**
The pascal voc conversion for image segmentation doesn't use the white outlining that the pascal voc dataset uses.

**To Reproduce**
1. follow example here: https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation

**Expected behavior**
An output that matches the pascal voc data set. Here is an example from the data set itself:
![2007_000129](https://user-images.githubusercontent.com/1685976/87735025-21d0cb00-c789-11ea-9341-2372c1afaffc.png)

However, the output doesn't have the same white outlining: 
![image](https://user-images.githubusercontent.com/1685976/87735077-4c228880-c789-11ea-8e0e-90e5428ca1d5.png)

**Desktop (please complete the following information):**
 - Windows Anaconda

**Additional context**
Everything else about instance segmentation seems good!

**Comment by wkentaro** [comment]
Probably we could add this. White outlining is **ignore** label where you don't penalize the segmentation in semantic segmentation. But in COCO, they don't have this kind of trick, do you think it's really necessary for instance segmentation as well?

**Comment by crouchjt** [comment]
https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation has a section called "Convert to VOC-format Dataset". If you truly want to support that case then I believe it is necessary to match with the rest of the VOC dataset.

**Comment by wkentaro** [comment]
I added VOC conversion since I needed, not wanted. And border ignore label was not necessary for me.
I don't really mind if it doesn't exactly match to the original VOC dataset.

**Comment by crouchjt** [comment]
Ah, so here's where I'm at:

I'm trying to extend a deeplab model that's originally been trained on the Pascal dataset with 20 classes. I'm seeing if I can add more classes into it so I used your tool to markup a new class and added it into the dataset. I noticed the difference between what this tool produced and the actual dataset and assumed it would be a problem when I had the model train over my new images. Should i be able to train on these images without the ignore border label? I'm thinking the answer is no because one of the steps removes all color from the image and saves it as a "SegementationClassRaw" as shown here: 
![2007_000129](https://user-images.githubusercontent.com/1685976/87864246-bc144880-c91a-11ea-92f4-c9b919637ad6.png)

My understanding is still a little weak of all this so I'm not sure exactly how this image is used in training.

**Comment by plter** [comment]
I created a simple tool for generating png with borders [https://github.com/plter/labelme2voc](https://github.com/plter/labelme2voc) and it works in my project.

**Comment by annish07** [comment]
@wkentaro  All because there is no  white-lining from the output of script "labelme2voc.py" , When we use remove_gt_colormap.py  from Tensorflow to remove background, it generates whole black image and model assumes that whole image is background.

Can you please let me know how can we modify labelme2voc.py script in order to have whitelines in border as output.

@plter Your suggestions would also help.
