### ISSUE TITLE
[BUG] labelme crashed when removing points

### ISSUE THREAD

**Issue by BriFuture** [wkentaro/labelme#732]
**Describe the bug**
Application crashed when removing points.

**To Reproduce**
1. Add Points such as  P1, P2, P3, P4, P5
2. Click on P1, right clicked to popup the menu,
3. Click `remove Selected point` at the bottom of the menu
4. The application crashed.

**Expected behavior**
P1 could be removed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 64bit
 - Labelme Version: 4.4.5

**Additional context**
```
c:\mypack\medicine\winevenv\lib\site-packages\labelme\utils\qt.py:93: RuntimeWarning: invalid value encountered in double_scalars
  return np.linalg.norm(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
Traceback (most recent call last):
  File "c:\mypack\medicine\winevenv\lib\site-packages\labelme\widgets\canvas.py", line 274, in mouseMoveEvent
    elif shape.containsPoint(pos):
  File "c:\mypack\medicine\winevenv\lib\site-packages\labelme\shape.py", line 222, in containsPoint
    return self.makePath().contains(point)
  File "c:\mypack\medicine\winevenv\lib\site-packages\labelme\shape.py", line 246, in makePath
    path = QtGui.QPainterPath(self.points[0])
IndexError: list index out of range
```

**Comment by ILXR** [comment]
I fix this bug and push the new code to https://github.com/ILXR/labelme
And i have made a pull request to this master
you can use https://github.com/ILXR/labelme  temporarily  and wait for the author to change the code
just copy the labelme folder to (your python folder)\Lib\site-packages\ and override existed folder "labelme"

**Comment by BriFuture** [comment]
Thank you. I found an alternative way to delete the single point:

1. select `Edit Polygons` at the left side toolbar
2. right click the label in `Polygon Labels` at the right side toolbar
3. click `delete polygons`

But this is cumbersome as I must check which point the label stands for.

**Comment by ILXR** [comment]
Hahahaha, I find this too
It's hard work to find out which points to delete (from so many points)

**Comment by VaneeshK** [comment]
> I fix this bug and push the new code to https://github.com/ILXR/labelme
> And i have made a pull request to this master
> you can use https://github.com/ILXR/labelme temporarily and wait for the author to change the code
> just copy the labelme folder to (your python folder)\Lib\site-packages\ and override existed folder "labelme"

Still, it's crashing with the error "AttributeError: 'NoneType' object has no attribute 'haveNoPoints'" although there were multiple points. Removing a point randomly crashes the app.

**Comment by wkentaro** [comment]
Should be fixed via https://github.com/wkentaro/labelme/pull/840

**Comment by AI-P-K** [comment]
It still quits when i remove points from a existing polygon. Step to reproduce:
1. Create polygon
2. Try to remove few points consecutively
