### ISSUE TITLE
[BUG] cannot write mode RGBX as PNG

### ISSUE THREAD

**Issue by hirokun2016** [wkentaro/labelme#736]
I tried to open a tiff image file that is a color composite of [red,green,blue,near-infrared]. However, upon opening an error pops out. It says cannot writy mode  RGBX as PNG. 

![image](https://user-images.githubusercontent.com/21302915/88679886-7ded0500-d122-11ea-9010-ed319bf9fe62.png)

**Comment by wkentaro** [comment]
Can you post the image as well? I never seen RGBX image.
