### ISSUE TITLE
labelme_json_to_dataset not generating a right label.png file

### ISSUE THREAD

**Issue by showaykerker** [wkentaro/labelme#74]
As title, I just tried to generate a mask using labelme_json_to_dataset,
it did generate a directory which contains 5 file, and the label_viz.png showed the mask correctly.
However, the generated file label.png was not showing anything, and all of the pixels were 0.
Here's how I checked the pixels:

```
>>> import numpy as np
>>> import cv2
>>> np.unique(cv2.imread('1/label.png'))
array([0], dtype=uint8)
```
Please let me know if I was mistaken or making any mistake, thanks!

**Comment by wkentaro** [comment]
Please use `PIL.Image` instead of `cv2`: https://github.com/wkentaro/labelme#convert-to-dataset

**Comment by NarcissusInMirror** [comment]
it works, thank you very much!
