### ISSUE TITLE
AttributeError: module 'labelme' has no attribute 'LabelFile'

### ISSUE THREAD

**Issue by eastplainzhang** [wkentaro/labelme#742]
Traceback (most recent call last):
  File "labelme2coco.py", line 187, in <module>
    main()
  File "labelme2coco.py", line 87, in main
    label_file = labelme.LabelFile(filename=filename)
AttributeError: module 'labelme' has no attribute 'LabelFile'

Hello.
I have encountered a problem mentioned above. 
How can I solve it. thank you.

**Comment by ryota765** [comment]
Updating labelme package to the latest version worked for me. 
`pip install -U labelme`

**Comment by eastplainzhang** [comment]
Thanks, I will have a try. @ryota765

**Comment by juniorkibirige** [comment]
Had that error sometime back.
But which version do you have please post it so we can reproduce the problem.

**Comment by eastplainzhang** [comment]
my labelme version is 3.16.7 @juniorkibirige

**Comment by dppselena** [comment]
@eastplainzhang Hello, have you solved this problem? I also encountered the same problem, please give me some advice.

**Comment by KrishnaNJena** [comment]
Getting Same Same Problem. My Labelme Version is 3.16.7. 
AttributeError: module 'labelme' has no attribute 'LabelFile'

**Comment by wkentaro** [comment]
Thanks for all. This is the solution: https://github.com/wkentaro/labelme/issues/742#issuecomment-671017264
