### ISSUE TITLE
ERROR: base_library.zip could not be created! . "How to build standalone executable":

### ISSUE THREAD

**Issue by ManhTK1911** [wkentaro/labelme#745]
Hello. I follow the steps "How to build standalone executable":
when i run this comand: pyinstaller labelme.spec
It has the error as below. how can i slove it?. thanks u.

20 INFO: checking Analysis
20 INFO: Building Analysis because Analysis-00.toc is non existent
20 INFO: Initializing module dependency graph...
21 INFO: Caching module graph hooks...
23 INFO: Analyzing base_library.zip ...
1391 INFO: Caching module dependency graph...
1416 ERROR: base_library.zip could not be created!
.
.
.
PermissionError: [Errno 13] Permission denied: '/home/labelme/build/labelme/base_library.zip'

_Originally posted by @ManhTK1911 in https://github.com/wkentaro/labelme/issues/220#issuecomment-669095606_

**Comment by wkentaro** [comment]
It seems you need to fix the permission of the build directory.
```
PermissionError: [Errno 13] Permission denied: '/home/labelme/build/labelme/base_library.zip'
```

**Comment by ManhTK1911** [comment]
ok. thanks u. I have installed it on the main account. however, when I created an account, the installation failed (even though I gave it sudo permission)
