### ISSUE TITLE
[BUG]lableme and opencv-python confict 

### ISSUE THREAD

**Issue by w594833736** [wkentaro/labelme#762]
**Describe the bug**
after install opencv-python,labelme can't startup 
description of what the bug is.
**To Reproduce**
1. pip install labelme 
2. pip install opencv-python
3. startup labelme

**Expected behavior**
after uninstall opencv-python,labelme worked well

**Screenshots**

> $ labelme
Loading config file from: /home/archer/.labelmerc
QObject::moveToThread: Current thread (0x561d58219840) is not the object's thread (0x561d5874f010).
Cannot move to target thread (0x561d58219840)
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "~/.local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

**Desktop (please complete the following information):**
 - OS: [archlinux ]
 - Labelme Version [4.5.6]
 - opencv-python Vserions [4.4.0.42]
*Additional context**

**Comment by liebkne** [comment]
Any news of this？

**Comment by barnettx** [comment]
A stop-gap solution: https://forum.qt.io/topic/119109/using-pyqt5-with-opencv-python-cv2-causes-error-could-not-load-qt-platform-plugin-xcb-even-though-it-was-found

**Comment by Adaverse** [comment]
I came across the error when I installed it from pip. Removed all the packages from virtual env and reinstalled labelme from apt worked for me.

**Comment by leeandy0822** [comment]
pip uninstall opencv-python can be solved.

**Comment by HyunjiEllenPak** [comment]
When conflict opencv with pyqt5,  you don't need to uninstall opencv.
Just install opencv-python-headless version. it works for me.

"pip install opencv-python-headless"

**Comment by thao-ftech** [comment]
> When conflict opencv with pyqt5, you don't need to uninstall opencv.
> Just install opencv-python-headless version. it works for me.
> 
> "pip install opencv-python-headless"
> 
> After that, you can get error such as "Qt startup error: symbol lookup error: libQt5XcbQpa.so.5: undefined symbol: FT_Get_Font_Format"
> 
> Then, type below.
> 
> "sudo yum update freetype-devel"
> 
> -os: centos7
> -python 3.6.13
> -PyQt5 5.15.4
> -opencv-python-headless 4.5.1.48

Also work on Ubuntu 18

**Comment by wkentaro** [comment]
This is the solution: https://github.com/wkentaro/labelme/issues/762#issuecomment-801519920

**Comment by ASShusharin** [comment]
sudo apt-get install --reinstall libxcb-xinerama0
Solved this issue for me

**Comment by LightRadiance** [comment]
> When conflict opencv with pyqt5, you don't need to uninstall opencv. Just install opencv-python-headless version. it works for me.
> 
> "pip install opencv-python-headless"
> 
> After that, you can get error such as "Qt startup error: symbol lookup error: libQt5XcbQpa.so.5: undefined symbol: FT_Get_Font_Format"
> 
> Then, type below.
> 
> "sudo yum update freetype-devel"
> 
> -os: centos7 -python 3.6.13 -PyQt5 5.15.4 -opencv-python-headless 4.5.1.48

It also works on Ubuntu22.04

**Comment by Sweaterz** [comment]
> When conflict opencv with pyqt5, you don't need to uninstall opencv. Just install opencv-python-headless version. it works for me.
> 
> "pip install opencv-python-headless"
> 
> After that, you can get error such as "Qt startup error: symbol lookup error: libQt5XcbQpa.so.5: undefined symbol: FT_Get_Font_Format"
> 
> Then, type below.
> 
> "sudo yum update freetype-devel"
> 
> -os: centos7 -python 3.6.13 -PyQt5 5.15.4 -opencv-python-headless 4.5.1.48

Just do "pip install opencv-python-headless" , then it works. Thanks very much.
