### ISSUE TITLE
How to label a single category with labelme? 

### ISSUE THREAD

**Issue by hande6688** [wkentaro/labelme#766]
How to label a single category with labelme? After looking at the user-defined data set, there is no annotation naming method. For example, there is only one category in a graph: cat, cat, cat or cat1, cat2, Cat3 or cat-0, cat-1, cat-2，
https://github.com/dbolya/yolact/issues/141

**Comment by wkentaro** [comment]
I don't really understand what you mean, but for single category annotation, you can edit `labels.txt`
https://github.com/wkentaro/labelme/blob/master/examples/instance_segmentation/labels.txt

as following
```
cat
```

**Comment by hande6688** [comment]
@wkentaro 
I mean to label a single category for instance segmentation. There are multiple cat in a graph, but there is only one category, so I want to know how to label it?
How to label a single category with labelme and instance segmentation? There are cat, cat, cat, cat0, cat1, cat2 or cat-0, cat-1, cat-2, etc. which annotation method is used?thank you!

I use cat-0, cat-1, cat-2 for annotation, and use labelme2coco to convert annotations.json, where the annotation is [], what's the matter?

**Comment by wkentaro** [comment]
> There are multiple cat in a graph

You mean "an image" by "a graph"? If so, my previous answer is what you need.

**Comment by wkentaro** [comment]
After creating your own `labels.txt`, you run below command
```
labelme data_annotated --labels labels.txt --nodata
```

**Comment by hande6688** [comment]
@wkentaro 
You still don't understand what I mean: instance segmentation, I only have one category. How to label it with labelme? For example, if the category is cat, some people suggest using Cat0, CAT1, cat2 on GitHub, and others suggest using cat-0, cat-1, cat-2, or cat, cat, cat, cat, which one should be used,

Using cat-0, cat-1, cat-2 requires this code labelme2cco
You've answered the same question as the following,:
https://github.com/wkentaro/labelme/issues/709
I use cat-0, cat-1, cat-2 for annotation, and use labelme2coco to convert annotations.json, where the annotation is [], what's the matter?

**Comment by wkentaro** [comment]
Why do you think I don’t understand? I refer instance segmentation example, and why it does not work?

**Comment by jiunyen-ching** [comment]
@hande6688 In case you're still interested, you need to use _cat_ for each of your _cat_ instances. In the _labels.txt_ that is passed as an argument for _labelme2coco.py_, the categories should be:
-  \_\_ignore\_\_
- \_background\_
- cat

When the code runs successfully, the terminal should say something like:
```
Creating dataset: <your_output_folder>
Generating dataset from: my_annotated/<your_json_file>.json
```

**Comment by morganOliveira2018** [comment]
@jiunyen-ching @Wkentaro Hello. 
1. I have a problem with labels automatically generated by Labelme. I created specific labels for fish species, for example, "eye Atlantic Mackerel", however the supercategory "**eye**" is being created and it is not being used in any image. However, the supercategory "** eye **" is added to train.json automatically after finalizing the labeling of the train folder.
2. 
```
        {
           "supercategory": "eye",
            "id": 18,
            "name": "eye"
        },
        {
            "supercategory": "eye Atlantic Mackerel",
            "id": 19,
            "name": "eye Atlantic Mackerel"
        },
        {
            "supercategory": "eye Lane Snapper",
            "id": 20,
            "name": "eye Lane Snapper"
        }, 
        ...
```
3. Due to the automatically generated labels, I am having a difference between the number of train.json and test.json labels generated. Train.json has 38 labels [0 - 37] and test.json has 31 labels [0 - 30], how can I correct this difference between files?


@wkentaro or @jiunyen-ching If you can help me, thank you.

**Comment by jiunyen-ching** [comment]
Hi @morganOliveira2018, just checking, are you using the Labelme tool by CSAILVision? I just checked my annotation files generated by this repo's tool; they don't have supercategory in them.

**Comment by morganOliveira2018** [comment]
@jiunyen-ching First I'm not using the Labelme tool by CSAILVision, I'm using the Labelme tool from the repository: https://github.com/wkentaro/labelme/. I used instance segmentation, inside Labelme I used annotation for polygon.

**Comment by jiunyen-ching** [comment]
Hi @morganOliveira2018 sorry for the late reply. The version of LabelMe that I am using must be of an older version then. Mine does not have the option for instance segmentation, just directly drawing polygons and giving it a label and optionally a group id.
