### ISSUE TITLE
Label all images in a directory

### ISSUE THREAD

**Issue by jbvo** [wkentaro/labelme#77]
Currently, labelme can be called using -O to preset the output file and the actual image to label as an argument. Using these options one could write a script that iterates over all images in a directory to label them all.

To make labeling all images in a directory more convenient, I think it would be helpful to be able to 'open dir' from the file menu and show a list of the images in the selected directory. Ideally the list would also provide some feedback whether the image is labeled yet.

**Comment by seahawks8** [comment]
@jbvo I finished this, check the latest PR.
