### ISSUE TITLE
How to transfer all json to dataset 

### ISSUE THREAD

**Issue by xcharxlie** [wkentaro/labelme#772]
It seems like the code labeme_json_to_dataset is only designed for single file. I tried to convert all json files into dataset formats. I coded like this:
 for a in os.listdir(path):
    file = os.path.join(path,a)
    for f in os.listdir(file):
        if(f.endswith('json')):
            name = os.path.split(f)[-1]
      
            labelme_json_to_dataset f -o dataset/os.path.splitext(name)[0]_json
I got an error 'invalid syntax' at 'f' in the last line. Just wonder what's going wrong here? Thank you very much.

**Comment by wkentaro** [comment]
Please look at `labelme2voc.py` and `labelme2coco.py`.
