### ISSUE TITLE
fail to create annotation of instance_segmentation

### ISSUE THREAD

**Issue by xcharxlie** [wkentaro/labelme#774]
Hi, I'm trying to create a coco annotation file using the instruction of instance segmentation provided.
This is my command in the terminal:

./labelme2coco.py data_annotated data_dataset_coco --labels label_names.txt
Creating dataset: data_dataset_coco
Generating dataset from: data_annotated/000794.json
Generating dataset from: data_annotated/000862.json
Generating dataset from: data_annotated/000321.json
Generating dataset from: data_annotated/001759.json
Traceback (most recent call last):
  File "./labelme2coco.py", line 187, in <module>
    main()
  File "./labelme2coco.py", line 162, in main
    labels, captions, masks = zip(
ValueError: not enough values to unpack (expected 3, got 0)

Could anyone help me out of my mistakes? Thanks in advance.

**Comment by IgMart** [comment]
Hi, @xcharxlie 
did you solve it?

**Comment by xcharxlie** [comment]
I actually resolved the question not technically but resolved the issue
itself.

**Comment by Crescent-Saturn** [comment]
I met the same error.
If you just want to generate the coco annotation json file, no need the visualization images, you may use the --noviz in the command, just like:
```
./labelme2coco.py data_annotated data_dataset_coco --labels label_names.txt --noviz
``` 

Then you will be able to get the `annotation.json` file in coco format.

**Comment by EMCP** [comment]
I just had this same error happen to me, of not enough values to unpack... it would be great if this happens to put a plain english error message citing this ticket or explaining that I should use `--noviz`  .  once i added that everything seems to have worked fine
