### ISSUE TITLE
imageData

### ISSUE THREAD

**Issue by alicera** [wkentaro/labelme#777]
When I label the image and save it , I find the property of imageData will be save.
So the *.json file is large.
How can I do ?

**Comment by ALmagical** [comment]
Hi, I have the same question. May I ask, have you found the solution?

**Comment by alicera** [comment]
not yet

**Comment by hyungju-song** [comment]
Hi, everyone.
When you run labelme, you can fix the problem with the "File" button in the top left corner.
From there, just turn-off "Save With Image Data".
Then your json file is saved in 10KB or less. What used to be 300KB

However, when labelme2voc.py is executed, information about the image data is required, 
so I hope you do not turn-off it for your convenience.

Hope it was helpful

**Comment by wkentaro** [comment]
You can use `labelme --nodata data_annotated/` not to save `imageData` into the JSON files.
And I think for now `labelme2voc.py` supports empty `imageData` property in the JSON file.
Let me know if you still have problem.
