### ISSUE TITLE
Fatal error detected?

### ISSUE THREAD

**Issue by codylcs** [wkentaro/labelme#781]
![image](https://user-images.githubusercontent.com/48380363/94389004-2cdcaa00-0181-11eb-9a94-007f7b453c28.png)

enviroment: win10
`# packages in environment at D:\ProgramData\Anaconda3\envs\labelme:
#
# Name                    Version                   Build  Channel
altgraph                  0.17                      <pip>
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py36h9f0ad1d_0    conda-forge
colorama                  0.4.3                     <pip>
cycler                    0.10.0                    <pip>
future                    0.18.2                    <pip>
icu                       67.1                 h33f27b4_0    conda-forge
imgviz                    1.2.2                     <pip>
jpeg                      9d                   he774522_0    conda-forge
kiwisolver                1.2.0                     <pip>
labelme                   4.5.6                     <pip>
libclang                  10.0.1          default_hf44288c_1    conda-forge
libpng                    1.6.37               ha81a0f5_2    conda-forge
macholib                  1.14                      <pip>
matplotlib                3.3.2                     <pip>
numpy                     1.19.2                    <pip>
openssl                   1.1.1h               he774522_0    conda-forge
pefile                    2019.4.18                 <pip>
Pillow                    7.2.0                     <pip>
pip                       20.2.3                     py_0    conda-forge
pyinstaller               4.0                       <pip>
pyinstaller-hooks-contrib 2020.8                    <pip>
pyparsing                 2.4.7                     <pip>
PyQt5                     5.15.1                    <pip>
PyQt5-sip                 12.8.1                    <pip>
python                    3.6.0                         2    conda-forge
python-dateutil           2.8.1                     <pip>
python_abi                3.6                     1_cp36m    conda-forge
pywin32-ctypes            0.2.0                     <pip>
PyYAML                    5.3.1                     <pip>
qt                        5.12.6               hb2cf2c5_0    conda-forge
QtPy                      1.9.0                     <pip>
setuptools                49.6.0           py36h9f0ad1d_1    conda-forge
setuptools                50.3.0                    <pip>
six                       1.15.0                    <pip>
sqlite                    3.33.0               he774522_0    conda-forge
termcolor                 1.1.0                     <pip>
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
wincertstore              0.2                   py36_1003    conda-forge
zlib                      1.2.11            h62dcd97_1009    conda-forge`

`(labelme) D:\Pycharm\labelme>pyinstaller labelme.spec
49 INFO: PyInstaller: 4.0
50 INFO: Python: 3.6.0 (conda)
51 INFO: Platform: Windows-10-10.0.18362-SP0
53 INFO: UPX is not available.
54 INFO: Extending PYTHONPATH with paths
['D:\\Pycharm\\labelme', 'D:\\Pycharm\\labelme\\labelme']
61 INFO: checking Analysis
77 INFO: Building because d:\programdata\anaconda3\envs\labelme\lib\site-packages\PyQt5\__init__.py changed
77 INFO: Initializing module dependency graph...
80 INFO: Caching module graph hooks...
92 INFO: Analyzing base_library.zip ...
2446 INFO: Caching module dependency graph...
2516 INFO: running Analysis Analysis-00.toc
2518 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by d:\programdata\anaconda3\envs\labelme\python.exe
2765 INFO: Analyzing labelme\__main__.py
2928 INFO: Processing pre-find module path hook distutils from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
2929 INFO: distutils: retargeting to non-venv dir 'd:\\programdata\\anaconda3\\envs\\labelme\\lib'
5040 INFO: Processing pre-find module path hook site from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
5041 INFO: site: retargeting to fake-dir 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\fake-modules'
6781 INFO: Processing module hooks...
6782 INFO: Loading module hook 'hook-distutils.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
6783 INFO: Loading module hook 'hook-encodings.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
6860 INFO: Loading module hook 'hook-lib2to3.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
6891 INFO: Loading module hook 'hook-numpy.core.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
7041 INFO: Loading module hook 'hook-numpy.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
7042 INFO: Loading module hook 'hook-PIL.Image.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
7394 INFO: Loading module hook 'hook-PIL.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
7395 INFO: Excluding import 'PyQt5'
7397 INFO:   Removing import of PyQt5.QtCore from module PIL.ImageQt
7397 INFO:   Removing import of PyQt5.QtGui from module PIL.ImageQt
7398 INFO: Import to be excluded not found: 'FixTk'
7399 INFO: Excluding import 'PyQt4'
7401 INFO: Excluding import 'PySide'
7403 INFO: Excluding import 'tkinter'
7405 INFO:   Removing import of tkinter from module PIL.ImageTk
7405 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
7406 INFO: Import to be excluded not found: 'FixTk'
7406 INFO: Excluding import 'tkinter'
7408 INFO: Loading module hook 'hook-pkg_resources.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
7830 INFO: Processing pre-safe import module hook win32com from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
7883 INFO: Processing pre-safe import module hook win32com from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
7935 WARNING: Hidden import "pkg_resources.py2_warn" not found!
7935 WARNING: Hidden import "pkg_resources.markers" not found!
7937 INFO: Excluding import '__main__'
7939 INFO:   Removing import of __main__ from module pkg_resources
7939 INFO: Loading module hook 'hook-PyQt5.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
8114 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
8181 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
8309 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
8579 INFO: Loading module hook 'hook-setuptools.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
9042 INFO: Loading module hook 'hook-sysconfig.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
9043 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
9043 INFO: Loading module hook 'hook-xml.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
9083 INFO: Loading module hook 'hook-_tkinter.py' from 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks'...
9219 INFO: checking Tree
9236 INFO: checking Tree
9272 INFO: Looking for ctypes DLLs
9313 INFO: Analyzing run-time hooks ...
9317 INFO: Including run-time hook 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyqt5.py'
9319 INFO: Including run-time hook 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
9320 INFO: Including run-time hook 'd:\\programdata\\anaconda3\\envs\\labelme\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
9329 INFO: Looking for dynamic libraries
10080 INFO: Looking for eggs
10080 INFO: Using Python library d:\programdata\anaconda3\envs\labelme\python36.dll
10081 INFO: Found binding redirects:
[]
10087 INFO: Warnings written to D:\Pycharm\labelme\build\labelme\warn-labelme.txt
10192 INFO: Graph cross-reference written to D:\Pycharm\labelme\build\labelme\xref-labelme.html
10212 INFO: Appending 'datas' from .spec
10216 INFO: checking PYZ
10220 INFO: Building because toc changed
10220 INFO: Building PYZ (ZlibArchive) D:\Pycharm\labelme\build\labelme\PYZ-00.pyz
11226 INFO: Building PYZ (ZlibArchive) D:\Pycharm\labelme\build\labelme\PYZ-00.pyz completed successfully.
11246 INFO: checking PKG
11246 INFO: Building because toc changed
11247 INFO: Building PKG (CArchive) PKG-00.pkg
24208 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
24213 INFO: Bootloader d:\programdata\anaconda3\envs\labelme\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
24214 INFO: checking EXE
24216 INFO: Building because toc changed
24216 INFO: Building EXE from EXE-00.toc
24222 INFO: Copying icons from ['labelme/icons/icon.ico']
24223 INFO: Writing RT_GROUP_ICON 0 resource with 76 bytes
24223 INFO: Writing RT_ICON 1 resource with 1128 bytes
24223 INFO: Writing RT_ICON 2 resource with 2440 bytes
24223 INFO: Writing RT_ICON 3 resource with 4264 bytes
24223 INFO: Writing RT_ICON 4 resource with 9640 bytes
24224 INFO: Writing RT_ICON 5 resource with 165640 bytes
24228 INFO: Updating manifest in D:\Pycharm\labelme\build\labelme\runw.exe._kij9d5v
24228 INFO: Updating resource type 24 name 1 language 0
24231 INFO: Appending archive to EXE D:\Pycharm\labelme\dist\labelme.exe
24268 INFO: Building EXE from EXE-00.toc completed successfully.

(labelme) D:\Pycharm\labelme>labelme --version
labelme 4.5.6

(labelme) D:\Pycharm\labelme>`

what should i do？

**Comment by torta24x** [comment]
I had the same exact issue,  this usually means that it has encountered an error while running `__main__.py`
To what I understand this could be caused by two fallowing reason

#### Possible reasons:

1.  **Path issue**, if you added config file or some other file that it requires while running and which is not added to exe file
2. There could be python **lib version compatibility issue** 

#### My Solution:
In my case I had to lower down the `imgviz==1.2.2 --> imgviz == 0.11`
And also for the config, I was unable to add it to exe so I placed it with the exe file and added that relative path to it.

If anyone knows a better way to deal with this, then please do let me know.

Thanks

**Comment by codylcs** [comment]
> I had the same exact issue, this usually means that it has encountered an error while running `__main__.py`
> To what I understand this could be caused by two fallowing reason
> 
> #### Possible reasons:
> 1. **Path issue**, if you added config file or some other file that it requires while running and which is not added to exe file
> 2. There could be python **lib version compatibility issue**
> 
> #### My Solution:
> In my case I had to lower down the `imgviz==1.2.2 --> imgviz == 0.11`
> And also for the config, I was unable to add it to exe so I placed it with the exe file and added that relative path to it.
> 
> If anyone knows a better way to deal with this, then please do let me know.
> 
> Thanks

thanks, the question has been tackled, u can look the link for know something https://blog.csdn.net/weixin_41449637/article/details/108849496

**Comment by torta24x** [comment]
Thanks, will make those changes as well.
