### ISSUE TITLE
[BUG]how to convert the json to label.png while my file contains more than 256 labels?

### ISSUE THREAD

**Issue by hughwyc** [wkentaro/labelme#788]
**Describe the bug**

I have a labeled image file contains 512 labels.

<img width="934" alt="image" src="https://user-images.githubusercontent.com/61838645/95809922-719c3f80-0d42-11eb-8217-c96b9dfba105.png">

When I try to convert the json to .png file, I met this:

File "/Users/hugh/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/labelme/utils/_io.py", line 29, in lblsave
    'Please consider using the .npy format.' % filename
ValueError: [train_dataset/mask/0.png] Cannot save the pixel-wise class label as PNG. Please consider using the .npy format.

The _io.py is as follows:

```
def lblsave(filename, lbl):
if osp.splitext(filename)[1] != '.png':
filename += '.png'
# Assume label ranses [-1, 254] for int32,
# and [0, 255] for uint8 as VOC.

if lbl.min() >= -1 and lbl.max() < 255:
lbl_pil = PIL.Image.fromarray(lbl.astype(np.uint8), mode='P')
colormap = label_colormap(255)
lbl_pil.putpalette((colormap * 255).astype(np.uint8).flatten())
lbl_pil.save(filename)
else:
# print('lbl.min = ', lbl.min(),'lbl.max = ', lbl.max())
raise ValueError(
'[%s] Cannot save the pixel-wise class label as PNG. '
'Please consider using the .npy format.' % filename
)
```

It seems can only convert the json contains less than 256 labels to .png (uint8 label file). but now I need more than 256. And I don't know how to using the .npy format. Please help me.

**Desktop (please complete the following information):**
 - OS: macOS Catalina version 10.15.7
 - Labelme Version : 3.16.7

**Comment by fanweiya** [comment]
you can save a tif ffile.

**Comment by wkentaro** [comment]
You can do something like `np.save("label.npy", lbl)` replacing `lblsave("label.png", lbl)`.
