### ISSUE TITLE
I got no file after executing command ./labelme2coco.py data_annotated data_dataset_coco --labels labels.txt

### ISSUE THREAD

**Issue by WWaynee** [wkentaro/labelme#790]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Labelme Version [e.g. 4.2.9]

**Additional context**

**Comment by wkentaro** [comment]
How to reproduce?

**Comment by wkentaro** [comment]
It seems same issue as https://github.com/wkentaro/labelme/issues/791
