### ISSUE TITLE
I executed the command './labelme2coco.py data_annotated data_dataset_coco --labels labels.txt'

### ISSUE THREAD

**Issue by WWaynee** [wkentaro/labelme#791]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Labelme Version [e.g. 4.2.9]

**Additional context**

**Comment by WWaynee** [comment]
And I got the errot:
Creating dataset: data_dataset_coco
Generating dataset from: data_annotated/188.json
Traceback (most recent call last):
  File "./labelme2coco.py", line 188, in <module>
    main()
  File "./labelme2coco.py", line 166, in main
    for (cnm, gid), msk in masks.items()
ValueError: not enough values to unpack (expected 3, got 0)


How to cope with this problem?Is there anybody giving me a helping hand?I would be grateful QAQ...

**Comment by Abdulhadiasa** [comment]
You have to modify the labels.txt file to match your labels

**Comment by WWaynee** [comment]
@Abdulhadiasa Thanks for your quick comment. But what should I do if I have many objects that belong to the same label. For example there're 3 cats in the image, how can I label and tag them by using labelme? 【cat1,cat2,cat3...】 or just【cat】for them all?

**Comment by Abdulhadiasa** [comment]
I think you just need to label each object as cat, don't group them together. If you look at the annotation afterwards you will notice that each object has an ID and an image_ID, so If you have multiple objects in the same picture they would have the same image_ID but different IDs.

**Comment by WWaynee** [comment]
@Abdulhadiasa Thank you very much!
