### ISSUE TITLE
how to generate color single channel mask image？

### ISSUE THREAD

**Issue by lucafei** [wkentaro/labelme#793]
hello, guys, i want know how does labelme generate a single channel color image, because recently i try to generate mask image as ground truth automatically, but when i always convert three channels RGB image into single channel image, it gets a gray image,not a color image with 1 channel like labelme. It makes me confused. Do you know how to deal with this? thank you in advance.

**Comment by wkentaro** [comment]
> always convert three channels RGB image into single channel image

Do you mean without annotation? If so how to do that?
