### ISSUE TITLE
How to solve error "Failed to execute script __main__ " in windows 10

### ISSUE THREAD

**Issue by KimMinGyu-ay** [wkentaro/labelme#796]
python == 3.6.9
PyQt5 == 5.15.1
pyinstall == 4.0
os == windows10

i commanded "pyinstaller labelme.spec" in terminal
After it, i try to run "lebelme.exe" but i met "Failed to execute script __main__".

how to solve it? 

labelme.spec

import sys

sys.setrecursionlimit(5000)  # required on Windows

a = Analysis(
    ['labelme/__main__.py'],
    pathex=['labelme'],
    binaries=[],
    datas=[
        ('labelme/config/default_config.yaml', 'labelme/config'),
        ('labelme/icons/*', 'labelme/icons'),
    ],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
)
pyz = PYZ(a.pure, a.zipped_data)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name='labelme',
    debug=False,
    strip=False,
    upx=True,
    runtime_tmpdir=None,
    console=False,
    icon='labelme/icons/icon.ico',
)
app = BUNDLE(
    exe,
    name='Labelme.app',
    icon='labelme/icons/icon.icns',
    bundle_identifier=None,
    info_plist={'NSHighResolutionCapable': 'True'},
)

** i saw #708 in github, but this solves is not fit for my problem

**Comment by KimMinGyu-ay** [comment]
i solved it

**Comment by honglanlao** [comment]
how did you solve it ?  i ran into the same issue

**Comment by KimMinGyu-ay** [comment]
could you show me your spec file?

**Comment by adtianjuan** [comment]
I got the same error.
I didn't modify anything in labelme.spec file.
Could you please share your solution?

**Comment by KimMinGyu-ay** [comment]
@adtianjuan  if your os is windows, you use cmd to solve the problem
in cmd, comand 'labelme.exe' that is create  after pyinstaller labelme.spec

**Comment by adtianjuan** [comment]
Thank you for your reply. @KimMinGyu-ay
My os is win10. But I got nothing in cmd window after running labelme.exe.
It only showed the error message window which included 'Failed to execute script __main__'. 
Could you please tell me more detail about your solution?

**Comment by KimMinGyu-ay** [comment]
@adtianjuan  you said "It only showed the error message"
Can you show me error message?

i guess that error message show about .dll

**Comment by LightSun** [comment]
finally I resolved this by steps.
1, As build exe in python just package python codes.  before build exe. we should ensure the labelme/__main__.py can run ok.
2, Ensure build exe has no warning info.

**Comment by KimMinGyu-ay** [comment]
@LightSun 

You should need to modify "Specfile":
 datas=[
        ('labelme/config/default_config.yaml', 'labelme/config'),
        ('labelme/icons/*', 'labelme/icons'),
    ],

"Datas" derive from library in Labelme-code, so following is example to solve problem.

1. Have to run in cmd 
2. After running, I think you encounter Error about library

if you can see Error, you will solve problem

Good luck too you

**Comment by airsimonhan** [comment]
It bothers me for a long time, and now I have solved this issue.
very very very easy !!! 
the author used *.yaml to config this project, and you may not install the lib `pyyaml`, just `pip install pyyaml`,  then you run again, done ! 

对于那些可以执行`python __main__.py`，但是却不能打包的情况，只需要安装`pyyaml`就可以了
