### ISSUE TITLE
how to create a exe file by pyinstaller or py2exe?

### ISSUE THREAD

**Issue by ustcxxs** [wkentaro/labelme#80]
Installation is not difficult, but there is still a need to look up some information.
So ,how to create a exe file by pyinstaller or py2exe?

**Comment by seahawks8** [comment]
Is an exe really necessary? The size of the compiled exe with the core modules and PYQT would probably be 500 MB using py2exe, pyinstaller or even cxfreeze

**Comment by wkentaro** [comment]
I tried using `pyinstaller --onefile --windowed labelme.py` with `labelme.py` below:

```
import labelme.app
labelme.app.main()
```

and ended up with failure; there was no window coming up..

**Comment by wkentaro** [comment]
Closed via #118 
There is an instruction in README: https://github.com/wkentaro/labelme#how-to-build-standalone-app
and I released standalone files here: https://github.com/wkentaro/labelme/releases/tag/v2.10.0
