### ISSUE TITLE
[BUG] OSError: cannot write mode RGBA as JPEG

### ISSUE THREAD

**Issue by ApoorvaOjha** [wkentaro/labelme#810]
When I am going to second image via next button or try to save current one the python crashes and labelme is closed.
the error is  
in _save raise OSError(f"cannot write mode {im.mode} as JPEG") from e
OSError: cannot write mode RGBA as JPEG
![err](https://user-images.githubusercontent.com/23102690/101984415-5ea4dd80-3ca7-11eb-86c6-797d2b2ee7d4.PNG)

Please help me soon, I have a deadline.

**Comment by Heermosi** [comment]
you may patch on this, manually conver RGBA to RGB channels, 
I hope this could help, though, .... it might have been too late

**Comment by f-izzat** [comment]
Any updates or workaraound on this? Im still getting this error.

**Comment by wkentaro** [comment]
Is that possible for you to provide the data to reproduce this?
