### ISSUE TITLE
[BUG]  shift_auto_shape_color config for semantic segmentation on Windows 10 not working

### ISSUE THREAD

**Issue by hyungju-song** [wkentaro/labelme#811]
**Describe the bug**

**OS: Windows 10
Labelme Version: 4.5.6**

The "shift_auto_shape_color" config doesn't seem to be working. I'm on Windows 10 and am running this command (based on the semantic segmentation example):

**labelme data_annotated --labels labels.txt --nodata --validatelabel exact --config '{shift_auto_shape_color: -2}'**

I end up getting this error:

**usage: labelme [-h] [--version] [--reset-config]
               [--logger-level {debug,info,warning,fatal,error}]
               [--output OUTPUT] [--config CONFIG] [--nodata] [--autosave]
               [--nosortlabels] [--flags FLAGS] [--labelflags LABEL_FLAGS]
               [--labels LABELS] [--validatelabel {exact}] [--keep-prev]
               [--epsilon EPSILON]
               [filename]
labelme: error: unrecognized arguments: -2}'**

Is this a bug or something wrong with how I'm using it? Thanks

**Comment by RabbyFazleCoder** [comment]
Same windows configuration and same error message. Couldn't fix it.

**Comment by shelldonhu** [comment]
@hyungju-song @RabbyFazleCoder 
On Windows, don't use '' but "". 
`labelme data_annotated --labels labels.txt --nodata --validatelabel exact --config "{shift_auto_shape_color: -2}"`
It works.

**Comment by 20195228** [comment]
what's the meaning of "{shift_auto_shape_color: -2}",What does it do
