### ISSUE TITLE
[BUG] mac os  labelme Boot failure 

### ISSUE THREAD

**Issue by billbillHao** [wkentaro/labelme#815]
macos 11.1 
python 3.7 
The installation was successful but the boot failed .
Prompt the application for no response

**Comment by Jay-Jia** [comment]
me too...

**Comment by mrhalyang** [comment]
me too

**Comment by mrhalyang** [comment]
I found the solution, https://github.com/tzutalin/labelImg/issues/672#issuecomment-731733191
