### ISSUE TITLE
[BUG]Labelme GUI won't load

### ISSUE THREAD

**Issue by bitcoder-17** [wkentaro/labelme#817]
**Describe the bug**
After I tried to run labelme by inputting labelme in terminal and hit enter, only the icon of labelme showed up in the application dock on Mac and there was no GUI popped up.

Message from Terminal:
[INFO   ] __init__:get_config:70 - Loading config file from:

**Comment by bitcoder-17** [comment]
I've figured out what prevented the GUI to pop up.

**Comment by rikutar** [comment]
Okey, can you share the solution?
I am dealing with same thing

**Comment by mrhalyang** [comment]
@bitcoder-17 Can you share the solution?

**Comment by bitcoder-17** [comment]
Since it has been a while, I will need to recap on what I did to solve the issue. I remember that I reinstall Python and the PyQt module and restarted my computer. Then, the issue was solved.

**Comment by bxxk2021** [comment]
try this：labelme --reset-config         
that's solve my problem
