### ISSUE TITLE
(node:8756) Electron: Loading non-context-aware native module in renderer: '...\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

### ISSUE THREAD

**Issue by twinsben94** [wkentaro/labelme#820]
Sir, I wannt use your labelme code. However it doesn't work, and these are the error in anaconda prompt. (I am a baby of Python.. haha). I guess https://github.com/electron/electron/issues/18397 is the solution, however I cannot find the way to solve it...

(venv_labelme) C:\ProgramData\Anaconda3\envs\venv_labelme\practice_labelme\labelme\examples\bbox_detection>
[main 2021-01-11T08:02:28.213Z] update#setState idle
(node:7036) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\Ryoungseob Kwon\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:7036) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\Ryoungseob Kwon\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:8756) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\Ryoungseob Kwon\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[main 2021-01-11T08:02:58.230Z] update#setState checking for updates
[main 2021-01-11T08:02:58.395Z] update#setState idle

I made the folder and in that folder, there is an sample image(what I chose), also I made a json file by your code. And now, I want to convert this file to VOC-format Dataset... I followed your homepage, 

https://github.com/wkentaro/labelme/tree/master/examples/bbox_detection

But, whenever I wrote ./labelme2voc.py data_annotated data_dataset_voc --labels labels.txt

(In my case, C:\ProgramData\Anaconda3\envs\venv_labelme\practice_labelme\labelme\examples\bbox_detection\labelme2voc.py data_annotated data_dataset_voc --labels labels.txt)

that doesn't seem to make any file. Just it open my vscode haha.....

May I get your help?? I really wanna use your code for my research(Because I think your code is the most simple and effective)

My final objective is to make xml file of annotation,,, please help me haha...

**Comment by wkentaro** [comment]
Where this Electron came from?
