### ISSUE TITLE
Rotated rectangle implementation [Question]

### ISSUE THREAD

**Issue by edu638s** [wkentaro/labelme#835]

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can label oriented bounding boxes using polygons and rotated boxes.
If necessary, you can export/import the Labelme JSON format.
https://rectlabel.com/help#xml_to_dota

![draw_obb_polygon](https://user-images.githubusercontent.com/1954306/214550369-560cb11d-4325-4ba4-9ba8-fd62297c9617.jpg)

**Comment by RoyiAvital** [comment]
@ryouchinsa , Now I see the context. You're the developer of `RectLabel`.
While it looks decent it does not work on Windows. So for me and others it is not an option.

Also the past pricing practices are questionable which makes the costs high.
