### ISSUE TITLE
[BUG] LabelMe crashes when clicking on rectangle, while holding shift

### ISSUE THREAD

**Issue by Armandgrd** [wkentaro/labelme#836]
**Describe the bug**
Clicking on rectangle while holding shift results in crash with assertionError.
```
  File "/user/folder/site-packages/labelme/shape.py", line 140, in paint
    assert len(self.points) in [1, 2]
AssertionError
57292 abort      labelme batch_fr_5 --nodata --labels labels.txt
```
**To Reproduce**
on Osx draw a rectangle and selecting it with mouse click, while holding shift.  

**Expected behavior**
No crash?
select multiple rectangles to edit labels in batch

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac os 
 - Labelme Version [e.g. 4.5.7]

> `labelme pathtofiles --nodata --labels labels.txt`

**Comment by wkentaro** [comment]
Sorry for late, but cannot reproduce. Let me know if you still have this issue.
