### ISSUE TITLE
[BUG] qt.qpa.plugin: Could not load the Qt platform plugin "xcb" -- fixed

### ISSUE THREAD

**Issue by fatalfeel** [wkentaro/labelme#842]
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/lib/python3.7/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

//////////////////////or//////////////////////////////////
QObject::moveToThread: Current thread (0xe38c70) is not the object's thread (0x1ab6aa0).
Cannot move to target thread (0xe38c70)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/lib/python3.7/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

///////////////////trace bug method
ldd /usr/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so
search [not found]

/////////////////// solved//////////////
sudo apt-get install python3-pyqt5
sudo apt-get install libxcb-xinerama0
sudo pip3 install pyqt5
sudo pip3 install opencv-python==3.4.10.35
sudo pip3 install labelme

**Comment by Heermosi** [comment]
I'm faced with the same , ... so called bugs? It was some thing relative to qt in Linux, may be you should submit the bug to opencv.
No not at all, you do not need anything else to make it work, just remove the damn

`/usr/lib/python3.7/site-packages/cv2/qt/plugins
`
then everything is fine....
May be the plugin shipped with opencv was not suited for this version of QT.
And it was a particular problem when opencv and pyqt installed at the same time in Linux. No such issue detected in Windows.

**Comment by TaucherLoong** [comment]
I have the same problem for a week, you mean 'remove /usr/lib/python3.7/site-packages/cv2/qt/plugins'. How to remove? remove the whole plugins directory or all files under this directory

**Comment by TaucherLoong** [comment]
or remove the qt directory?

**Comment by YacobBY** [comment]
@TaucherLoong Delete the whole cv2/plugins directory from wherever your venv is located. In my Project using the Pycharm IDE this would be venv/lib/python3.9/site-packages/cv2/qt/plugins
![Screenshot from 2021-07-10 14-37-51](https://user-images.githubusercontent.com/30029456/125163224-76d0d280-e18c-11eb-8e1b-d7c7b3baf8f1.png)

**Comment by TaucherLoong** [comment]
@YacobBY  Thanks a lot，feel so good. It really works

**Comment by wkentaro** [comment]
Thanks for finding and sharing the solution. 👍

**Comment by fsevenm** [comment]
> I'm faced with the same , ... so called bugs? It was some thing relative to qt in Linux, may be you should submit the bug to opencv. No not at all, you do not need anything else to make it work, just remove the damn
> 
> `/usr/lib/python3.7/site-packages/cv2/qt/plugins ` then everything is fine.... May be the plugin shipped with opencv was not suited for this version of QT. And it was a particular problem when opencv and pyqt installed at the same time in Linux. No such issue detected in Windows.


In my case `Ubuntu 21.04`, it's in `/usr/local/lib/python3.9/dist-packages/cv2/qt/plugins`. And yes, removing them or moving to other folder fixed the issue.

**Comment by JPLeoRX** [comment]
Dialing in here - removing the whole plugins folder breaks opencv if you're using it in normal (not headless) mode. I feel like this bug needs a better solution.

**Comment by nick-halden** [comment]
In case you're running on a **server**: Check if there are any calls for **graphical output** like `cv2.namedWindow`, `cv2.imshow()`, ...

**Comment by trezero** [comment]
What if I want the graphical output? Is there no way to have it work with the windows? It will be really hard to know if the app is working without being able to see anything for testing

**Comment by AbdelsalamHaa** [comment]
Thanks @TaucherLoong , 
your solution worked for me :)

**Comment by Airluv** [comment]
> @TaucherLoong Delete the whole plugins directory from wherever your venv is located. In my Project using the Pycharm IDE this would be venv/lib/python3.9/site-packages/cv2/qt/plugins ![Screenshot from 2021-07-10 14-37-51](https://user-images.githubusercontent.com/30029456/125163224-76d0d280-e18c-11eb-8e1b-d7c7b3baf8f1.png)

It really works!!!

**Comment by MarwanMagdy0** [comment]
the solution works for me but when i use the normal opencv imshow function it shows this error 
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "/home/marwan/.local/lib/python3.8/site-packages/cv2/qt/plugins"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)

**Comment by mcgilltaosun** [comment]
I solved this by installing a lower version of pyqt5

pip uninstall pyqt5
pip install pyqt5==5.10

**Comment by BoZhiStudying233** [comment]
Thanks for the solution, it worked for me!
