### ISSUE TITLE
Question: How to change the label of an existing bounding box?

### ISSUE THREAD

**Issue by mattroos** [wkentaro/labelme#844]
When using labelme, is there a way to change the label of an existing bounding box? I can't seem to find a mechanism. I have to delete the existing box and then create a new box with the new label, which is rather inefficient.

**Comment by 614nK** [comment]
Two methods:

1. In the "polygon labels" section of the UI, right click on the label and select "edit label"

2. Go into JSON file created from save and edit the label of whichever label you choose. See example below.
`{
  "version": "4.5.7",
  "flags": {},
  "shapes": [
    {
      "label": "put_your_label_here",
      "points": [
        [
          219.0,
          182.0
        ],
        [
          231.0,
          182.0
        ],
        [
          231.0,
          199.0
        ],
        [
          219.0,
          199.0
        ]
      ],
      "shape_type": "polygon",
      "flags": {},
      "group_id": "1",
      "other_data": null`

**Comment by mattroos** [comment]
Thanks, @614nK! I turns out that in my UI, the Label List section was covering up the Polygon Labels section, so I didn't even know the Polygon Labels section existed. Fixed that, and all is well.
