### ISSUE TITLE
While annotating Semantic Segmentation example  with "labelme data_annotated --labels labels.txt --nodata --validatelabel exact --config '{shift_auto_shape_color: -2}' " command, it says UNRECOGNIZED AURGUMENTS: -2

### ISSUE THREAD

**Issue by Muhibullah1** [wkentaro/labelme#850]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Labelme Version [e.g. 4.2.9]

**Additional context**

**Comment by Muhibullah1** [comment]
any help in this regard would be greatly appreciated

**Comment by wkentaro** [comment]
Probably you need to use `"{shift_auto_shape_color: -2}"` instead of `'{shift_auto_shape_color: -2}'` on Windows.
