### ISSUE TITLE
[BUG]issue with running labelme2coco

### ISSUE THREAD

**Issue by halhwadi** [wkentaro/labelme#852]
**Describe the bug**

**To Reproduce**
running the flowing line in ananconda prompt :
>labelme2coco.py images/train data_dataset_coco --labels labels.txt

getting this error:
**"File "C:\Users\Windows10-Desktop\Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model\labelme2coco.py", line 81, in main
    assert class_name == "__ignore__"
AssertionError"**

**Expected behavior**
generating the json file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 10 enterpise]
 - Labelme Version 4.5.7]

**Additional context**
attached:
labels.text
[labels.txt](https://github.com/wkentaro/labelme/files/6255204/labels.txt)

**Comment by wkentaro** [comment]
Probably the first line of labels.txt should be `__ignore__`?
Please follow the examples.

**Comment by EMCP** [comment]
@wkentaro , I had same error because I had `_background_` instead of `__ignore__` .. I think you can close this
