### ISSUE TITLE
Undo is very slow

### ISSUE THREAD

**Issue by jfemiani** [wkentaro/labelme#854]
**Undo is taking a large amount of time (seconds)**

When we have a reasonable number of polygons (e.g. 100) and you undo, it takes seconds before the app is responsive again. 
The app seems to be triggering a huge number of repaints.  
Every time we undo, we update the visibility of each shape.  
When we update the visibility of each shape, it calls `repaint`  which redraws the canvas right away.  
I think that 'repaint' should be replaced with 'update', at least in the methods that are triggered in a loop. 
The `update` method will wait to repaint the screen until the next time the app is idle.  

**To Reproduce**
1. Open an image
2. Add 100+ polygons 
3. CTRL+Z 
4. Press CTR+Z again (and notice how long it takes to happen)

**Expected behavior**
It immediately undoes the change and then is responsive by the time I press CTRL+Z again. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5
 - Labelme Version 4.5.6  (cloned from git)

**Additional context**
I have actually fixed this locally be replacing some calls to 'repaint' with 'update'. I plan to submit a pull request, but I think you would wanrt an active issue first.

**Comment by wkentaro** [comment]
Closed via #856
