### ISSUE TITLE
Configurabel undo stack size

### ISSUE THREAD

**Issue by jfemiani** [wkentaro/labelme#855]
**Is your feature request related to a problem? Please describe.**
I can only undo the last 10 actions -- I would like to be able to undo more. 

**Describe the solution you'd like**
A configuration variable under the `canvas` section that lets me specify `num_backups` to be something other the the currently hardcoded number (10).  I would also like to be able to specify the number at the command line as `--num-backups 100` or similar. 

**Describe alternatives you've considered**
None -- I can understand worrying about RAM. 
One alternative could be to create 'backup` files so that, even with autosave, you can revert to an earlier version of the file. 
However, this is still far from ideal as I could just have done that myself. The issue is if I make a lot of changes and then change my mind or realize I made a mistake. 

**Additional context**

**Comment by wkentaro** [comment]
Closed via #856
