### ISSUE TITLE
AssertionError: rgb shape must be (H, W, 3) [BUG]

### ISSUE THREAD

**Issue by codePerfectPlus** [wkentaro/labelme#857]
**Describe the bug**

while converting labelme2voc, I am facing the below error.
```
assert rgb.shape[2] == 3, "rgb shape must be (H, W, 3)"
AssertionError: rgb shape must be (H, W, 3)
```
**To Reproduce**
1. Go to 'labelme2voc.py'
2. Click on ''

**Expected behavior**

It's converting in VOC format successfully for some images but after 40-50 images I am getting the above error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10 20H2]
 - Labelme Version [labelme 4.5.7]

**Additional context**

**Comment by wkentaro** [comment]
Probably your images contain gray file?

**Comment by codePerfectPlus** [comment]
Thanks @wkentaro, you are right. The issue was due to gray file.

**Comment by codePerfectPlus** [comment]
> What is a gray image and how to detect?

Gray file:- Image with colors. Gray image are 2D array. Which have range 0 to 255(usually) and color image are 3D array(R G B).

**Comment by jlgiorio** [comment]
> Thanks @wkentaro, you are right. The issue was due to gray file.

Good evenning, how do you fixed it? I got this issue last week on my dataset.
thanks

**Comment by codeperfectplus** [comment]
> > Thanks @wkentaro, you are right. The issue was due to gray file.
> 
> Good evenning, how do you fixed it? I got this issue last week on my dataset. thanks

you can apply some check conditions to check if it's a 2D array image or a 3D array image.
