### ISSUE TITLE
what is the way of using image-level flags

### ISSUE THREAD

**Issue by neouyghur** [wkentaro/labelme#868]
Hi, I could don't find any example regarding "flags" usage. Is there any related example like labelme2voc for flags. What is the best way to use flags for training? Thanks.

**Comment by wkentaro** [comment]
See https://github.com/wkentaro/labelme/tree/master/examples/classification

**Comment by neouyghur** [comment]
I know how to labeling, but didn't see any example about how to extract this labeling information.

**Comment by wkentaro** [comment]
Does the below example help?

```
import json
with open("image.json") as f:
    flags = json.load(f)["flags"]
```

**Comment by neouyghur** [comment]
Thanks. It is similar to my solution.
