### ISSUE TITLE
how to create the chinese exe

### ISSUE THREAD

**Issue by Enn29** [wkentaro/labelme#870]
how to create the chinese file, which file need to modify

**Comment by MrWindWz** [comment]
`osp.dirname(osp.abspath(__file__)) + "/translate"` this line cannot find the right .ts path

**Comment by MrWindWz** [comment]
![image](https://user-images.githubusercontent.com/15726324/119626809-2866af00-be3e-11eb-84d7-88b07d1a9ed3.png)
I modified this bug myself, made it Chinese, and added a visual label floating window.

**Comment by Enn29** [comment]
> `osp.dirname(osp.abspath(__file__)) + "/translate"` this line cannot find the right .ts path

Thank you for your quick reply. i modify the labelme.spec file, but it isn't ok

`a = Analysis(
    ['labelme/__main__.py'],
    pathex=['labelme'],
    binaries=[],
    datas=[
        ('labelme/config/default_config.yaml', 'labelme/config'),
        ('labelme/icons/*', 'labelme/icons'),
	('labelme/translate/*', 'labelme/translate'),
    ],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
)`

**Comment by MrWindWz** [comment]
The .spec is right, you need to modify that line code I pasted.



在时间的唇上抹上一缕微笑！


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wkentaro/labelme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月26日(星期三) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wkentaro/labelme] how to create the chinese exe (#870)





  
osp.dirname(osp.abspath(__file__)) + "/translate" this line cannot find the right .ts path
  
Thank you for your quick reply. i modify the labelme.spec file, but it isn't ok
 
a = Analysis( ['labelme/__main__.py'], pathex=['labelme'], binaries=[], datas=[ ('labelme/config/default_config.yaml', 'labelme/config'), ('labelme/icons/*', 'labelme/icons'), ('labelme/translate/*', 'labelme/translate'), ], hiddenimports=[], hookspath=[], runtime_hooks=[], excludes=[], )

**Comment by Enn29** [comment]
I try to modify the line code, the exe file is still dependent on the tranlate. can you tell me how to modify them.
I want to generate a separate EXE file which include the Translate folder.
thanks!

**Comment by MrWindWz** [comment]
I will show it in github.
&nbsp;

在时间的唇上抹上一缕微笑！


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月27日(星期四) 上午9:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wkentaro/labelme] how to create the chinese exe (#870)





 
I try to modify the line code, the exe file is still dependent on the tranlate. can you tell me how to modify them.
 I want to generate a separate EXE file which include the Translate folder.
 thanks!
 
&mdash;

**Comment by MrWindWz** [comment]
I fixed it by in __main__.py, you can find it in #834, here is the code [ link](https://github.com/wkentaro/labelme/pull/834/commits/5e72ced56f7b0524e2219e47417e7652c19264d4).
> translator =  #QtCore.QTranslator()
> translator.load(QtCore.QLocale.system().name(), config_info.translate_dir,)    **here need a absolute path**

**Comment by Enn29** [comment]
thanks for your help!
