### ISSUE TITLE
[BUG] Open Dir not working correctly.

### ISSUE THREAD

**Issue by ranbims** [wkentaro/labelme#882]
**Describe the bug**
I have a collection of labled files with json format. I want to review them with labelme. I launched labelme and clicked 'Open Dir' in the menu list. I selected the folder containing the labeled files. But nothing happend.

**Comment by wkentaro** [comment]
Use `--output` to specify a directory that contains annotated JSON files.
See https://github.com/wkentaro/labelme/issues/1009#issuecomment-1173020775
