### ISSUE TITLE
Group ID

### ISSUE THREAD

**Issue by chiba1sonny** [wkentaro/labelme#888]
I want to label the zebra line with polygons. Since zebra line is composed of many lines. Do I need to write group ID(1) (2) (3) for every line, or all of them are grou ID(0) ?

**Comment by wkentaro** [comment]
Does this answer your question?
https://github.com/wkentaro/labelme/issues/633

**Comment by chiba1sonny** [comment]
I guess so. In my case, I need to set all the group ID as 0 for every line in one group of zebra lines. And if there are two groups of zebra lines in one image, I need to set the group ID of another zebra line as 1.  And if there are three, it is 0, 1, and 2. Right?

Many thanks.

**Comment by wkentaro** [comment]
Yes, I think so.
