### ISSUE TITLE
[Feature]windows system

### ISSUE THREAD

**Issue by Enn29** [wkentaro/labelme#891]
I use labelme.exe in win8 system(32bit), but it has a problem.
![image](https://user-images.githubusercontent.com/63645468/126267245-55798358-e623-409c-9a39-dd6e1145b4fc.png)
The labelme.exe is created by win10(64bit), how can i slove the issue.

**Comment by Cube707** [comment]
you cannot run x64 exe-files on a x32 system. This is totally expected.

@wkentaro I recomend closing this
