### ISSUE TITLE
[Feature] save the json quitely

### ISSUE THREAD

**Issue by sycophant-stone** [wkentaro/labelme#902]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when labeling with a lot of images, the rhythm is always Interrupted by the `save` operations.

**Describe the solution you'd like**
as far as I know, the `save` is not necessary, especially for `open-dir` scene. it would be better if the saving operation is done quietly(by back ground).

**Comment by YacobBY** [comment]
@sycophant-stone There's a "save automatically" option, if you tick it before opening an image it will just save any changes you make when you go to the next image
