### ISSUE TITLE
 The key point belongs to the bbox, how to label the information?

### ISSUE THREAD

**Issue by hande6688** [wkentaro/labelme#904]
How to mark the key points of the face and the face frame at the same time?How to judge whether the key points of a human face belong to a human face? How to judge whether the key points of a human face are not on the face?

**Comment by wkentaro** [comment]
Group id is meant to be used for this purpose.
See https://github.com/wkentaro/labelme/tree/main/examples/instance_segmentation#annotation for an example of how to use group id to annotate separated polygons (e.g., sofa with middle part occluded by people).
