### ISSUE TITLE
Annotation of instance id

### ISSUE THREAD

**Issue by wkentaro** [wkentaro/labelme#91]
Maybe with a small textbox right side of the label name.
I think this is necessary if I implement after #90 because the #90 will forbid labels like `person-1`, `person-2`.

**Comment by jbvo** [comment]
Is this really required?
In my current use of labelme, I apply the same label more than once and everything seems to be working fine. To see which label matches to which polygon it allows me to select an item in the label list and the matching polygon will be highlighted, even if there are multiple polygons with the same label name.

Note: in the pull request I noticed that the QComboBox's editable property is set to True, so it would still be possible to enter `person-1`, `person-2`, etc.

**Comment by wkentaro** [comment]
Yeah, that's controversial, and I still not decided which is better.

**Comment by wkentaro** [comment]
> Note: in the pull request I noticed that the QComb

Yeah, but I think it can be changed by some options.

**Comment by wkentaro** [comment]
With creating the example in #101, I think this is not necessary for now.
