### ISSUE TITLE
Disappearing Polygon labels when reordering[BUG]

### ISSUE THREAD

**Issue by andife** [wkentaro/labelme#910]
**Describe the bug**
Reording the polygons with drag&drop lead to the disappearance from the selected polygon.

**To Reproduce**
No systematics found out. With only two polygons it doesn't matter if you try to move the lower polygnon up or the upper down. In both cases the polygnon disaapers. If there are more polynomial, does it seem that the polygnon should not be moved to the first or last position. 
**Expected behavior**
Reorder should not cause disappearning "polygon labels"

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by wkentaro** [comment]
Let's merge this with https://github.com/wkentaro/labelme/issues/783
