### ISSUE TITLE
TypeError: label2rgb() got an unexpected keyword argument 'img'

### ISSUE THREAD

**Issue by cauivy** [wkentaro/labelme#913]
Hi, guys!

My labelme was installed in environment with Win10+Conda env+Python3.6. When I tried to use 'labelme_draw_json' or 'labelme_json_to_dataset' command，following error was reported:

C:\Users\labelme-master\examples\tutorial>labelme_draw_json apc2016_obj3.json
Traceback (most recent call last):
  File "c:\users\zhourong\anaconda3\envs\labelme_py36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\zhourong\anaconda3\envs\labelme_py36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\zhourong\anaconda3\envs\labelme_py36\Scripts\labelme_draw_json.exe\__main__.py", line 7, in <module>
  File "c:\users\zhourong\anaconda3\envs\labelme_py36\lib\site-packages\labelme\cli\draw_json.py", line 44, in main
    loc="rb",
TypeError: label2rgb() got an unexpected keyword argument 'img'

Does anyone get the same problem and have the solution. Thanks in advance!

**Comment by Chao86** [comment]
> Hi, guys!
> 
> My labelme was installed in environment with Win10+Conda env+Python3.6. When I tried to use 'labelme_draw_json' or 'labelme_json_to_dataset' command，following error was reported:
> 
> C:\Users\labelme-master\examples\tutorial>labelme_draw_json apc2016_obj3.json
> Traceback (most recent call last):
> File "c:\users\zhourong\anaconda3\envs\labelme_py36\lib\runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "c:\users\zhourong\anaconda3\envs\labelme_py36\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\zhourong\anaconda3\envs\labelme_py36\Scripts\labelme_draw_json.exe__main__.py", line 7, in
> File "c:\users\zhourong\anaconda3\envs\labelme_py36\lib\site-packages\labelme\cli\draw_json.py", line 44, in main
> loc="rb",
> TypeError: label2rgb() got an unexpected keyword argument 'img'
> 
> Does anyone get the same problem and have the solution. Thanks in advance!

I get the same issue, have you sovled it? Can you offer some help? @wkentaro

**Comment by Chao86** [comment]
> > Hi, guys!
> > My labelme was installed in environment with Win10+Conda env+Python3.6. When I tried to use 'labelme_draw_json' or 'labelme_json_to_dataset' command，following error was reported:
> > C:\Users\labelme-master\examples\tutorial>labelme_draw_json apc2016_obj3.json
> > Traceback (most recent call last):
> > File "c:\users\zhourong\anaconda3\envs\labelme_py36\lib\runpy.py", line 193, in _run_module_as_main
> > "**main**", mod_spec)
> > File "c:\users\zhourong\anaconda3\envs\labelme_py36\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\zhourong\anaconda3\envs\labelme_py36\Scripts\labelme_draw_json.exe__main__.py", line 7, in
> > File "c:\users\zhourong\anaconda3\envs\labelme_py36\lib\site-packages\labelme\cli\draw_json.py", line 44, in main
> > loc="rb",
> > TypeError: label2rgb() got an unexpected keyword argument 'img'
> > Does anyone get the same problem and have the solution. Thanks in advance!
> 
> I get the same issue, have you sovled it? Can you offer some help? @wkentaro

@cauivy , hi, I have tackled this issue, just changed the parameter's name 'img' into image in the code.  The reason is listed as the following picture.
![捕获](https://user-images.githubusercontent.com/44365146/132453932-bc1db1eb-d9e9-4af0-9426-b779d07e6773.PNG)

**Comment by HelloCentaurus** [comment]
@Chao86 thank you very much！it is worked！
![f9bc752dd358446fd82d304aee673b9](https://user-images.githubusercontent.com/15262893/132456358-89e8b1ce-8d4f-4a4b-a67f-2d25045d47a2.png)

**Comment by linn345** [comment]
thankyou very much！it helps me a lot

**Comment by mylwx** [comment]
try change the version of imgviz,the command is as follow

pip install -i https://pypi.tuna.tsinghua.edu.cn/simple imgviz==1.2.0
