### ISSUE TITLE
keypoints annotation

### ISSUE THREAD

**Issue by XiaopinWang** [wkentaro/labelme#921]
Hi，The key point data of coco format is [x,y, v], Labelme can only mark x and Y coordinates, may I ask how to deal with occlusion but mark this situation (v=1), thank you！

**Comment by wkentaro** [comment]
I'm not very familiar with the coco format. Can you explain what is v?

**Comment by XiaopinWang** [comment]
First of all, thanks for the reply. When v is 0, it means that the key point is not marked (x = y = v = 0). When v is 1, it means that the key point is marked but invisible (occluded). When v is 2, Key points are marked and visible at the same time. Labelme does not provide a v=1 processing mode, so I would like to ask if you will provide this function, thank you.

**Comment by wkentaro** [comment]
I understand.

> Labelme does not provide a v=1 processing mode

Regarding this part, Labelme is not providing any examples of keypoint annotation, in my understanding.
Which one do you mean the function of keypoint annotation in Labelme?

I see that you can use Labelme to annotate keypoints, and you can annotate keypoints as the following:

```
{"label": "eye-left-visible", "shapes": [(x1, y1), ], "shape_type": "point"},
{"label": "eye-right-occluded", "shapes": [(x2, y2), ], "shape_type": "point"},
```

and convert it to coco format as the following, right?

```
[(x1, y1, v=2), (x2, y2, v=1)]
```

**Comment by XiaopinWang** [comment]
The function I am talking about is to handle (v=1) this mode. I saw the example you provided. I know how to handle it now. Thank you for your reply.

**Comment by DWendou** [comment]
> The function I am talking about is to handle (v=1) this mode. I saw the example you provided. I know how to handle it now. Thank you for your reply.

Why don't I see examples of points like (x,y,v)? How to display and adjust the value of v?
