### ISSUE TITLE
Next and previous button take more than 5 seconds to execute

### ISSUE THREAD

**Issue by NathanJanniaux** [wkentaro/labelme#924]
I have installed the newest version 4.5.12 with anaconda, and when I annotate the image and save it, I found the json-file quite big with the imageData tag and when I click on the next button our on the previous button, it takes more than 5 seconds each time. Is there a way to accelerate the change of image? 

Thank you

**Comment by NathanJanniaux** [comment]
No I haven't try on an older version. Before using your soft, I was using LabelImg which is graphically quite similar and there was no latence. Your application is has no latence on the other functions but just on this one. I use a professional computer very powerfull to run the application so that is surprising. I have seen that the json annotations are bigger than the images, I think this is due to imageData tag. Is it possible to remove easly the generation of this tag ?

**Comment by wkentaro** [comment]
Yeah, you can use `labelme --nodata image.jpg`.

**Comment by NathanJanniaux** [comment]
Super, thank you !
