### ISSUE TITLE
[Feature] human pose

### ISSUE THREAD

**Issue by alicera** [wkentaro/labelme#925]
Does it support human pose label?
For example:
The image have two person.
And label know the keypoint is which person.

**Comment by wkentaro** [comment]
Group id is meant to be used for this purpose.

**Comment by alicera** [comment]
But a person have many keypoint name, like nose, eyes, ears, ...
I only know I can name it nose_1, lefteye_1, .... and use point to label. But it doesnt make sense

**Comment by wkentaro** [comment]
I mean group_id, not something like `<label_name>_1`.

the`0` in the following example.
![image](https://user-images.githubusercontent.com/4310419/141291563-6b332f73-8286-41a9-ac8c-61fb1c0de6ae.png)

**Comment by alicera** [comment]
tks

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can read/write/export keypoints in the YOLO format.
https://rectlabel.com/help#xml_to_yolo

```
class_index center_x center_y width height x1 y1 v1 x2 v2 y2 x3 y3 v3 ...
0 0.545230 0.616880 0.298794 0.766239 0.522073 0.309332 2 0.540170 0.293193 2 0.499589 0.296503 2 ...
```

A visibility flag v defined as v=0: not labeled (in which case x=y=0), v=1: labeled but not visible, and v=2: labeled and visible.
https://cocodataset.org/#format-data

![yolo_polygon](https://user-images.githubusercontent.com/1954306/209942647-fa9565e0-d4cf-42c2-a382-a8043465765b.jpg)
