### ISSUE TITLE
Pick images that I want

### ISSUE THREAD

**Issue by alicera** [wkentaro/labelme#928]
If I have 10000  images to label. How to pick the image that I want and move it to another folder ?  I only need pick 100 images in 10000 images.

**Comment by wkentaro** [comment]
You can probably create a shell script for that.
```bash
mkdir images_100
image_files=($(ls images_10000))
for i in $(seq 1 ${#image_files[@]}); do
  if [ $(expr $i % 100) = 1 ]; then
    cp images_10000/${image_files[$i]} images_100/
  fi
done
```

**Comment by alicera** [comment]
I have to see the label image  and decide to pick it or drop it.

**Comment by wkentaro** [comment]
No, it can't. I suggest using `--flags` option. After annotation, you can refer `"flags"` data in the JSON to skip un-picked files.

```
# example
labelme --flags pick examples/video_annotation/data_annotated/
```

**Comment by alicera** [comment]
How can I add new button in labelme, quickly? Maybe I can add the button for custom.

**Comment by wkentaro** [comment]
> How can I do with flags?

See https://github.com/wkentaro/labelme/tree/main/examples/classification#classification-example
