### ISSUE TITLE
[Feature] Permanently set brightness and contrast in .labelmerc

### ISSUE THREAD

**Issue by shunmian** [wkentaro/labelme#929]
**What is your question? Please describe.**
Is there a way to permanently set `brightness` and `contrast` in .labelmerc ?

**Comment by wkentaro** [comment]
No, but there's an option to keep the brightness in the previous image annotation if that works for you.
```
keep_prev_brightness: true/false
keep_prev_contrast: true/false
```

**Comment by shunmian** [comment]
This is good enough, thanks @wkentaro
