### ISSUE TITLE
[INFO   ] __init__:get_config:71 - Loading config file from: /root/.labelmerc

### ISSUE THREAD

**Issue by Note-Liu** [wkentaro/labelme#941]
when i use docker to install labelme:

sudo docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=:0 -v $(pwd):/workdir wkentaro/labelme

[INFO   ] __init__:get_config:71 - Loading config file from: /root/.labelmerc
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.

**Comment by wkentaro** [comment]
Did you run this? `xhost +`
