### ISSUE TITLE
why labelme can't next images as in a sorted sequence as like in folder?

### ISSUE THREAD

**Issue by Aliktk** [wkentaro/labelme#953]
**What is your question? Please describe.**
I am doing a large data labeling using label me. I have 3k images where each has BB but I am labeling using a new method. But problem is that I am double-checking the image and its bounding box annotation parallel. But when I open the directory the images are not sorted. 

when I click **next** image then it just shows me a random image, not a sequence-wise image.

**Describe what you have tried so far**
try to find a way that makes them sorted during showing the next image.
Thanks

**Comment by wkentaro** [comment]
Can you give examples of your actual problem?

**Comment by Aliktk** [comment]
I am doing labeling images using lableme.  whenever I am liking the next images I got a random image not a sequence of images in the folder.

if you get my point please verify that.

**Comment by wkentaro** [comment]
Without examples, I can’t see why it is happening.
