### ISSUE TITLE
[BUG] labelme_draw_json and labelme_json_to_dataset not working on macOS

### ISSUE THREAD

**Issue by aestarita** [wkentaro/labelme#983]
I am running "labelme_draw_json" and "labelme_json_to_dataset" on macOs Monterrey through the terminal, but neither of these two work. Both show a " Command not found ". 
I installed through homebrew and command labelme works fine. Only these two do not work.
Thank you

**Comment by wkentaro** [comment]
With installed via brew, these commands are not installed. You need install via `pip`.
