### ISSUE TITLE
multiple labels output in different colors each time json file is converted to png

### ISSUE THREAD

**Issue by rexxar0105** [wkentaro/labelme#995]
As you can see that after labeling the 3 classes they come out in different colors after extracting from the json file. i want each of them to be of distinct colors. 
Can you help?

![label](https://user-images.githubusercontent.com/81734615/155832597-226f720e-11a3-4847-bf50-44b95883e0a3.png)
![label](https://user-images.githubusercontent.com/81734615/155832601-f7b58fcf-f01d-4e4d-b392-a77506a9006c.png)
![label](https://user-images.githubusercontent.com/81734615/155832607-a199164a-66d9-4866-ab98-6e4d4e447865.png)

**Comment by wkentaro** [comment]
https://github.com/wkentaro/labelme/tree/main/examples/semantic_segmentation
